### ISSUE TITLE
FNX-3272 ⁃ [Bug] Pages with embedded content sometimes scroll toolbar, sometimes doesn't (like Github)

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10073]
* [ ] GV Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1633322

## Steps to reproduce
1. Go to: https://github.com/mozilla-mobile/fenix/issues/new
1. Type in something in the discription field which is at least a few lines.
1. Go back/press back button and come forward. 
1. Now move the text in the discription field up and down.
1. Observe that it triggers the bottom toolbar which it should not. Sometimes the toolbar never appears no matter where you click or move the page 

### Expected behavior
Shouldn't trigger bottom toolbar

### Actual behavior
Triggers the bottom toolbar

### Device information
* Android device: Motorola One Power, Android 10
* Fenix version: Nightly 200420 06:01 (Build #2015735603)
![20200421](https://user-images.githubusercontent.com/42088907/79822386-91990a80-8380-11ea-8f01-564268cdcac9.gif)UNITO-UNDERSCORE!085041!

**Comment by sblatz** [comment]
I believe this is caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1631754 and is similar to https://github.com/mozilla-mobile/fenix/issues/10045

**Comment by fluffyemily** [comment]
Fix landed 14th May 2020 and is available in GeckoView 78.

**Comment by SS1113** [comment]
@fluffyemily I can still reproduce the issue on today's Nightly.

**Comment by liuche** [comment]
@sblatz is there anything that Fenix needs to do to pick up the GV bugfix, for this issue or #10045?

**Comment by sblatz** [comment]
I can not reproduce this anymore on the latest nightly. I've tested on github projects, spotify embedded playlist, and ublock filter list. Please verify again, QA 😄 


![spotify demo 2020-06-03 15_27_24](https://user-images.githubusercontent.com/4400286/83695369-bce15d00-a5ae-11ea-8ffc-17797ed90012.gif)

![demo of ublock 2020-06-03 15_26_56](https://user-images.githubusercontent.com/4400286/83695378-c074e400-a5ae-11ea-8751-ff77a5fb7b8e.gif)

**Comment by SS1113** [comment]
@sblatz I can confirm that the issue not reproducible anymore on GitHub and Ublock Origin. However, the toolbar hides the contents of Ublock Origin's "Restore to default settings..." Button in settings and on GitHub the contents at the bottom are not visible. 

And also the bottom toolbar never hides when on GitHub.

![Screenshot_20200604_081057](https://user-images.githubusercontent.com/42088907/83709298-be8e3d80-a60d-11ea-9bd1-86f8f6f606fc.jpg)
![Screenshot_20200604_081313](https://user-images.githubusercontent.com/42088907/83709334-cbab2c80-a60d-11ea-8daf-189af0b22e04.jpg)

**Comment by sflorean** [comment]
Environment: Google Pixel 3 (Android 10), and Nokia 6 (Android 7.1.1) on Nightly 6/4.

- for the duplicated issue #10978
I can confirm that the toolbar is displayed when scrolling up/down on Github: - Fenix Releases, Fenix issues pages.

 ** uBlock - Filter list**
Toolbar set to bottom: the same result: the toolbar is not hiding, when scrolling up and down.
Toolbar set to top: no issues displayed.

**Embedded content** - Github new issue
Toolbar set to bottom: the same result: the toolbar is not hiding, when scrolling up and down.
Toolbar set to top: see the video.

![ezgif com-optimize](https://user-images.githubusercontent.com/58466444/83778023-cd6b0380-a692-11ea-9720-7c1d596e7071.gif)

@sblatz can you please add your thoughts regarding our results? thank you!

**Comment by sblatz** [comment]
So there are two issues here: 
1. When the dynamic bottom toolbar is enabled, on a site that returns HANDLED events on every press, the toolbar is impossible to scroll, but also the bottom content is hidden because it's not a "fixed" toolbar. 

2. With a top dynamic toolbar, embedded content still scrolls. See really bad case here: https://open.spotify.com/artist/2fbUQIKSBTohTK6tHaFGYV?nd=1

@fluffyemily / @snorp how should we handle this first case? I think the second issue is on our side.

**Comment by sblatz** [comment]
I wonder if addons are a separate case here.

**Comment by sblatz** [comment]
This is also affecting error pages: https://github.com/mozilla-mobile/fenix/issues/10477

**Comment by abodea** [comment]
Hi, @sblatz is this issue also fixed based on the GV fixes from https://github.com/mozilla-mobile/fenix/issues/10045?

**Comment by liuche** [comment]
For #1, got an answer from snorp that GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1633322 is probably related.

@sblatz you mentioned #2 is on the Fenix side? If we can get this turned on for our next release then we'll have some time to fix it in code freeze.

**Comment by sblatz** [comment]
This top bar bug is in nightly and is unrelated to the bottom toolbar. I'm going to file a new bug for it. That being said, I think it's important and will pull it into this sprint to see if I can figure out a fix.

**Comment by sblatz** [comment]
Top bar issue is here: https://github.com/mozilla-mobile/fenix/issues/11388

**Comment by sblatz** [comment]
I'm going to close this issue as it has been fixed for bottom dynamic toolbar. The outstanding issues are filed as: 
- https://github.com/mozilla-mobile/fenix/issues/10477
- https://github.com/mozilla-mobile/fenix/issues/11388
- https://github.com/mozilla-mobile/fenix/issues/11389

**Comment by softvision-miralobontiu** [comment]
Reproducible on the latest Beta 5.2.0-beta.1, using Samsung Galaxy Tab S6 (Android 9) - the https://github.com/mozilla-mobile/fenix/issues page did not have the dynamic bottom navbar.

**Comment by SS1113** [comment]
@sblatz @liuche I cannot click the bottom contents even if they are visible, this happens on YouTube comments section and on reddit and at other websites too! Is there an open issue for that? Since this issue is closed now.

**Comment by sblatz** [comment]
Yes, that's https://github.com/mozilla-mobile/fenix/issues/11189 & https://github.com/mozilla-mobile/fenix/issues/11356 :)
