### ISSUE TITLE
FNX3-13771 ⁃ Add call/email intents to the text selection toolbar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10260]
### Why/User Benefit/User Problem
As a user, I want to be able to initiate a phone call, text message, or email from within the browser content, so I don't have to manually copy a phone number and paste it into other Android apps such as "phone", "email" app. 

### Acceptance Criteria (how do I know when I’m done?)
* When I highlight a phone number, I see intents such as "call" depending on supported apps I have installed. Once I tap on an intent, Fenix will open that app and pass the phone number to it. 
* When I highlight an email address, I see an "email" intent depending on supported apps I have installed. Once I tap on an intent, Fenix will open that app and pass the email address to it. 

Screenshots from Chrome (for clarification purposes)
![Screenshot](https://user-images.githubusercontent.com/42752644/80446561-25208d00-88e5-11ea-87fc-8e9d3fe0466b.png)UNITO-UNDERSCORE!20200428-000108!
![Screenshot](https://user-images.githubusercontent.com/42752644/80446566-281b7d80-88e5-11ea-8457-8cd0b3e2f84f.png)UNITO-UNDERSCORE!20200428-000141!
![Screenshot](https://user-images.githubusercontent.com/42752644/80446569-2a7dd780-88e5-11ea-9280-f6ba292d8bf9.png)UNITO-UNDERSCORE!20200428-000116!

**Comment by vesta0** [comment]
Let's find out what we need to make this happen? Is there GV work involved?

**Comment by liuche** [comment]
@gabrielluong what do you think - is this mainly AC work to pattern-match these types of highlighted text, or does GV need to expose something?

**Comment by brampitoyo** [comment]
@liuche @vesta0 This would be great, but in order to be useful, it also needs to be context sensitive:

- “Call” and/or “Message” should only appear when the text highlighted is a phone number
- “Email” should only appear when the text highlighted is an email address

Let’s also make sure that it doesn’t conflict with other options on the context menu: Copy, Search, Select all, Share, Search privately, Find in page, etc. We should figure out the right ordering.

**Comment by vesta0** [comment]
Thanks @brampitoyo :) I had already created #10466 to track the "re-ordering work" and I see that you are already on it. 

Once you have completed your UX investigation/feedback, please add `eng-ready` to this issue.

**Comment by AmyYLee** [comment]
@brampitoyo Is this still a WIP?

**Comment by kbrosnan** [comment]
Detecting phone numbers universally is quite hard. What is in scope for this? https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers on top of this there are dial codes such as `,` for pause and `;` for wait among others.

**Comment by vesta0** [comment]
@kbrosnan would be good to find out what logic Fennec uses.

**Comment by person808** [comment]
For detection of the type of text highlighted I believe [this](https://developer.android.com/reference/androidx/textclassifier/TextClassifier) is the api to use. 

[This](https://source.android.com/devices/tech/display/textclassifier) page has more details

**Comment by brampitoyo** [comment]
@AmyYLee Thanks for confirming. This is no longer work-in-progress. We can, and should, add intents to context menu. But note that doing so may take some time (and as @kbrosnan wrote, involve many exceptions as phone numbers are formatted differently across countries) – so we may not be able to do it in the short term.

**Comment by kbrosnan** [comment]
It looks like the code that implemented phone number detection was in [bug 1235508](https://bugzilla.mozilla.org/show_bug.cgi?id=1235508). The code still lives in mozilla-central in more or less the same place [AccessibleCaretManager::IsPhoneNumber](https://searchfox.org/mozilla-central/source/layout/base/AccessibleCaretManager.cpp#927) but would need a GV and AC API for Fenix to use it. It is fairly liberal in what it detects as a phone number. If I am reading the regexp correctly it can start with `()` then sets of digits with numbers separating them up to 30 characters long. Doing some adhoc testing with phone numbers it accepts almost all numbers I found.

Fennec had some JS regexp code that attempted to [detect strings that looked like US phone numbers](https://hg.mozilla.org/releases/mozilla-esr68/file/tip/mobile/android/chrome/content/Linkify.js#l9) in the traditional format `(###)-###-####` or `###-###-####` country codes were also accepted but I left them off as they are uncommon in the US. This solution was very expensive for performance and was never shipped as a default.

```
Passing
555-555-5555
(555)-555-5555
01-555-555-5555

Failing
555.555.5555
555 555 5555
(555) 555-5555
```

**Comment by liuche** [comment]
Let's do this as a fast-follow to release, not a release blocker.

**Comment by sblatz** [comment]
I think this requires adding a new custom action to DefaultSelectionActionDelegate in AC. I'm looking now to see if this would require GV, but my guess is, as long as we're not detecting it on page load (and requiring people to SELECT the text first), this should definitely be possible without a perf hit.

**Comment by sblatz** [comment]
I have a solution with changes only to AC that I think will work. PR will be up shortly 😄

**Comment by sblatz** [comment]
AC PR: https://github.com/mozilla-mobile/android-components/pull/7587

**Comment by Diana-Rus** [comment]
Hi, verified the issue with Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7) on latest Nightly 7/16:
- For hyperlinked email and phones an "Open with" box is displayed ✔️
- For non linked emails and phone numbers the "Email"/"Call" options will be displayed in the context menu primary options in both normal and private mode ✔️
- In case of more than one app installed of mail or phone number type an "Open with" or "Call with" is displayed ✔️
- The "Email"/"Call" option is present in Custom tab as well ✔️

Could you please check the below questions:
1. For text format of the phone numbers and emails, the context menu will not have from start options Email/Call as it will select the space before first character and last character as well. 
The user will have to move the handles for the selection. Should the selection be left as it is?
<details closed><summary>GIF</summary>

![20200716-150702](https://user-images.githubusercontent.com/49859863/87670649-c1399200-c778-11ea-849d-d64b8ba0bb9e.gif)</details>

2. Should the email/phone application icon be visible for the user in the context menu, for example of the last used one by the user? Or in case there is only one app of it's kind then have the icon displayed?

**Accepted format:**
55 555 5555
555-555-5555
(555)555-5555
(555) 555-5555
+44 (5) 5555-5555
555 555 5555
1-555-555-5555
5555425555
555.555.5555
5-555-555-5555
5 555 555 5555

**Failed formats:**
5-(555)-555-5555
(+55)(5)55-12345678
1(519) 555-4444
1 (519) 555-4422

<details closed><summary>Testing site</summary>
- https://regexlib.com/Search.aspx?k=phone&c=-1&m=-1&ps=20
- https://stackoverflow.com/questions/26713672/phone-number-match-regular-expression
</details>

**Comment by sblatz** [comment]
I'm addressing the whitespace issue in an AC PR: https://github.com/mozilla-mobile/android-components/pull/7781

**Comment by sblatz** [comment]
This should be addressed now. @Diana-Rus can you please verify that the whitespace issue no longer happens? :)

**Comment by Diana-Rus** [comment]
Hello, issue is still reproducible on latest Nightly 7/20

Verified with:
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3 XL (Android 9)

Results:
- For domain https://www.attinternetservice.com/call/ - the space before the first character is still selected for the non linked phone number - with both devices
![Screenshot_20200727-112248_Firefox Nightly](https://user-images.githubusercontent.com/49859863/88520532-5bf96280-cffc-11ea-9bd7-4ef1abca5820.jpg)

- For domain https://regexlib.com/Search.aspx?k=phone&c=-1&m=-1&ps=20 - the space after the last character is still selected for the non linked phone number
![Screenshot_20200727-112916_Firefox Nightly](https://user-images.githubusercontent.com/49859863/88521048-12f5de00-cffd-11ea-980d-225f15f1fc51.jpg)

- For domain https://stackoverflow.com/questions/26713672/phone-number-match-regular-expression - besides the last space will take in consideration also the punctuation mark (comma)
![Screenshot_20200727-113507_Firefox Nightly](https://user-images.githubusercontent.com/49859863/88521372-7d0e8300-cffd-11ea-99b1-4c8ab065231f.jpg)


<details><summary>Testing sites:</summary>
- https://www.attinternetservice.com/call/
- https://regexlib.com/Search.aspx?k=phone&c=-1&m=-1&ps=20
- https://stackoverflow.com/questions/26713672/phone-number-match-regular-expression
</summary>

**Comment by Diana-Rus** [comment]
Re-tested, issue still reproducible with Nightly 7/27 from playstore with Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9) 
- For domain attinternetservice.com/call - first space before first character is still selected for non linked phone numbers
<details><summary>Gif-Google Pixel</summary>

![20200727-121834](https://user-images.githubusercontent.com/49859863/88525970-fdd07d80-d003-11ea-941f-553c1ac166ed.gif)
</details>
- For domain https://regexlib.com/Search.aspx?k=phone&c=-1&m=-1&ps=20 - the space after last character is still selected for the non linked phone numbers
![Screenshot_20200727-123327](https://user-images.githubusercontent.com/49859863/88526967-4b011f00-d005-11ea-8606-c7b7c52fdb2c.png)

- For domain https://stackoverflow.com/questions/26713672/phone-number-match-regular-expression - the punctuation mark (comma) and the space after the punctuation mark is selected
![Screenshot_20200727-123105](https://user-images.githubusercontent.com/49859863/88526609-cdd5aa00-d004-11ea-808a-e9eaa5144c22.png)


@sblatz - Could you please take another look at the issue. Could you also please check questions 2 and 3 from my previous comments? For questions 2 the implementation is different from issue's description.

Note: On Chrome when non linked phone numbers are selected neither the first nor the last space is present.

**Comment by sblatz** [comment]
So the space being selected is a GV issue. That's not something I can fix on the Fenix end :( I will file a Bugzilla for that.

For the ones that *only* have a space, it's showing a call button now, so that's the expected behavior :)

**Comment by sblatz** [comment]
Filed Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1655591
