### ISSUE TITLE
FNX3-13805 ⁃ [Bug] The toolbar appears on PWAs if backgrounded

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#10315]
## Steps to reproduce
1. Install and open a PWA (twitter, or 9gag)
1. Tap the task tray button.
1. Return to the app.
    1. Expected behavior
The toolbar should never appear on PWA while you are navigating inside its scope.
    1. Actual behavior
The custom tab toolbar is displayed on the PWA homescreen.
*If you choose to open the page in Fenix, from the custom tab menu, the PWA task is closed.
    1. Device information

* Android device: Pixel 4 (Android 10), HTC Nexus 9 (Android 7.1.1)
* Fenix version: Beta 5.0, Nightly 4/30

LE:
The toolbar appears also if a doorhanger needs to be displayed: permission to access the camera/location for example.

**Comment by ekager** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/10306 in master

**Comment by agi90** [comment]
This is still happening (screenshot from yesterdays Fenix nightly) 
![Screenshot_20200514-173359_Firefox Nightly](https://user-images.githubusercontent.com/4297388/82072756-0bc16400-968d-11ea-84af-23a056880d77.jpg)

I think it happened after I reopened a PWA I hadn't used for a couple of hours.

**Comment by agi90** [comment]
I noticed that opening an instagram story triggers this. Not sure if there are more ways to trigger it.

**Comment by NotWoods** [comment]
I'm not able to reproduce this anymore. Can QA check if this is still an issue?

**Comment by agi90** [comment]
@NotWoods I can easily reproduce on the instagram PWA, open a story tap through the end and after you exit the PWA will have a toolbar.

**Comment by ekager** [comment]
Yeah, it now has to do with videos because on fullscreen, we are hiding the toolbar, but then when fullscreen ends, showing the toolbar again and don't treat PWAs differently right now. You can get it to show again by clicking on a link within the PWA.

**Comment by kbrosnan** [comment]
issue #10452 exists to deal with the full screen problem. Closing as a dupe of #10071 which was fixed by the pr Emily mentioned.
