### ISSUE TITLE
[Bug] Can't fully unzoom images

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#10479]
## Steps to reproduce 
0. Enable scroll to hide toolbar
1. Open [Firefox profile picture on twitter](https://nitter.net/pic/profile_images%2F1399715004010532871%2FH_xS5LMU.jpg)
1. Zoom
1. Unzoom
# Expected behavior
I can fully unzoom, and the image would be shown as when I've not zoomed
# Actual behavior
I can't fully unzoom

### Device information
* Android device: Pocophone F1, Android 9
* Fenix version: latest nightly, i.e. 200507 06 01.21280606. It doesn't happen with stable version, i.e. 4.3.0.21082024).

### Additional information
Here is a gif showing the difference between nightly and stable version:
![Here is a gif showing the difference between nightly and stable version](https://user-images.githubusercontent.com/58657617/81287459-51a97700-9052-11ea-829a-0c1e1f6614de.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-598)

**Comment by Diana-Rus** [comment]
Hi, i also reproduce this issue with Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8)and Sony Xperia Z5 (Android 7) on Nightly 200507 5/7.

**Comment by SL-Lee** [comment]
Kind of similar to #9813.

**Comment by Diana-Rus** [comment]
Hi, @SL-Lee  you are right, thank you for pointing it out, I'm going to leave this one opened, as it has already been triaged and close the other one, i'll also leave here the site so that it can be checked ,when it will be fixed - #9813.

Note - taken from #9813:
- The same problem can be reproduced on page https://bugzilla.mozilla.org/show_bug.cgi?id=1628413 by zooming in and then zooming out fully.

**Comment by hiikezoe** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1652190 for investigation.

**Comment by B0pol** [comment]
I don't know if it is the same issue, but it seems like.

With [this page](https://www.sciencesetavenir.fr/ultrabreves/peuplement-de-l-amerique-sonde-chinoise-sur-mars-et-demence-l-actu-des-sciences-en-ultrabreves_146211), I can't fully unzoom (and it's not an image)

**Comment by madb1lly** [comment]
Hi all,
I've also experience this issue, for example on the WebThings Gateway pages.
Cheers 🙂

**Comment by B0pol** [comment]
The issue on bugzilla is closed as resolved fixed and I updated to Nightly 200724 06:05, tested again:

- I can't reproduce the original bug **in portrait mode**

- I can't reproduce the bug I reported two hours ago

Therefore I modified the title and steps to reproduce

- The same bug happens but with landscape mode this time.

Steps to reproduce:
1. Open [Firefox profile picture on twitter](https://nitter.net/pic/profile_images%2F1138489258207899648%2F9_KBUEn7.jpg)
2. Set landscape mode
3. Zoom
4. Unzoom

**Comment by s-ankur** [comment]
Might be related to#12798

**Comment by ekager** [comment]
The original issue should be fixed by bugzilla.mozilla.org/show_bug.cgi?id=1652190

**Comment by ebalazs-sv** [comment]
This is still reproducible on Nightly 200804 Build #22170943 GV 81.0a1 from 8/4 with Pixel 2 (Android 9). I will remove the qa:needed label for now.
![20200804_143914](https://user-images.githubusercontent.com/48799384/89289781-7668b700-d660-11ea-8174-a20c4d654a41.gif)

**Comment by patel-malav** [comment]
I have made the issue and more details are in here but closed it to keep it confined this issue -> #14793 
and able to reproduce same issue as #9813  in following websites
- [example.com](example.com)
- [svelte.dev](svelte.dev)
- or an basic html5 template with tag

on device OnePlus 7 - android 10 and **Not** on OnePlus5 - android 9

**Comment by B0pol** [comment]
Does not happen with top toolbar and scroll to hide toolbar disabled

**Comment by B0pol** [comment]
Still an issue when scroll to hide toolbar is enabled

**Comment by kevinoid** [comment]
I'm able to reproduce this issue on https://example.com with GVE 2022-04-04 (48ee5b88) on a Pixel 5a running Android 12 (SP2A.220305.012).

I can't find an open bug in Bugzilla for tracking this.  (Since [Bug 1652190](https://bugzilla.mozilla.org/show_bug.cgi?id=1652190) was fixed.)  Should we open a new one?

**Comment by hiikezoe** [comment]
So this issue is originally for image cases. In normal web content cases, I think https://bugzilla.mozilla.org/show_bug.cgi?id=1762255 is a relevant one.

**Comment by kevinoid** [comment]
Thanks @hiikezoe!  FWIW, I'm also able to reproduce the issue with GVE 2022-04-04 (48ee5b88) on https://www.bugzilla.org/img/buggie.png

**Comment by B0pol** [comment]
Still an issue

**Comment by B0pol** [comment]
???
