### ISSUE TITLE
[Bug] Long press to select the text, links or pasting the copied text takes a lot of time

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10618]
## Steps to reproduce
1. Long press to select text or a link 
1. Notice that it takes almost 2 to 3 seconds to select the text or link and even pasting the copied link or text.

### Expected behavior
Long press to select text or a link or pasting a copied link or text must not take 3 seconds, in chrome browser I can do it almost immediately. 

### Actual behavior
Takes a lot of time to select text, link or pasting the copied link/text.

### Device information
* Android device: Motorola One Power, Android 10
* Fenix version: 76.0.0-beta.1 (Build #2015737667) and Nightly 200511 06:21 (Build #2015739635)

**Comment by ekager** [comment]
I can reproduce even on a new device (Pixel 3). Wondering if we can look into this as a possible performance win with GV (I'm assuming GV because these actions are all routed through there) because it does feel quite laggy.

**Comment by mcomella** [comment]
Triage: we have two theories 1) a threshold is defined that delays the pop-up from appearing and it's currently too long or 2) the threshold is fast enough but it's hard to get the proper alignment to trigger it - it requires more precision and less movement, manifesting itself as longer delay. Since this is likely a UX/implementation issue, we're adding it to cross-team issues.

**Comment by ekager** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1652851

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)

**Comment by ShatteredPixel** [comment]
I saw the @snorp's comment on [Bugzilla ](https://bugzilla.mozilla.org/show_bug.cgi?id=1652851) and they are asking if I can reproduce the issue on everywhere or just some websites?



I want to confirm that I can reproduce the issue on _all_ the websites. long press action takes too much time compared to Chrome browser where the I can select by long pressing almost instantly. I can give you screen record if you want. 


Thanks! :)

**Comment by ekager** [comment]
Hm I personally can't reproduce anymore in Nightly. My selection time in Fenix is about equal to Chrome which snorp says should be about 500ms but I'm definitely not seeing 2-3 seconds.
@sheikh-azharuddin can you still reproduce as well?

**Comment by sheikh-azharuddin** [comment]
Na no issue observed anymore probably I think this is fixed...
Let's wait for the original reporter to confirm

**Comment by ShatteredPixel** [comment]
@ekager you tagged the wrong person. 

Yes, I can still reproduce this issue.

**Comment by ShatteredPixel** [comment]
> Na no issue observed anymore probably I think this is fixed...
> Let's wait for the original reporter to confirm

I'm the original reporter sheikh-azharuddin and I can still reproduce the issue!

Thanks! :)

**Comment by sheepycoder** [comment]
I can also reproduce the issue.

**Comment by ShatteredPixel** [comment]
> I can also reproduce the issue.

Can you please list the Firefox version and the device which it is reproducing on?

Thanks! :)

**Comment by ShatteredPixel** [comment]
Please see the screenrecord of the bug: 
[Long press delay.zip](https://github.com/mozilla-mobile/fenix/files/4937705/Long.press.delay.zip)

Extract the file to see the video. Attaching a ZIP file because of the limitations of the GIF format and loss of the video frame rate and sense of time while encoding the video file to GIF.

Device: Motorola One Power, Android 10.
Fenix: Nightly 200714 18:01

Thanks! :)

**Comment by ShatteredPixel** [comment]
I have noticed that this isn't happening on "all" websites as I said earlier. Maybe it was fixed. I'm not sure.  


But I ca still reproduce the issuenis also reproducing on twitter.com while long pressing to copy links or writing a tweet and pasting that link in the tweet. 

This same issue doesn't reproduce on YouTube.com; I can select link and copy/paste text just as speedily as Chrome browser.

**Comment by snorp** [comment]
I sometimes see some delay when long pressing images on twitter, but can't reproduce the problem with links or when composing a tweet. I think twitter uses touch event handlers in some places, so I wonder if that's factoring in here.

**Comment by ShatteredPixel** [comment]
This issue consistently reproduces for me on GitHub mobile website. Anything that I do in the comments box; copying, pasting links or otherwise takes too much time. And even copying links outside the comments box is very time consuming


If you want I can list the website as I discover which websites this issue is reproducing on. I have attached a video in https://github.com/mozilla-mobile/fenix/issues/10618#issuecomment-660081085, please see it.

**Comment by staktrace** [comment]
Looks like the original reporter's account got deleted? At any rate, if anybody can still reproduce this, please try adjusting the `apz.touch_start_tolerance` pref to be larger and see if that helps. You can also try adjusting the `apz.touch_move_tolerance` pref. If the problem is theory (2) from mcomella's comment above then making one of these two prefs bigger should fix it.

For testing theory (1) you would need to adjust `ui.click_hold_context_menus.delay` and make it smaller (it's the delay in ms that we wait for before firing the long-press).

**Comment by Neutrino999** [comment]
> 
> 
> Looks like the original reporter's account got deleted? At any rate, if anybody can still reproduce this, please try adjusting the `apz.touch_start_tolerance` pref to be larger and see if that helps. You can also try adjusting the `apz.touch_move_tolerance` pref. If the problem is theory (2) from mcomella's comment above then making one of these two prefs bigger should fix it.
> 
> For testing theory (1) you would need to adjust `ui.click_hold_context_menus.delay` and make it smaller (it's the delay in ms that we wait for before firing the long-press).

@staktrace I can reproduce the issue on my device. My device is the same as the OP. I tried adjusting the values in the latest Beta  `80.0.0-beta.6` as in the stable 79.0.4 about:config doesn't seem to be working anymore, I think there could be a bug with it as I always get the error stating '`Cannot Complete Request` try again'. but that apart, changing the values in `about:config` didn't seem to make any difference.  I have set the value of `ui.click_hold_context_menus.delay` to 200ms but it still doesn't feel like it is making any difference. I have also tried adjusting the other values you mentioned but they also seem to be doing nothing.



But they do make a noticeable difference on other websites like`Wikipedia.org`, `getpocket.com`, etc. and in fact they work as expected when those values are changed.


### Some of the websites the long press issue reproducing on even after changing the value of `ui.click_hold_context_menus.delay` to 200ms.

* `https://tachiyomi.org/`
* `https://mobile.twitter.com`
* `https://www.passmark.com`

I could probably give you more but I need time to research.

**Comment by staktrace** [comment]
> about:config doesn't seem to be working anymore

I think it is intentionally disabled in release builds, not sure.

> But they do make a noticeable difference on other websites

Ah that's interesting. So it's site-specific, maybe having to do with touch event listeners on the site itself. I tried on the three websites you listed, and can sort of reproduce, but it would help if we just picked one test case to focus on. For example, on passmark.com, can you identify a specific piece of text on which long-pressing doesn't work well for you? I want to make sure that I can reliably reproduce the same symptoms you are seeing and don't end up looking at a different problem.

**Comment by Neutrino9** [comment]
@staktrace OK, thanks for the response.


### Steps to reproduce 1

1. Visit `https://www.passmark.com`
2. Click `browser all` under `Bench marking & diagnostic Software`
or `BurnInTest` under the image or you can click on `Learn More` 

**See the screenshots, Long press on the highlighted area button/links.**

___

### Steps to reproduce 2


1. On `https://mobile.twitter.com`
2. Try to click on a link or compose a tweet and try to long press on the written text to copy or paste it. 
or on the `mobile.twitter.com` page (without logging in)  click on `Login` and `Sign up` or bottom elemets.
**See the screenshots, Long press on the highlighted area button/links.**


___

### Steps to reproduce 3 

1. On `https://tachiyomi.org/`
2. Long press on  `Download` or `User Guide`
3. Long press the buttons in the side bar.

**See the screenshots, Long press on the highlighted area button/links.**

___

### Steps to reproduce 4

I tried reproducing the scenario as on https://github.com/mozilla-mobile as highlighted in the comment https://github.com/mozilla-mobile/fenix/issues/10618#issuecomment-660081085 and I was able to successfully reproduce the issue on my device too. 

My device is same as the OP. i.e Motorola One Power. And it has the Android OS version Android 10.

___


### Screenshots
![Screenshot_20200820_080400](https://user-images.githubusercontent.com/69946395/90710503-33dbe700-e2bc-11ea-867a-01d8af3220cf.jpg)
![Screenshot_20200820_080435](https://user-images.githubusercontent.com/69946395/90710509-376f6e00-e2bc-11ea-9234-e5cc27095377.jpg)
![Screenshot_20200820_080510](https://user-images.githubusercontent.com/69946395/90710511-38a09b00-e2bc-11ea-90cb-298c2599d062.jpg)

![Screenshot_20200820_080607](https://user-images.githubusercontent.com/69946395/90710526-3dfde580-e2bc-11ea-83dd-b269312eadd1.jpg)
![Screenshot_20200820_080536](https://user-images.githubusercontent.com/69946395/90710523-3b9b8b80-e2bc-11ea-87a0-cef3ecf1812b.jpg)

**Comment by staktrace** [comment]
Thanks. I tried all of those links on all the devices (Sony XPeria XZ1C, Sony Xperia Z3C, and a Pixel2) and in all cases I got the context menu just fine.

I think the next step here to try and figure out what's going on is for somebody who can reproduce the problem to turn on some logging prefs and try to collect the logging. If you're comfortable using a command line and the `adb` tool for android devices then let me know and I can provide instructions accordingly. If you're not comfortable with that I can try to provide instructions that you will write logging to a file and maybe we can pull the file off and analyze it. Let me know!

**Comment by Neutrino9** [comment]
Thanks for responding.


I can use `adb` tool if you provide me clear instructions and just in case if I was unable to do that, give me the second method as well (if it doesn't require much work from your side). 



I'll try to get you the logs in the next 12 hours.

**Comment by staktrace** [comment]
Great! So first go to about:config, and create the following integer prefs:

- `logging.apz.manager` with value `5`
- `logging.apz.controller` with value `5`
- `logging.apz.inputqueue` with value `5`
- `logging.apz.eventstate` with value `5`

This should start causing a whole bunch of logging to show up in the adb logcat output. Then:

- Go to tachiyomi.org, wait for it to load (I'm picking this URL since the page structure seems simpler than passmark.com and seems less likely to have touch listeners and such)
- run `adb logcat -c` to clear the log
- run `adb logcat | tee mylog.txt` to start collecting the log to mylog.txt
- reload the page in the browser (this way I get the logs for stuff that happens during page load)
- long-press on the Download link. Try to avoid doing any other actions (e.g. scrolling) on the page.
- kill the adb logcat process to stop collecting logs
- attach the resulting mylog.txt to this bug

You'll want to reset the logging prefs afterwards, as they can cause the browser to get a bit slower.

**Comment by staktrace** [comment]
If you want to try logging to a file, then you need to create a `logging.config.LOG_FILE` string pref with a filename, probably something like `/sdcard/Downloads/mylog.txt` and also create a `logging.config.sync` boolean pref with the value true. This is in addition to the prefs I listed in the previous comment. Then:

- Go to tachiyomi.org, wait for it to load
- long-press on the Download link. Try to avoid doing any other actions (e.g. scrolling) on the page.
- Exit the browser (swipe it away in the app switcher)
- See if there's a mylog.txt file in your Downloads folder that you can extract using USB mounting or `adb pull /sdcard/Downloads/mylog.txt`
- attach the resulting mylog.txt to this bug

I'm less sure that this method works as I've had trouble with it in the past with logs not buffered and not written to the file.

**Comment by Neutrino9** [comment]
@staktrace 

In first method https://github.com/mozilla-mobile/fenix/issues/10618#issuecomment-677751650 `adb logcat | tee mylog.txt` isn't working and it fails with the error: `'tee' is not recognized as an internal or external command,
operable program or batch file.`  

And when I create the integer prefs that you gave in `about:config` no logs showed up in the `adb`

And the device seems to be connected, I tried running the command `adb devices` and it showed the device and `USB debugging` is enabled in the Android  1`Developer options` and in Firefox `Remote debugging via USB` is also enabled,

Seems like I am doing something wrong here.
___

In the second method https://github.com/mozilla-mobile/fenix/issues/10618#issuecomment-677754897 doesn't work I am not getting any log file named mylog.txt in the Download folder 

in the `about:config` I entered Name: logging.config.LOG_FILE -- String and Enter a string -- to the storage path of Download folder on my device to `/storage/emulated/0/Download/mylog.txt` and I even tried reversing the Name and Enter a string, that also didn't work. 

Am I doing something wrong?

**Comment by mcomella** [comment]
> I reopened https://bugzilla.mozilla.org/show_bug.cgi?id=1652851 and have a general idea of how to fix it.

@staktrace It looks the like upstream bug is closed: is this issue ready to be checked by QA?

**Comment by staktrace** [comment]
> @staktrace It looks the like upstream bug is closed: is this issue ready to be checked by QA?

It's fixed in Gecko, so yes. I'm not sure if the latest Fenix has pulled in a version of Gecko with the fix.

**Comment by mcomella** [comment]
QA: assuming we pull gecko from master in Nightly and we'd have this fix, please verify this is fixed using the STR in the first comment.

**Comment by softvision-miralobontiu** [comment]
Hi all,
Verified as fixed on the latest Nightly build from 9/4 with Samsung Galaxy Tab S6 (Android 9), Samsung Galaxy Tab A6 (Android 5.1.1), and HTC 10 (Android 8).
Takes about 1 second to select some text or link, and paste the copied link or text.

**Comment by Yajo** [comment]
I think that one thing that really makes this process slow is the fact that you must tap, hold, wait, **and then release the finger to grab the handler and drag it to the end or start of the selection**, unlike any other Android app, where you just tap, hold and drag it to the end. Is that the some issue or a separate one?

**Comment by staktrace** [comment]
That sounds like a separate issue. I never actually noticed that before but yeah it does seem like something we can fix. Please file a new issue for that and we can take a look.
