### ISSUE TITLE
[Bug]Tab Tray: Open Tabs media controls aren't displayed

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10740]
## Steps to reproduce
1. Navigate to audiomack.com and play a song
1. Tap the **Tab Tray**
1. Check the audiomack open tab

### Expected behavior
Audiomack's media controls and state should be displayed in the Tab Tray

### Actual behavior
The media controls and state aren't displayed in the Tab Tray

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build #200518 from 5/18

### Notes
► Video
![20200518-170950](https://user-images.githubusercontent.com/51314259/82222966-ad191600-992a-11ea-9294-72bf10160bcf.gif)

**Comment by karlcow** [comment]
Related or duplicate https://github.com/webcompat/web-bugs/issues/52908

**Comment by AndiAJ** [comment]
Reproducible on the latest **Nightly Build 200605 from 6/5** while playing audio on Soundcloud using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

**Comment by topotropic** [comment]
@AndiAJ seems to be fixed, can you verify? Thanks!

**Comment by AndiAJ** [comment]
Hi @topotropic , unfortunately, **it's still reproducible** on the latest **`Nightly Build 200708 from 7/8`** while playing any track on Soundcloud using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200708-141855](https://user-images.githubusercontent.com/51314259/86913035-b18dce00-c126-11ea-986e-831904731e4e.gif)

**Comment by ekager** [comment]
Hm if this is only on soundcloud (and other specific media sites) then this is likely related to https://github.com/mozilla-mobile/fenix/issues/4793 / https://github.com/mozilla-mobile/fenix/issues/7369

**Comment by AndiAJ** [comment]
Reproducible on Beta 80.0.0-beta.4 using a OnePlus A3 (Android 6.0.1) while playing the video from this link https://www.bbc.com/news/world-middle-east-53683082

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on Beta 82.0.0-beta.4 with Samsung Galaxy Tab S6 (Android 10) with rockfm.ro page.

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on the 10/8 Nightly build with soundcloud.com, using Samsung Galaxy Tab S6 (Android 10).

**Comment by rocketsroger** [comment]
With nightly this issue is fixed.  Please verify.   Thanks!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201210`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment]
Still reproducible on Beta 85.0.0-beta.2 using a OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment]
Still reproducible on **`85.1.0-rc.1`** using a OnePlus A3 (Android 6.0.1)

**Comment by softvision-oana-arbuzov** [comment]
This is still an issue. 
Reproduced on URL: https://music.youtube.com/watch?v=pBaae5TXQ40&list=RDAMVMpBaae5TXQ40
 
**Tested with:**
Browser / Version: Firefox Nightly 105.0a1 (🦎 105.0a1-20220731065953) 
Operating System: Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
