### ISSUE TITLE
FNX-11903 ⁃ [Bug] Odd animation on plus sign icon in tab tray when closing tabs

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11044]
## Steps to reproduce
1. Open tab tray
1. Swipe closed some tabs (not sure if it has to be near the bottom of the stack)

### Expected behavior
Smooth animations. 

### Actual behavior
Plus sign icon jumps up and down in response to the close action. 

![recording](https://user-images.githubusercontent.com/152493/83280254-5f12d680-a1a4-11ea-98bc-3f1f7d451f9f.gif)UNITO-UNDERSCORE!20200529!UNITO-UNDERSCORE!114406!

### Device information
* Android device: Moto G XT1031
* Fenix version: latest nightly

**Comment by miDeb** [comment]
I believe the FAB should not animate at all: https://github.com/mozilla-mobile/fenix/issues/11089

**Comment by jonalmeida** [comment]
This should be fixed already. The a-c bug for it was closed via another fix: https://github.com/mozilla-mobile/android-components/issues/7282

**Comment by darkwing** [comment]
I'm still seeing a bit of a weird bounce: 

![Jun-23-2020 16-52-21](https://user-images.githubusercontent.com/46655/85468514-2c28ec00-b572-11ea-82c3-ce306f775e57.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200708 from 7/8`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200708-100624](https://user-images.githubusercontent.com/51314259/86888636-2e0eb580-c103-11ea-9991-e31cdfb5911e.gif)
