### ISSUE TITLE
FNX-12626 ⁃ [Bug] Native crash when opening many tabs rapidly (1 per second)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11653]
## Steps to reproduce
* Connect device to computer
* Open many tabs quickly. I ran: `while true; do adb shell am start -n org.mozilla.fenix.nightly/org.mozilla.fenix.IntentReceiverActivity https://amazon.com; sleep 1; done`

### Expected behavior
No crash, tabs open.

### Actual behavior
App crash. Looking at the logs, I only see native traces and "Crashes" setting confirms it was a native crash. Crash signature is c6ae7e08-82e9-4436-bc82-ac7f3e3c3ab7 (not loaded into crash-stats yet).

### Device information
* Android device: P2
* Fenix version: Nightly 200616

**Comment by kbrosnan** [comment]
That is not a processed crash id. That is the local crash id. A sharable crash ID will end in YYMMDD.

See a similar report in issue #11419

**Comment by Mugurell** [comment]
I think there's another bug with the crash reporter in relate to native crashes.
I'm seeing in logs.
`Submitted crash to Sentry (id=null, url=null)`
and
`E/mozac/MozillaSocorroCra: failed to send report to Socorro`
Will investigate.

**Comment by Mugurell** [comment]
Could not get the same logs.
Using the adb am start loop as suggested by mcomella I can have this reproduced.
A socorro Report for this- https://crash-stats.mozilla.org/report/index/294379c4-9e46-4244-9806-8f7530200617

**Comment by Mugurell** [comment]
Interestingly this doesn't seem to be reproducible onGeckoView Example but I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1646352 there since this seems like something the GV team may be better suited to investigate.

**Comment by AndiAJ** [comment]
Hi, I've just checked this on both **`Nightly 200618 from 6/18`** and **`Beta 5.2.0-beta.2 from 6/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

#### Nightly 200618 from 6/18
• Google Pixel 3a (Android 10) - ✔️ No crash
• Huawei Mate 20 Lite (Android 9) - 💥 Native code crash (No Soccoro link)
• OnePlus A3 (Android 6.0.1) - 💥 Native code crash (No Soccoro link)

#### Beta 5.2.0-beta.2 from 6/16
• Google Pixel 3a (Android 10) - ✔️ No crash
• Huawei Mate 20 Lite (Android 9) - ✔️ No crash
• OnePlus A3 (Android 6.0.1) - ✔️ No crash

Opened more than 100 tabs using this

 <details>
    <summary>Loop</summary>

```
@echo off
goto Loop

:Loop
adb shell am start -n org.mozilla.fenix.nightly/org.mozilla.fenix.IntentReceiverActivity https://amazon.com
goto Loop

```
exit


</details>

**Comment by sv-ohorvath** [comment]
I tried the loop as well on a Nexus 9 (Android 7.1.1) and got an about:blank tab, then a new tab with amazon.com which didn't load, just showed a blank screen. Then the app stopped loading tabs or responding to refreshing and opening new tabs manually. No crash reports were added in about:crashes. Let me know if you need more info, this device is pretty slow FWIW.

**Comment by liuche** [comment]
@AndiAJ thanks for the testing. To get the Socorro links, maybe you need to click the "Report" button in the Fenix crash notification in the system notifications tray? Give that a try in the future, hopefully we can get Socorro and Sentry links from about:crashes (which will help us differentiate them).

**Comment by AndiAJ** [comment]
Hi @liuche, clicking the "Report" button in the Fenix crash notification **doesn't do the trick**, mentioned this in [#11419](https://github.com/mozilla-mobile/fenix/issues/11419#issuecomment-645187468)

As @Mugurell mentioned above
Sentry (id=null, url=null)
and
E/mozac/MozillaSocorroCra: failed to send report to Socorro

I've re-tested this issue, tapped the notification but yet again, no Soccoro link

► Video
![20200619-123115](https://user-images.githubusercontent.com/51314259/85118808-7edc6e00-b229-11ea-8a3b-37e8c48c8561.gif)

**Comment by Mugurell** [comment]
This should probably be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1644561.
Not sure about the prevalence of the issue on Fenix but with seeing this in the "Potential Release Blockers" column, maybe after verifying it as fixed in the next Nightlyes we could push for an uplift in both GV and Fenix Release.

**Comment by sv-ohorvath** [comment]
I got this similar crash in one of the automated tests: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6411311184354138254/executions/bs.c1ebb5c4598f8ece/testcases/1/logs
The steps are: 
Open 3 dot menu from the homescreen.
Go to Settings.
Go back to homescreen.
Open 3 dot menu, open the Help link.
On the Help tab, tap the tab counter.

Not sure if it's the same crash but looks similar to this bug or https://github.com/mozilla-mobile/fenix/issues/5478
From the logs:
`06-22 23:58:50.543: D/GeckoSession(7710): handleMessage GeckoView:PageStart uri=about:blank
`

`--------- beginning of crash
06-22 23:59:43.778: E/AndroidRuntime(7710): FATAL EXCEPTION: FinalizerWatchdogDaemon
06-22 23:59:43.778: E/AndroidRuntime(7710): Process: org.mozilla.fenix.debug, PID: 7710
06-22 23:59:43.778: E/AndroidRuntime(7710): java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
`

**Comment by AndiAJ** [comment]
Still reproducible on the latest **`Nightly Build 200624 from 6/24`** using the following devices:
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

**Comment by liuche** [comment]
This just landed today, so it should be in the nightly on 6/26. This won't make 78.0.0 but should be fixed in 79.0.0

**Comment by AndiAJ** [comment]
Hi, I've just checked this on both **`Nightly Build 200629 from 6/30`** and **`Fenix 79.0.1-beta.1 from 6/30`** using the following devices:
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

**I've ran the loop 3x on each device and build**

► **Nightly Build 200629 from 6/30**
Huawei Mate 20 Lite (Android 9) ✔️ No crash
OnePlus A3 (Android 6.0.1) 💥 Crashed 2 out of 3 times, native code crash (No Soccoro link)

► **Fenix 79.0.1-beta.1 from 6/30**
Huawei Mate 20 Lite (Android 9) ✔️ No crash
OnePlus A3 (Android 6.0.1) ✔️ No crash

@liuche - Please review and advise

**Comment by kbrosnan** [comment]
This looks to be fixed then. Thanks for testing @AndiAJ
