### ISSUE TITLE
[Bug] [L10n]The translation in other languages for Collection's description is not present

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#11731]
## Prerequisites
* Have device's language set to russian.
    1. Steps to reproduce

1. Open app and observe the homescreen under top sites.
    1. Expected behavior
The collections description is translated.
    1. Actual behavior
The collections description is not translated.
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Beta 5.2.0-beta.2 and Nightly 6/18

Screen
![20200618](https://user-images.githubusercontent.com/49859863/85023111-f86a5280-b17c-11ea-8b64-619d1546d5cb.jpg)UNITO-UNDERSCORE!154449!

Note: It can also encounter with Japanese

**Comment by liuche** [comment]
This is a new string, so it should get fixed by an l10n update soon!

**Comment by Diana-Rus** [comment]
Hello, this is not yet fixed for:
- Arabic
- Estonian
- Gaeilge (Irish)
verified on Beta 80.0.0-beta.1 and Nightly 7/30with Samsung Galaxy S9 (Android 8)

<details closed><summary>Verified Languages</summary>

- Russian
![Screenshot_20200730-223243_Firefox Beta](https://user-images.githubusercontent.com/49859863/88966453-03082380-d2b5-11ea-954e-37d31ed48a2b.jpg)
- German
- French
- Japanese
- Chinese (traditional)
- Spanish
- Bosnian
- Dansk
- Portuguese
- Polski
</details>
