### ISSUE TITLE
FNX2-15112 ⁃ [Bug] Report site issue is missing from Add-ons sub menu

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#12248]
Pre-requisites:

* Have Firefox Nightly installed from playstore.
  1. Steps to reproduce

1. Open app and go to Add-ons.
1. From Add-ons enable one of them - I used uBlock Origin.
1. Make a search after a domain.
1. Tap on the Menu/Add-ons.
    1. Expected behavior
"Report site issue" is present either in Add-on submenu or in the main menu https://bugzilla.mozilla.org/show_bug.cgi?id=1643144 .
    1. Actual behavior
"Reports site issue" is missing from the Add-ons submenu.
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8), Motorola Moto G6 (Android 8)
* Fenix version: Nightly 7/3 and Release migration build 1, from 7/3 

Screen
![Screenshot](https://user-images.githubusercontent.com/49859863/86476562-73bc2e80-bd4f-11ea-84f3-f010bdf0fe99.jpg)UNITO-UNDERSCORE!20200703-170008!UNITO-UNDERSCORE!Firefox Nightly!

**Comment by ebalazs-sv** [comment]
This is still reproducible on Nightly Build #21980629 GV 80.0a1 from 7/16 with Motorola Moto G6 (Android 8).

**Comment by csadilek** [comment]
Fix landed on master. This should be fine again in next Nightly.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/17.
Devices: Samsung Galaxy Note10(Android 10), LG G7 FIT (Android 8).

**Comment by softvision-miralobontiu** [comment]
This is still reproducible on the 79.0.2 RC build from 8/1 with Samsung Galaxy Tab S6 (Android 9).
