### ISSUE TITLE
FNX-4957 ⁃ [Bug] Crash playing youtube videos

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1322]
## Steps to reproduce
1. go to youtube and play a video.
    1. Expected behavior
Video plays.
    1. Actual behavior
Fenix stops working.
    1. Device information

* Android device: Note 8 (Android 9), Nexus 9 (Android 6.0.1)
* Fenix version: 4/2 build

**Comment by cpeterso** [comment]
@boek reproduced this crash and says it looks like a GV tab crash. I filed a new GV bug for this crash: https://bugzilla.mozilla.org/show_bug.cgi?id=1541128

**Comment by vesta0** [comment]
@cpeterso will this bug be fixed in time for the beta?

**Comment by cpeterso** [comment]
@sv-ohorvath Can you still reproduce this YouTube crash? YouTube doesn't crash for me with the latest Fenix Build 4/11) on my Moto G5 running Android 8.1. Maybe this was a bug in GV 67 that has since been fixed in GV 68.

**Comment by dbolter** [comment]
I can't repro on pixel2

**Comment by sv-ohorvath** [comment]
Doesn't reproduce on Pixel (Android 9), HTC Desire 820 (Android 6.0.1), Galaxy S8 (Android 9).
build: 4/11
