### ISSUE TITLE
FNX-5032 ⁃ [Bug] search shortcuts not correctly aligned in the middle

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1442]
### Steps to reproduce
1. open search shortcuts

### Expected behavior
correct vertical alignment

### Actual behavior
no correct vertival alignment, text has to be moved a bit to bottom

![Screenshot](https://user-images.githubusercontent.com/1100614/55670725-3c2eb000-5888-11e9-8db3-0790851a0cbf.png)UNITO-UNDERSCORE!20190406-151246!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision d43e902b4433348da285a2978918ccfefc389014

**Comment by cadeyrn** [comment]
Compared to the original report it looks even worse with a current build:

![Screenshot_20190610-213657](https://user-images.githubusercontent.com/1100614/59221606-fc59b100-8bc7-11e9-8f9a-25a0e7e57c1f.png)

**Comment by lime124** [comment]
I'm not sure what is needed from the UX team. I agree with the reporter and it should be vertically aligned with the icon.

Removing ux label - please re-add and add comments as to what my team needs to provide. Thanks!

**Comment by rocketsroger** [comment]
Looks like the text inside the toolbar is vertically scroll-able.  Something with child size is not right here.

**Comment by rocketsroger** [comment]
Confirmed on latest master build that this is fixed.

**Comment by cadeyrn** [comment]
> Confirmed on latest master build that this is fixed.

While it's definitively better for the search engine icons (still not perfectly aligned but it looks better now) the misalignment of the settings icon is still noticeable in my opinion.

**Comment by lime124** [comment]
@cadeyrn could you file a follow  up issue for the settings alignment? i find it odd that didn't get fixed along with the search icons, but that was the intent. there will have to do some investigation and figure out why it's not happening. thanks!
