### ISSUE TITLE
[Bug] duckduckgo - title is not visible

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#14432]
## Steps to reproduc
On duckduckgo:
1. Search "test 1"
2. Search "test 2" 
3. Open tab tray
### Expected behavior
The title is: "test 1 - Duckduckgo" or test 2… so that we can distinguish both
### Actual behavior
Both are https://duckduckgo.com/?q=… , I can't distinguish them
<img src="https://i.ibb.co/X48cdX3/Screenshot-20200829-132248-Firefox-Nightly.png" width="300">
### Device information

* Android device: Pocophone F1
* Fenix version: Nightly 200829 06:05

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5898)

**Comment by B0pol** [comment]
I think it is depends on #10916
If you watch url bar closely, you first see duckduckgo.com/?q=test%201&t=fpas, then it becomes duckduckgo.com/?q=test+1&t=fpas via a redirection. %20 is space when you encode url.

**Comment by ekager** [comment]
Possibly related to https://github.com/mozilla-mobile/android-components/issues/8315

**Comment by jonalmeida** [comment]
This should be fixed now, but leaving it for the OP to close.

**Comment by B0pol** [comment]
It's not fixed, we can see the title for a very short amount of time but after the redirection %20 (space encoded) to + as word separator, I don't see the url in the tab tray, but the full url. Version Nightly 200917 06:07

**Comment by jonalmeida** [comment]
You're right! I wonder why all the other issues are no longer reproducible except for this one..

**Comment by mobd** [comment]
I get this same issue on lots of sites, though not reliably. It doesn't need to have anything to do with redirects in my experience
![Screenshot_20201101_064526_org mozilla fenix](https://user-images.githubusercontent.com/66154603/97796132-b4995680-1c0e-11eb-90e1-b6720282b619.jpg)

**Comment by mobd** [comment]
I still have this issue on many sites, not specifically duckduckgo. Tabs won't have a title and just display the url until you reload the page

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1766676

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1766677

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
I reopened the Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1766676 now that we track AC bugs in Bugzilla.

Does this bug also affect Focus tabs?
