### ISSUE TITLE
[Bug]The Wikipedia default top site doesn't work on OnePlus A3 (Android 6)

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#14610]
## Steps to reproduce
1. Tap and open the Wikipedia default Top Site
2. Open the Tabs Tray

### Expected behavior
Wikipedia is properly opened and displayed in the Tabs Tray

### Actual behavior
Secure connection Failed error page
fx-fenix_errror_5 is displayed in the Tabs Tray

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Nightly 200902
• Beta 81.1.0-beta.1

### Notes
❗ Not reproducible with the following devices:
• Google Pixel 3a (Android 10)
• Google Pixel 3XL (Android 9)
• Samsung Galaxy Tab S3 (Android 8)

❗ Similar issue: #14517 

► Video
![20201012-132215](https://user-images.githubusercontent.com/51314259/91969917-89ce7700-ed1f-11ea-82da-c27748694e7d.gif)

**Comment by Diana-Rus** [comment]
Related to mozilla-mobile/android-components#8315

**Comment by jonalmeida** [comment]
This should be fixed now and was verified in https://github.com/mozilla-mobile/fenix/issues/14620.

**Comment by AndiAJ** [comment]
Still reproducible on the latest Nightly build 200917 using a OnePlus A3 (Android 6.0.1)
