### ISSUE TITLE
[Bug] Autofill from Keepass2Android not working consistently

### ISSUE THREAD

**Issue by bluezed** [mozilla-mobile/fenix#14633]
## Steps to reproduce
Open any website that requires Login and tap into the Username field.

### Expected behavior
The Autofill dialog from Keepass2Android should come up allowing to autofill the Username. That's how it used to work in previous versions and still works like this in Fennec F-Droid.

### Actual behavior
No dialog appears or it just flashes up quickly and then disappears again before a selection can be made.

### Device information

* Android device: Xiaomi Mi Note 10 Lite, Android 10
* Fenix version: 80.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6206)

**Comment by philipreimer** [comment]
Same here.

It mostly happens if I switch to some other tab or app while the page with the login form is still loading.
When I return to the page with the login form, it is not possible to access the autofill dialog.

Sometimes it helps to reload the page.

**Comment by sophiekuehn** [comment]
Doesn't opens up at all for me. Not even inconsistently. Android 8 Oreo.

**Comment by philipreimer** [comment]
Still happening in Firefox 81,1,1 (Build #2015764547)

**Comment by sagebind** [comment]
Same for me, I can't even get autofill from Keepass2Android to show up at all on any website, even on nightly. I'm on Android 8.

Note that even in previous versions of Firefox Keepass2Android was a bit finicky for me on some websites, but I could always get it to work by long-pressing a field and clicking "AUTOFILL" in the context menu to manually trigger Keepass2Android, but it seems that menu option doesn't exist any more in Firefox for some reason.

**Comment by philipreimer** [comment]
@sagebind Sometimes it helps to reload the page. Sometimes it helps to switch to the Keepass2Android keyboard and that will trigger the Autofill popup. Sometimes it's just not working at all.

**Comment by sophiekuehn** [comment]
@philipreimer Not true it seams for Android 8 Oreo. There is no working workaround in that version.

**Comment by philipreimer** [comment]
@sophiekuehn Sorry, I forgot to mention that I am using Android 10.

**Comment by bluezed** [comment]
Just got the update to v81.1.2 and still have the same problem ☹️

**Comment by Ythan** [comment]
Android 10 with KeePassDX and Firefox 82.0b4 here. This is a very frustrating problem. Sometimes, it can be made to work just by tapping at the elements repeatedly, eg:

https://mind-media.com/Screen_Recording_20201007-150643_Firefox%20Beta.mp4

When that doesn't help, a consistent workaround for me is to switch to a different app and then back to Firefox, eg:

https://mind-media.com/Screen_Recording_20201007-151604_Firefox%20Beta.mp4

You can also observe two other minor bugs in the videos above. In the first video, the offset for the autofill dialog is incorrect. In the second video, the entire page is highlighted after autofilling the password.

I hope there is a proper fix soon.

**Comment by Taknok** [comment]
Issue also present on 81.1.4 with android 10 on Oneplus 7 OOS 10.0.7.
This seems to be a element focus issue, the pop up close when the keyboard open (on chrome the popup did not close at keyboard opening).
In the GIF below the popup did not open at 1st click. Then it blink until luck.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12498020/96180325-8e976500-0f32-11eb-984a-61de33be4724.gif)

**Comment by Gael-Mifsud** [comment]
Hello,

I use a LG G6 with Android 10.
So far, the autofill with keepass2android with Firefox fenix has been successful only one time : with github I wanted to log in to rant in this thread.

It seems as if it wants to troll me. 😵

I hope you or the kp2a team will solve this bug.

**Comment by skoobasteeve** [comment]
Same here, OnePlus 6 with Android 10 running Firefox Beta 84.0.0 beta2

Been happening for the last few versions. Sometimes I can get the autofill menu to stay open if I switch back and forth from another tab, but otherwise it just flashes and goes away. Would be okay if I could long press and manually select autofill but it appears this isn't an option.

Happy to test a nightly when a fix is available.

**Comment by grrosminet** [comment]
Same here on Samsung galaxy s10, Android 10

**Comment by philipreimer** [comment]
The situation actually has become worse.
With Firefox 84.1.2 on Android 10 (Nokia 8.1) Autofill from Keepass2Android does not work at all anymore.

Even if I get the autofill menu to appear at some point no login data gets filled into the login form.

**Comment by ptar** [comment]
Almost th same to me with 84.1.2 on Android 10 (LG V40): E.g. the github login took me some tipping between username and password fields, until the autofill constantly appears. Then selecting the credentials and when coming back, a reload and some luck with the next 5 or 10 focus switches between username and password to get a "sticky" autofill dialogue.
When I checked a login page with Chrome in comparison, the autofill options appear and stay as it did in Firefox some time ago.
Please fix this! Thanks!

**Comment by montilo** [comment]
This bug is so annoying... I hoped there will be a bugfix soon, but after months i will probably switch my Default browser :-(

**Comment by Jean85** [comment]
FTR, this was originally reported as https://github.com/PhilippC/keepass2android/issues/1399, so it's still hitting us after 4 months (and many major versions).

Anyone can at least let us know if this is addressable by the devs?

**Comment by hokonch** [comment]
The same bug was also reported in KeePassDX, another KeePass client, and the developer did some workaround. KeePassDX autofill works fine on Firefox now except for a minor issue.
https://github.com/Kunzisoft/KeePassDX/issues/725
I suspect that this bug is caused by Firefox, but the developer of Keepass2Android may be able to do the same workaround.

**Comment by sophiekuehn** [comment]
@hokonch The workaround sadly is not helping on Android 8.0 devices, where the autofill popup still is not appearing at all.

**Comment by t-o-o-m** [comment]
Compared Firefox (84.1.4), Firefox Nightly (210109 17:00) and Chrome (87.0.4280.141) with both, Keepass2Android & LastPass. 

| | Firefox  | Firefox Nightly | Chrome |
| ------------- |------------- | ------------- | ------------- |
| **Keepass2Android** | short popup | popup but click doesn't fill password | works | 
| **LastPass** | nothing happens | nothing happens | works |

As much as I love Firefox and the idea behind it this is the first time I'm actually considering switching to a different browser. I'm using a password manager for a reason!
### Keepass2Android
![Keepass2Android](https://user-images.githubusercontent.com/29979066/104132866-4694ac80-5380-11eb-847f-b0537c1c3ccc.gif)

### LastPass
![LastPass](https://user-images.githubusercontent.com/29979066/104132865-45637f80-5380-11eb-94e7-514a2932cbcd.gif)

**Comment by roedel1** [comment]
I can also confirm and reproduce the behaviour. 

Device: Sony Xperia XZ2 Compact
OS: Android 10 (Stock) 52.1.A.3.49
Mozilla Firefox: 84.1.4 (Firefox Daylight Channel from Google Play)
KeePass2Android: 1.08d-r1

Behaviour is inconsistent but has definitely gotten better with KP2A-Upgrade to 1.08d-r1. I'll be happy to share device log data if it's helpful in tackling the issue. 

Thank you for being here and working on the issue! 
Stephan

**Comment by philipreimer** [comment]
As Firefox is broken now for over 4 months it would be nice to finally get some feedback from the Firefox devs if they are even aware of this issue and plan to fix this at some point.

Keepass2Android is not even mentioned yet in #9773.

Seems to be unfair to developers of Keepass2Android, who now get all the heat from disappointed users, and have to implement unnecessary workarounds just because Firefox broke the Autofill support.

**Comment by Offerel** [comment]
@philipreimer that's so true. I completely agree with this. It's quite frustrating how many bugs are currently open in Firefox Android without a fix. Even long-time users like me are switching to alternative browsers because there is hardly any other option. It's all more than just unpleasant.

**Comment by skoobasteeve** [comment]
This has been fixed for me in Firefox Nightly. Oneplus 6 on Android 10.

Can anyone else confirm?

**Comment by ptar** [comment]
Thanks for the tip!
Yes, it's much better (nightly 210111 17:02 #2015786763 compared to 84.1.4), but still not working correctly: The flickering/"disappearing" of the dialogue seems to be gone, but the dialogue still does re-appear automatically after choosing the credentials in Keepass2Android  (neither were the chosen credentials automatically inserted). Reload helped in my case, but I know, that's not always possible with all login screens.
At least, using Keepass2Android with Firefox is usable again.

**Comment by Gael-Mifsud** [comment]
I know you're "only" a user like me, but, per chance, do you know when - more or less - this "nightly" will become "official" ? :-D
I have installed the playstore version of Firefox.
Thank you.

**Comment by Offerel** [comment]
@Gael-Mifsud to my knowledge, this behavior is only a workaround created in Keepass2Android 1.08d-r2 (in beta channel from yesterday). I have not seen a change from Mozilla side.

**Comment by ptar** [comment]
@Gael-Mifsud The Firefox Nightly is available in the PlayStore, see https://play.google.com/store/apps/details?id=org.mozilla.fenix
I tried both Nightly and Firefox release version with the release version of Keepass2Android (1.08c-r1) side by side with two login pages where I had encountered problems. One of the pages is is the github-login-page.
Please try yourself!

**Comment by philipreimer** [comment]
@ptar @Offerel using FF Nightly 210111 17:02 (Build #2015786763) with Keepass2Android 1.08c-r1 the problem of a disappearing Autofill dialogue seems to be fixed indeed. The dialogue appeared and stayed visible. Some pages I tested: github, twitter, gmail

But login data is still not entered into the login field after selecting credentials from Keepass2Android.

So Autofill is still broken from my point of view.

**Comment by grrosminet** [comment]
The developper of keepass2android has published a BETA release with a workaround for Firefox and Chrome.
https://github.com/PhilippC/keepass2android/issues/1399

**Comment by Gael-Mifsud** [comment]
Thank you, @ptar, I installed the Nightly version of Firefox.

Now I see what @philipreimer said 2 days ago : with Firefox Nightly, the autofill dialog appears (YES !) but nothing is filled in the login fields (OUCH !).
With Firefox, the autofill dialog doesn't appear at all.

Still broken, then.
But I don't have tested the K2PA beta spoken by grrosminet, so there is still hope.  ^_^

**Comment by Djfe** [comment]
#10640 is the same bug happening with enpass's autofill
It's fully fixed in Nightly

**Comment by montilo** [comment]
Not on my devices. The autofill Pop-up is showing up correctly, but the credentials are not filled out. It is only working if I refresh the page and do it a sedond time again.

**Comment by Djfe** [comment]
I'm sorry, I only wanted to highlight that this is not a specific bug and it's happening to all autofill inputs from password managers.

It's annoying enough that it will only be fixed by mid February (Firefox 86) if it won't be uplifted. It's been annoying us for months :/

Anyways just because the flickering also happens in enpass, doesn't mean that there aren't further bugs in Firefox concerning keypass. hopefully they will fix these, too :)

**Comment by montilo** [comment]
I am testing it every nightly release hoping that I can change my default browser back to my favorite browser. Is there anything we can do to make these bug more visible after 5 month?

**Comment by workingmachine** [comment]
I also notice that very annoying behavior.
Samsung Galaxy S21 Ultra 5G with Android 11 and Firefox from playstore.
Autofill dialog sometimes appears for 100 milliseconds and then disappears.
After 1,5 hour testing with some web logins, no chance to get it useful working. 
I hope mozilla will fix the bug this month, otherwise I have to change my default browser to chrome.

**Comment by workingmachine** [comment]
Now I have tested with Firefox 85.1.3 from playstore and keepass2android 1-08d-r5 (test version) and it works.
I seems that currently official releases of keepass2android are also responsible for that behavior.

**Comment by philipreimer** [comment]
I am using the same combination (FF 85.1.3 and k2a 1-08d-r5 - both the latest versions from play store) and it is still not working reliably.
Still getting the flickering / disappearing popup on most login pages.
Still login information is not filled in after selecting from k2a (especially if there are multiple logins available).

**Comment by Derkades** [comment]
It is fixed for me with latest KP2A and latest Firefox stable or nightly (all from Play Store)

**Comment by sagebind** [comment]
For me it still does not work at all. Firefox 85.1.3, Keepass2Android 1.08d-r5, Android 8.

**Comment by bluezed** [comment]
For me it still does not work reliably either. It's a litte better than it was but still frustrating that 9 times out of 10 the autofill dialog either doesn't pop up or when it does the fill does not work. Firefox 85.1.3, Keepass2Android 1.08d-r5, Android 11.

**Comment by workingmachine** [comment]
Because of the last comments I have tested once again.
I have installed Firefox 85.1.3 from playstore.
Keepass2Android version 1.08d-r5 is not from palystore, I have found it with google search.
At many login sites the Autofill dialog appears immediately after loading.
When I touch beside the Autofill dialog it disappears.
When touching the user or password field the Autofill dilaog flickering.
After next touching at the user or password field the Autofill dialog appears.
At amazon login the Autofill dialog does not appears, I have to touch beside the login credential field and than to the user field two or three times and then the Autofill dialog appears.

It does not work perfectly, but in most case I can use the Autofill dialog.

**Comment by sagebind** [comment]
(1.08d-r5 is the latest version on the Play Store only if you opt in to beta testing, as I have.) 

@workingmachine What version of Android have you used in your test?

**Comment by sagebind** [comment]
For what it is worth, I should mention that on some sites I do get the Keepass2Android notification for the site on load, if Keepass2Android is already running, but there's no offer to auto fill the credentials. I have to copy and paste the username and password manually using the notification. So somehow Kepass2Android is at least being informed of the current URL, but there's still no autofill. 

This is an improvement since the issue was initially opened, when not even the notification would show up (perhaps a Kepass2Android change?), but still much worse than the pre-Fenix experience.

**Comment by workingmachine** [comment]
Sorry for the mismatch.
Now I have checked in the play store and it is the last official version (1.08d-r5).
In the last I used “Keepass2Android Offline” version, which is behind from Keepass2Android.
The version of android is 11, Samsung Galaxy S21 Ultra.

**Comment by sagebind** [comment]
I'm on Android 8 which may be pertinent. Is autofill just not expected to work on Android 8 any more? Having to get a new phone just for this would be a bummer; it bothers me how disposable many people treat their devices these days.

**Comment by Djfe** [comment]
nope this concerns all password managers (autofill apps) on all Android versions
I'm using enpass on Android 10 and I'm experiencing something very similar (bug is linked in a post above this)

**Comment by flowercow** [comment]
this bug has been fixed in firefox nightly, but not in ff 86.1.0-rc1.

**Comment by philipreimer** [comment]
So it seems that the fix did not make it from FF nightly into the 86.1.1 release?
The behaviour has improved with 86.1.1 but it's still broken when you have multiple tabs open and switch between them.

A simple scenario:

1. Open [www.heise.de/sso/login](www.heise.de/sso/login)
2. Open a second tab
3. Open [github.com/login](github.com/login) in second tab
4. Switch back to first tab (heise)
5. Switch to second tab (github) again

Most of the times the autofill popup does not appear in steps 4 and 5. Sometimes alternately tapping on login and password fields a few times will make the popup appear. Sometimes reloading the page will help. Of course, reload does not help for some pages if you got redirected to the login or it is some kind of modal window, etc. You then restart the whole login process again.

Firefox 86.1.1 (Build #2015794883)
K2A 1.08d-r5
Android 10
Nokia 8.1

**Comment by Djfe** [comment]
My guess by now is, that this is caused during the build of beta and release.
So it cannot be fixed in Nightly since it's not happening there.

**Comment by tinsukE** [comment]
On 87.0.0-rc.1 and this still is happening.

It'dbe very scary if really caused by the beta and release build processes.

**Comment by allisonkarlitskaya** [comment]
My 2¢: Lastpass and Bitwarden both seem to be impacted here.

Chrome works consistently
Firefox Klar works consistently
Nightly works, mostly (but stops working if you click around too much)
87, and beta seem broken

Despite what the summary of this bug suggests, it's very much not limited to Keepass

**Comment by philipreimer** [comment]
Still not fixed in 88.1.3 (Build #2015808507).

Android 11
Nokia 8.1

**Comment by freaktechnik** [comment]
What I'm seeing is that Bitwarden will show up logged out, I log in and select the item to autofill and then the stuff isn't filled. After that it no longer shows up, unless the page is reloaded/the form is re-created. I can then use the logged-in state autofill popup to successfully auto fill.

**Comment by kaysond** [comment]
Still not working as of 90.1.3 Build #2015824995

**Comment by sagebind** [comment]
I've since replaced my previous phone, which ran Android 8, with a new phone running Android 11. Here autofill with Keepass2Android works _most_ of the time, though on some pages the autofill popup quickly disappears randomly and tapping the input fields (defocusing between taps) a few times will typically cause the popup to come back. It is definitely useable, but still doesn't work as well as it did in Fennec.

This is different from when I was running Android 8, under which the autofill _never_ worked with Keepass2Android.

**Comment by Derkades** [comment]
I share the same experience on Android 11 where autofill works most of the time but disappears quickly sometimes. Tapping a different area then selecting the field again makes it appear.

**Comment by thevoiceless** [comment]
Confirming what others have reported:

* The autofill dropdown appears for a split second before disappearing on stable `91.4.0` and beta `92.0.0-beta.8`. No luck with the workarounds that some have mentioned (tapping repeatedly, moving focus to the URL bar and back, etc).
* The autofill dropdown appears as expected (correct position, does not disappear, etc) on nightly `93.0a1` and all previous nightlies for the past ~week. Tapping on it does launch Keepass2Android, but the selected entry is not populated when returning to Firefox.

Info:

* Keepass2Android Offline `1.08c-r1` from Play Store
* Android 11
* Samsung Galaxy s10e + OneUI 3.1

Tagging related issues:
https://github.com/mozilla-mobile/fenix/issues/9773
https://github.com/mozilla-mobile/fenix/issues/19981

**Comment by Djfe** [comment]
the workaround is to switch between user and password fields until it stops flickering and stays visible.

**Comment by workingmachine** [comment]
I use
- Keepass2Android 1.08d-r5, not offline version, but with this version you can also work complete offline
- Android 11
- Samsung Galaxy S21 Ultra
This version is newer than the online version and has some improvements to work better with firefox.

**Comment by kaysond** [comment]
This update to Bitwarden fixed one of the main issues for me! The autofill popup now shows up consistently and doesn't flash.

It did not, however, fix the issue where signing into the vault and then immediately choosing an entry does not populate the form fields. (It works if you're already signed in)

https://github.com/bitwarden/mobile/pull/1592

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1364456

**Comment by Gael-Mifsud** [comment]
Device: LG G6
OS: Android 9 (Stock)
Mozilla Firefox: 95.2.0 (Firefox Daylight Channel from Google Play)
KeePass2Android: Last official version from googleplay

I wanted to let you know that, with the fewwebsites I use, it works now.
Sometimes flawlessly, sometimes I have to click the password field. But nevertheless, now it shows and it autofills the fields.
I didn't try for a while, so it may be fixed from last 29 November, as noted in the changelog.

Good job and thank you very much !

**Comment by delia-pop** [comment]
I was not able to reproduce this issue on the latest Nightly from 05/19 or GVE with Google Pixel 6 (Android 12).
On both apps, with KeePass2Android set as default autofill app and a login for Facebook saved, the autofill works as expected.

The current flow is as follows:

1. Tap on the username/password fields.
2 a. Tap on the "Fill with KeePass2Android" option above the keyboard > the user is taken to KeePass2Android and can select desired saved login > the user is returned on the page in step 1 > the selected saved login is now available near the username/password fields and if selected, the data is correctly imported.
2 b. Select the saved login displayed above the keyboard > the data is correctly imported.

**Comment by Djfe** [comment]
that's because the biggest part of this bug and other password manager bugs on Android was never reproducible in Nightly. only in beta and release. This has been the case for years now.
don't ask me why but test release and then compare it to the nightly with the same version number: the Nightly doesn't have the issue but Release does. sadly

Also this only affects the new Android autofill API. legacy methods using an accessibility function work reliably. but they have access to anything I type :/

**Comment by Djfe** [comment]
it's actually a great idea to compare fdroid and play store builds. I'll do that. Thanks for the idea.

**Comment by delia-pop** [comment]
Hi, @Djfe, thank you for your input and contribution in testing this. 
I tested and confirmed that this is no longer an issue on the latest Nightly 102.0a1 because a change in autofill in GeckoView landed in this version. Therefore, upcoming Betas and Release 102 should also have this issue fixed. We will continue to verify this once the said builds are available. :)

**Comment by Djfe** [comment]
great news!

**Comment by kaysond** [comment]
Seems resolved to me! Using bitwarden on FF 102.2.0 on a galaxy s22 with android 12

**Comment by allisonkarlitskaya** [comment]
I think this is less `wontfix` and more `alreadyfixed`. :)

**Comment by gbakeman** [comment]
I wanted to add since I've been experiencing this issue - when the changes came down to the Fennec build on F-Droid, my autofilling became... Different, but not necessarily better? The autofill prompt sometimes shows and works correctly, sometimes not at all. But now, sometimes it only shows on the password field, and skips filling the username field.

Not sure if this is a new bug...?

**Comment by makotokato** [comment]
@gbakeman
If you say that this occurs on F-Droid only and this is https://github.com/PhilippC/keepass2android/issues/1808, we should fix keepass2android since F-Droid package name is different of Firefox. I don't know about version number rule (`maxLongVersionCode`) of F-Droid, we should ask F-Droid team.

**Comment by gbakeman** [comment]
> @gbakeman If you say that this occurs on F-Droid only and this is [PhilippC/keepass2android#1808](https://github.com/PhilippC/keepass2android/issues/1808), It should fix keepass2android since F-Droid package name is different of Firefox. I don't know about version number rule (`maxLongVersionCode`) of F-Droid, you should ask F-Droid team.

Sorry, I didn't mean to imply to that this was an F-Droid-only issue. Just that that's how I normally receive updates. Although before hand my issue seemed to fall in line with the others, although I'm not sure how this password-only filling issue came about other than as a result of the recent update that did atleast improve some detection.

**Comment by boek** [comment]
This appears to have been fixed. If there is a new bug you're experiencing please file a new issue with steps to reproduce

**Comment by kaysond** [comment]
Many thanks to the team for resolving this horribly annoying issue!
