### ISSUE TITLE
Deeplinks not working from FireFox Android

### ISSUE THREAD

**Issue by rkops-bd** [mozilla-mobile/fenix#14977]
## Steps to reproduce
Navigate to https://mijn.digid.nl, select 'op dit apparaat', AppStore will be opend instead of DigiD or https://app.digid.nl
### Expected behavior
DigiD App should be opened if installed, or navigate to https://app.digid.nl
### Actual behavior
AppStore will be openened
### Device information
Huawei Nexus 6P
* Android device: ?
* Fenix version: ?

**Comment by thomond** [comment]
Hi,

I tested this on Firefox Beta on the Play Store and App launched so it seems fixed now.

**Comment by ekager** [comment]
@rkops-bd can you still reproduce this? Going to close for now
