### ISSUE TITLE
[Bug] suggested logins android phone crash 

### ISSUE THREAD

**Issue by Iiz-vas** [mozilla-mobile/fenix#15383]
## Steps to reproduce
Open Firefox 
Go to page needing login 
Select Suggested logins menu
Select saved credentials from list

### Expected behavior
Form autocompletes and log in successful

### Actual behavior
Phone crash and quickly restarts 

### Device information
Build number 
Oneplus a5010_43_200224
Oxygen os 9.0.11
Android 9

* Android device: oneplus a5010
* Fenix version: ?

**Comment by ekager** [comment]
Could you provide info about the site that it's happening on if you're comfortable with that? Or is it every site? When you go to about:crashes do you see anything there?

**Comment by Iiz-vas** [comment]
https://staffmail.brighton.ac.uk/my.policy

**Comment by kbrosnan** [comment]
We would need a logcat to understand what is going on. https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information

Ideally using our [Nightly build](https://play.google.com/store/apps/details?id=org.mozilla.fenix)

**Comment by Iiz-vas** [comment]
https://staffmail.brighton.ac.uk/my.policy

When the phone crashes the screen just goes black for a second and restarts.

**Comment by s-ankur** [comment]
I am not 100% sure if it is related but I had this crash while the site was open
```
6269a6dd-4375-4569-a1e0-23576a4a8d74
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=0dbc61a012a649af813965b85edd120f
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-0cfcc827-a6c3-4d9b-9291-952df0200925
----
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8038)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1279)
	at android.view.View.requestLayout(View.java:23120)
	at android.view.View.requestLayout(View.java:23120)
	at android.view.View.requestLayout(View.java:23120)
	at android.view.View.requestLayout(View.java:23120)
	at android.view.View.requestLayout(View.java:23120)
	at android.view.View.requestLayout(View.java:23120)
	at android.view.View.requestLayout(View.java:23120)
	at android.view.View.requestLayout(View.java:23120)
	at android.view.View.requestLayout(View.java:23120)
	at android.view.View.requestLayout(View.java:23120)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.triggerUpdateProcessor(RecyclerView.java:4)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:3)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:3)
	at androidx.preference.PreferenceGroupAdapter.onPreferenceChange(PreferenceGroupAdapter.java:2)
	at androidx.preference.Preference.notifyChanged(Preference.java:2)
	at androidx.preference.Preference.setSummary(Preference.java:4)
	at org.mozilla.fenix.settings.logins.SyncLoginsPreferenceView.updateSyncPreferenceStatus(SyncLoginsPreferenceView.kt:4)
	at org.mozilla.fenix.settings.logins.SyncLoginsPreferenceView.access$updateSyncPreferenceStatus(SyncLoginsPreferenceView.kt:1)
	at org.mozilla.fenix.settings.logins.SyncLoginsPreferenceView$1.onAuthenticated(SyncLoginsPreferenceView.kt:1)
	at mozilla.components.service.fxa.manager.FxaAccountManager$accountStateSideEffects$6.invoke(FxaAccountManager.kt:3)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.service.fxa.manager.FxaAccountManager.notifyObservers(Unknown Source:7)
	at mozilla.components.service.fxa.manager.FxaAccountManager.stateActions(FxaAccountManager.kt:10)
	at mozilla.components.service.fxa.manager.FxaAccountManager$processQueue$2.invokeSuspend(FxaAccountManager.kt:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by ekager** [comment]
@s-ankur were you just in Settings before browsing? This looks like a settings crash

**Comment by s-ankur** [comment]
Yes, correct

**Comment by blerner** [comment]
I think I'm seeing something similar, but I had not been using the Settings page at all.  When navigating to a particular school-related website (a Rails app), every time I try to log in using a suggested login, Firefox crashes.  I've sent crash reports (I think), but dunno if they actually went anywhere.  I'm using v81.1.2, and have disabled the only two extensions I had installed, and that didn't make a difference.  I tried following the adb instructions, and I got a massive amount of debugging info.  I think the relevant stack trace is:
```
10-06 12:35:30.390 I/ActivityManager( 1492): Process org.mozilla.firefox (pid 9809) has died: fg  TOP 
10-06 12:35:30.407 W/InputDispatcher( 1492): channel 'a3b9037 org.mozilla.firefox/org.mozilla.fenix.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd
10-06 12:35:30.407 E/InputDispatcher( 1492): channel 'a3b9037 org.mozilla.firefox/org.mozilla.fenix.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-06 12:35:30.407 W/InputDispatcher( 1492): Attempted to unregister already unregistered input channel 'a3b9037 org.mozilla.firefox/org.mozilla.fenix.HomeActivity (server)'
10-06 12:35:30.421 I/libprocessgroup( 1492): Successfully killed process cgroup uid 10175 pid 9930 in 46ms
10-06 12:35:30.421 I/libprocessgroup( 1492): Successfully killed process cgroup uid 10175 pid 9809 in 0ms
10-06 12:35:30.446 D/ApplicationLoaders(12819): Returning zygote-cached class loader: /system/framework/android.test.base.jar
10-06 12:35:30.468 W/ActivityTaskManager( 1492): Force removing ActivityRecord{5d28ff1 u0 org.mozilla.firefox/org.mozilla.fenix.HomeActivity t1020}: app died, no saved state
10-06 12:35:30.484 I/sh.CrashHandle(12819): The ClassLoaderContext is a special shared library.
10-06 12:35:30.524 W/WindowManager( 1492): Failed to deliver inset state change to w=Window{a3b9037 u0 org.mozilla.firefox/org.mozilla.fenix.HomeActivity EXITING}
10-06 12:35:30.524 W/WindowManager( 1492): android.os.DeadObjectException
10-06 12:35:30.524 W/WindowManager( 1492): 	at android.os.BinderProxy.transactNative(Native Method)
10-06 12:35:30.524 W/WindowManager( 1492): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
10-06 12:35:30.524 W/WindowManager( 1492): 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:765)
10-06 12:35:30.524 W/WindowManager( 1492): 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3669)
10-06 12:35:30.524 W/WindowManager( 1492): 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$4$InsetsStateController(InsetsStateController.java:445)
10-06 12:35:30.524 W/WindowManager( 1492): 	at com.android.server.wm.-$$Lambda$InsetsStateController$-1iOXDf-1s3wDHcMIHBKNk6MS3I.run(Unknown Source:2)
10-06 12:35:30.524 W/WindowManager( 1492): 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:341)
10-06 12:35:30.524 W/WindowManager( 1492): 	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:222)
10-06 12:35:30.524 W/WindowManager( 1492): 	at com.android.server.wm.WindowAnimator.lambda$new$1$WindowAnimator(WindowAnimator.java:107)
10-06 12:35:30.524 W/WindowManager( 1492): 	at com.android.server.wm.-$$Lambda$WindowAnimator$ddXU8gK8rmDqri0OZVMNa3Y4GHk.doFrame(Unknown Source:2)
10-06 12:35:30.524 W/WindowManager( 1492): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
10-06 12:35:30.524 W/WindowManager( 1492): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
10-06 12:35:30.524 W/WindowManager( 1492): 	at android.view.Choreographer.doFrame(Choreographer.java:727)
10-06 12:35:30.524 W/WindowManager( 1492): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
10-06 12:35:30.524 W/WindowManager( 1492): 	at android.os.Handler.handleCallback(Handler.java:938)
10-06 12:35:30.524 W/WindowManager( 1492): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-06 12:35:30.524 W/WindowManager( 1492): 	at android.os.Looper.loop(Looper.java:223)
10-06 12:35:30.524 W/WindowManager( 1492): 	at android.os.HandlerThread.run(HandlerThread.java:67)
10-06 12:35:30.524 W/WindowManager( 1492): 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
10-06 12:35:30.615 D/NetworkSecurityConfig(12819): No Network Security Config specified, using platform default
10-06 12:35:30.624 D/NetworkSecurityConfig(12819): No Network Security Config specified, using platform default
10-06 12:35:30.692 E/mozac/CrashReporter(12819): CrashHandlerService received native code crash
10-06 12:35:30.706 I/mozac/CrashReporter(12819): Received crash: NativeCodeCrash(timestamp=1602002130705, minidumpPath=/data/user/0/org.mozilla.firefox/files/mozilla/0jko8789.default/minidumps/1c0c029d-bd34-5879-6982-1562262d864a.dmp, minidumpSuccess=false, extrasPath=/data/user/0/org.mozilla.firefox/files/mozilla/0jko8789.default/minidumps/1c0c029d-bd34-5879-6982-1562262d864a.extra, isFatal=true, breadcrumbs=[], uuid=8f6ee9a4-1336-4609-b2e2-d64bd9450945)
```

I can try to collect more information, if there are more specific instructions I could follow.

**Comment by ekager** [comment]
@blerner could you check about:crashes and see if there's anything there?

**Comment by blerner** [comment]
9 separate crash reports over the past few weeks -- one of them has a Socorro link; all of them have Share links.  What's the best way to send you those crash reports?  (I'm pretty sure nearly all of them are on that same course website, so they're probably pretty repetitive.  Happy to send all of them if you want.)

**Comment by ekager** [comment]
If you could attach the Socorro link here that would be great!

**Comment by blerner** [comment]
https://crash-stats.mozilla.org/report/index/d3080619-3d21-4363-9e1c-2b5f00200922

Dunno if the others are the same or not - I'm guessing they must be slightly different, or else they'd likely have the same socorro link?  (I didn't do anything special with that crash, so any socorro link was automatically determined.)

**Comment by ekager** [comment]
Thanks! Is the website this is happening on something you could also share or is it a private site? (If you don't feel comfortable posting it here you could email it me or DM me on Riot)

**Comment by blerner** [comment]
Emailed you the link.

Weirdly, I only crash fenix when I click on the purple "suggested logins" bar: if I type my username manually, then click the ->next keyboard button, fenix fills in the associated password without any trouble. I thought perhaps it might be an issue with special characters in the passwords, or maybe having several logins for that site? Even more weirdly, the suggested logins bar works fine on some other sites (I tried Bank of America as a quick sanity test). So I don't have a consistent pattern figured out yet.

Let me know if I should send the other crash reports somewhere...

**Comment by Iiz-vas** [comment]
Hi. This problem just existed when I tried to log in to my work email via
Outlook Web here: https://staffmail.brighton.ac.uk/my.policy

Something now seems to have been fixed as it has stopped crashing and I can
no longer recreate the crash.

Thank you

**Comment by Iiz-vas** [comment]
Problem seems to be solved - I can no longer make the crash happen. Thanks

**Comment by blerner** [comment]
Please don't close this yet -- this issue still is affecting me, and I've sent crash info to @ekager above to try to diagnose it further...  It _doesn't_ seem to happen on _every_ site, so this is definitely tricky...

**Comment by Iiz-vas** [comment]
I was wrong, I just got another crash. Sorry!

**Comment by ekager** [comment]
@blerner @liz-vas would you mind downloading Nightly and seeing if you can reproduce there? 
I tried with the sites you two provided and couldn't repro on my device. 

You can find Nightly here:
https://play.google.com/store/apps/details?id=org.mozilla.fenix

**Comment by Iiz-vas** [comment]
Hi. Yes just downloaded  nightly and reproduced the crash first try.

I have never done the crash log before so would like to help but it's going
to take me a while to find time.

**Comment by blerner** [comment]
I just had the more serious version of this crash happen, where going to the same site as before crashed my entire phone.  (At least that's the apparent sequence of events, I wasn't doing anything else on my phone at the time.) I don't know if I have any crash reports to send: the entire phone crashed, not just Firefox, and I don't know where Android crash logs might be stored...

**Comment by dbenjaminmiller** [comment]
For me this seems to occur whenever I have more logins than appear on one screen. So whenever the view might be scrollable.
