### ISSUE TITLE
Re: Slow html5 performance: games stutter

### ISSUE THREAD

**Issue by grenvol** [mozilla-mobile/fenix#15868]
## Steps to reproduce
Load an html5 game like Perfect Piano: https://play.famobi.com/perfect-piano

### Expected behavior
Game should be smooth and close to 60 fps

### Actual behavior
The game stutters and is choppy

### Device information

* Android device: Honor 8x max
* Fenix version: daylight 81.1.2

### Side note

This bug has already been reported in the past here: https://github.com/mozilla-mobile/fenix/issues/14842  https://bugzilla.mozilla.org/show_bug.cgi?id=1664950 and closed. However, I can 100% confirm that this bug is still present and easy to reproduce.
Please, be a bit more careful before closing bugs too quickly. Thank you.

**Comment by mcomella** [comment]
Thanks for following up – I reopened the original Bugzilla issue and asked them to be more careful about testing that this issue is addressed before closing it.

**Comment by liuche** [comment]
Hi @grenvol can you test this on nightly? Bugs are closed when they are verified on Nightly, and will make their way to release over the next few cycles. If you can still repro please reopen.

**Comment by grenvol** [comment]
I have been testing on and on, on Firefox nightly and I can confirm that I could still reproduce this bug across different versions.
Currently, I am on version Nightly 201031 17:02 Build#2015772939 and I can still reproduce the bug.
