### ISSUE TITLE
A "dead" area is displayed on websites with a "sticky" header after the screen has been wiped up and down several times.

### ISSUE THREAD

**Issue by tachtler** [mozilla-mobile/fenix#16386]
Dear Mozille-Firefox-Android-Team,

## Steps to reproduce

Open e.g. the website

[https://homepage.tachtler.net/homepage/de_mobile_01_main.action](https://homepage.tachtler.net/homepage/de_mobile_01_main.action)

or

[https://media.kulturbanause.de/2017/04/responsive-sticky-footer-table-layout.htm](https://media.kulturbanause.de/2017/04/responsive-sticky-footer-table-layout.htm)

or **many other sites with a "sticky header"**

in Firefox for Android and **wipe the screen up and down several times**.

A **"dead" area** is now displayed on the **lower screen wheel**, which is no longer included in the 100% height of the screen.

### Expected behavior

**No "dead" area should be displayed** on the lower screen wheel. 

See the following screenshot once with the **"wrong"** representation in Firefox for Android

![grafik](https://user-images.githubusercontent.com/11161944/98208081-f68f0900-1f3c-11eb-9d2f-765465dd80be.png)

and one with the **"right"** representation in Chrome for Android.

![grafik](https://user-images.githubusercontent.com/11161944/98208121-0c043300-1f3d-11eb-95ce-f9b89ea9fa2a.png)

### Actual behavior

**This problem occurs on many web pages with sticky header**

Open a **website with a sticky header**.

**Wipe the screen up and down several times**.

A **"dead" area** is now displayed on the **lower screen wheel**, which is no longer included in the 100% height of the screen.

### Device information

* Android device: Samsung Galaxy S8 ( SM-G950F )
* Android version: Stock image, Android Version 9
* Kernel -Version: 4.4.111-18920278

* Fenix version: 82.1.1 (Build #2015770923)

Thank you!
Klaus Tachtler.

**Comment by jomisica** [comment]
Hi tachtler,

I can confirm that it happens, but only when the toolbar menu is at the top.

Android device: A20e
Fenix version: 82.1.1

**Comment by jimparis** [comment]
This is a simple demo of what is probably the same bug, which only happens when the toolbar is on the top:
https://psy.jim.sh/~jim/tmp/ff.html

**Comment by tachtler** [comment]
Update the title and problem description!

**Comment by Mugurell** [comment]
@tachtler Thank you for the report!
I think this should be fixed in the current Nightly & Beta.
Can you please confirm?

**Comment by tachtler** [comment]
@Mugurell The problem still exists!

I figured it out, using Firefox Nightly:

Nightly 210203 17:01 (Build #2015791179)
AC: 73.0.20210202194906, 59dddc21f
GV: 87.0a1-20210202095107
AS: 69.0.0

You can try it by yourself, using my development homepage:

https://homepage.tachtler.net/homepage/de_mobile_01_main.action

Sorry, for the bad news.
Klaus Tachtler.

**Comment by sflorean** [comment]
This issue is still reproducible on latest Nightly 4/12 with Samsung Note 10 (Android 11).

**Comment by lobontiumira** [comment]
Reproducible on twitter.com, on RC 88.1.4 with Samsung Galaxy Note 8 (Android 9).

**Comment by Mugurell** [comment]
This seems like a GeckOView issue but I was unable to reproduce it.
@tachtler @lobontiumira Can you please post a video showing the issue? It would help us greatly.

**Comment by Mugurell** [comment]
> This is a simple demo of what is probably the same bug, which only happens when the toolbar is on the top:
> https://psy.jim.sh/~jim/tmp/ff.html

I think this issue is now resolved. @jimparis can you please confirm?

**Comment by lobontiumira** [comment]
I was able to reproduce this issue also on Beta 89.0.0-beta.8 on instagram.com, with Samsung Galaxy Note 8 (Android 9):

https://user-images.githubusercontent.com/40694158/118661199-933d3800-b7f7-11eb-9448-b3091045e085.mp4

**Comment by Mugurell** [comment]
I wasn't able to reproduce but this seems like a GV issue, moving it to Bugzilla.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1712280

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jimparis** [comment]
> > This is a simple demo of what is probably the same bug, which only happens when the toolbar is on the top:
> > https://psy.jim.sh/~jim/tmp/ff.html
> 
> I think this issue is now resolved. @jimparis can you please confirm?

I can confirm that it's fixed for me in 88.1.4, thanks!
