### ISSUE TITLE
[Bug] Crash when tapping on "Firefox account" with non-English system language

### ISSUE THREAD

**Issue by sivaraam** [mozilla-mobile/fenix#17002]
## Steps to reproduce
1. Set system language to a non-English language
1. Open 'Settings'
1. Tap on the account menu

### Expected behavior
The "Account settings" page opens.

### Actual behavior
Fenix crashes.

### Device information
* Android device: 5.1.1
* Fenix version: 83.1.0

**Comment by LittleAngelwings** [comment]
no crashes for me with 83.1.0 using Android 8.1.0 and 9.1.0

**Comment by sivaraam** [comment]
Interesting. Anyways, it's always reproducible for me. It might be worth noting that I use [F-droid version of the app](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/). Let me know if more information is needed.

**Comment by ekager** [comment]
Without logs and without being able to repro on master this isn't actionable. 

@sivaraam let us know if you can collect logs from the crash https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by sivaraam** [comment]
This looks like the related log for the crash: https://crash-stats.mozilla.org/report/index/ac9c070c-b6b6-4ab7-80d5-7220b0201212

**Comment by codrut-topliceanu** [comment]
Hey @Delphine . This issue stems from the Thai translation of the app: `ta/strings.xml`
![image](https://user-images.githubusercontent.com/60002907/104172537-1e06c400-540d-11eb-8229-fe02f630577b.png)

The last two characters should be `%s` not `%@`.

**Comment by Delphine** [comment]
This has been updated in Pontoon, thanks for flagging (language was actually Tamil).
Pontoon syncs every 20 min, so this should be fixed very quickly

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 1/13 with Nexus 5 (Android 6.0.1). When having the Tamil language set and accessing the Account setting page, the app does not crash.

This crash is still reproducible on the latest Beta 85.0.0-beta.7 from 1/12 and Release 84.1.4 from 1/7.

I will remove the qa:needed label and close this issue.
