### ISSUE TITLE
[Bug] Title not shown correctly in media control after next track loads in Youtube playlist

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#17368]
## Steps to reproduce
Go to https://m.youtube.com/playlist?list=PL4B22D54E54AC7CB9 and start playback. Watch out for the behaviour of the media control in the notification tray as the first track finishes and the second track loads.

### Expected behavior
The current page title is correctly shown in the media playback control even after a Youtube playlist changes to the next track.

### Actual behavior
For the first track, things work as expected, i.e. the page title is shown in the first line of the media playback control and the page URL in the second line. Once Youtube switches to the next track, both lines start showing the page URL, though.

### Device information

* Android device: Moto G4 Play, Android 6.0.1
* Fenix version: Nightly 2021-01-07

**Comment by ekager** [comment]
cc @rocketsroger probably related to new media session API?

**Comment by rocketsroger** [comment]
Yes, this is related to the new MediaSession API.  Here's the issue that is related to this https://github.com/mozilla-mobile/android-components/issues/9170.  I've just put up a change that will fix this.  @buttercookie42 Thanks for reporting this use case, I've tested and it works with the new change.

**Comment by rocketsroger** [comment]
This is fixed in Nightly.  Please verify.  Thanks,

**Comment by abodea** [comment]
I can still reproduce this issue on the latest Nightly build 1/29 with Google Pixel 4 XL (11).
Note that once Youtube switches to the next track, both lines start showing the page URL, though.
![Screenshot_20210129-123113](https://user-images.githubusercontent.com/42831109/106264576-7ff96300-622e-11eb-9a19-ea653b36cbef.png)

**Comment by rocketsroger** [comment]
Unfortunately 1/29 Nightly only picked up one of the two fixes needed.  Please verify on latest nightly.  Sorry about the confusion.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 2/3 with Pixel 3 (Android 11).
