### ISSUE TITLE
[Bug] Each open tab is a gray screen

### ISSUE THREAD

**Issue by Larkagi** [mozilla-mobile/fenix#17719]
Starting in version 84, each open page is displayed as a gray fill.
Navigation bar and preferences are displayed correctly. 
The captured screenshot shows the correct image.

Device information:
    Mecool Km1 AMLOGIC S905X3
    Stock-ROM Android TV 10
    Firefox 85.1.1, Firefox Beta 86.0.0-beta.1

**Comment by amedyne** [comment]
@Larkagi Please attach the screenshot. Thank you!

**Comment by Larkagi** [comment]
![Firefoxscr](https://user-images.githubusercontent.com/78321191/106401584-2e66f900-6425-11eb-80b8-b9819f8e0d7b.jpg)

Here you are.

**Comment by Mugurell** [comment]
Thank you for the report @Larkagi 
This issue seems similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1683936 which should have been resolved in the current Beta.
If not maybe we should do something similar for the Mail-G31 that powers this also.
Moving the ticket to Bugzilla since it's a graphics issue.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1689947

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
Hi @Larkagi, thank you for the bug report and sorry for any inconvenience this has caused.

This might be difficult given that rendering is broken, but if you visit about:config, search for gfx.webrender.force-disabled and set it to true, then restart, your browser should work again.

After doing that, would it be possible to attach the about:support information? Do you have USB access to the device? Are you able to capture a logcat of launching Firefox and opening a page with this bug?

Thanks!

**Comment by Larkagi** [comment]
Thank you @jamienicol.

Unfortunately, the about: config tab is broken too. I see gray fill and I can't change anything.
about: support information I copied blindly.
[support.txt](https://github.com/mozilla-mobile/fenix/files/5906773/support.txt)

**Comment by jamienicol** [comment]
Just to update you @Larkagi, this should be fixed in upcoming releases (of Nightly, Beta, and Release) in the next few days. Thanks again for reporting the issue!

**Comment by Larkagi** [comment]
Hi @jamienicol

I checked version 85.1.3 and 86.0.0-beta.4 and the problem still exists.

**Comment by jamienicol** [comment]
@Larkagi thank you for letting me know, that's not what I expected.

I know it was hard because you couldn't see, but could you please get the attach the about:support data again from the new version? Thanks

**Comment by Larkagi** [comment]
No problem.
[support 86beta5.txt](https://github.com/mozilla-mobile/fenix/files/5983358/support.86beta5.txt)
[support 85.1.3.txt](https://github.com/mozilla-mobile/fenix/files/5983359/support.85.1.3.txt)

**Comment by Larkagi** [comment]
I also noticed that sometimes after installation, the image flashes when you scroll and you can see the content. The second launch removes this effect and it is just like I wrote earlier.

**Comment by Larkagi** [comment]
@jamienicol everything works OK if I turn on "Disable HW Overlay" in developer options.
