### ISSUE TITLE
[Bug] BBC.com videos not showing

### ISSUE THREAD

**Issue by infiniumX** [mozilla-mobile/fenix#17715]
### Steps to reproduce

Open any page with videos on www.bbc.com/news

### Expected behavior

Firefox should show/load the video so it can be played.

### Actual behavior

Instead of the video a grey placeholder with the BBC logo is shown, with the caption of the video at the bottom (if present). It does not matter whether ETP is on or off. If all cookies are deleted (using Delete Browsing Data) before opening the page, a popup that prompts the user to accept the cookie agreement is displayed and after accepting the video IS loaded and can be played. But once you reload the page (or load any other page with videos) the placeholder is shown again and the videos can no longer be played. Interestingly the videos on the site do load normally and can be played in privacy mode. The bug is not related to uBlock origin as it manifests even with the addon uninstalled (and when enabled is also running in privacy mode where videos load normally). Disabling the Video Background Play Fix addon also doesn't change anything (and it is also running in privacy mode where videos load normally).

### Device information

* Device vendor / model and Android version: 
Samsung Galaxy A40 / Android 9 (security patch level : 1 March 2019 )
* Firefox for Android version: 
Firefox Daylight 85.1.1
* Addons: uBlock Origin, Search by Image, Google Search Fixer, Video Background Play Fix

**Comment by LittleAngelwings** [comment]
No problems with stable Firefox and Android 9, also with uBlock Orgin. Can play and see all videos on bbc.com.

**Comment by infiniumX** [comment]
Just to add that this buggy behavior has been going on for more than a couple of versions now. So it's not tied to the latest update. It's possible that if I delete all app data it will be fixed, but I have a lot of favorites and history, etc.

**Comment by LittleAngelwings** [comment]
Please try a nightly or beta version from Google Play Store. They'll be there own separate profiles.

**Comment by Mugurell** [comment]
Tried with the same addons installed and for me the latest version starts playing all videos as expected, even after reloading the page, closing and restoring the tab, opening other bbc pages.
Asking QA for help in reproducing.

**Comment by infiniumX** [comment]
I will try the nightly/beta version, but I am pretty sure that the videos will work. I think a good indicator is that the videos are working in privacy mode (with all plugins active), so I think the main question is: what is the main difference between privacy and normal modes that might be relevant to this bug? Is a different profile used for the private session indicating that the non-private profile might be corrupt? Or some other difference between the two modes? I haven't looked exactly at how bbc loads the videos but it seems that a script that is doing the job is getting blocked/not executing properly for some reason.

**Comment by infiniumX** [comment]
Confirmed videos working in latest Firefox Beta (85.0.0-beta.9).

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce the issueon the RC 85.1.1 build with Samsung Galaxy Note 8 (Android 9).
I had all 4 add-ons installed and enabled both in normal and private browsing, I stopped, paued, resumed different videos on BBC page and everything worked as expected.
I'll remove the qa:needed label.

**Comment by Mugurell** [comment]
Seems like the issues is resolved.
Closing this ticket as such.

Feel free to leave comment if you'll see this again.

**Comment by infiniumX** [comment]
Sorry, but the issue is not resolved. The videos are loading on Firefox Beta but the issue persists on the last stable, and I'm pretty sure once I upgrade to the next new version it'll still be there - as I said this has been going on for more than a couple of versions now. Can you at least give me some idea how I can resolve this and what might be the possible cause? Is it possible that I somehow export the bookmarks/history from Firefox, say using adb - is Sync the only option and can Sync also keep my history? Or can I somehow refresh the profile without losing the data, again maybe using adb?

**Comment by infiniumX** [comment]
New development: the problem is probably related to cookies/local storage. When I go to the Sign up page for Sync I get the message: Cookies and local storage are required. Local storage is enabled in the app permissions. So it seems that maybe cookie/local storage management got corrupted in some upgrade. So I can't even sign up/sign in with Sync (even if I first sign up on desktop).
