### ISSUE TITLE
Custom settings made through about:config reverts back to default

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#18733]
Fenix version: Fenix-beta-88.0.0.2

Custom changes made through about:config reverts back to their default state after exiting(clearing fenix from recent apps) fenix. Properties like;

* dom.security.https_only_mode -> reverts back to false

* javascript.enabled -> reverts back to false

* network.cookie.behavior -> reverts back to 4 and network cookie lifetime policy reverts back to 0

I believe the *dom.security.https_only_mode* issue started after fenix beta-87.0.0.3 version.

**Comment by ebalazs-sv** [comment]
I had tested this on the latest Nightly 4/1, Beta 88.0.0-beta.3, RC 87.0.0-rc.1 with Samsung Galaxy Tab S3 (Android 8) and could not reproduce the issue.
Tested with ETP set to Standard, Strict or Custom, also when "Delete browsing data on quit" is set to on.
@samiuljoy Hi! What device did you use? What were the settings on the device? Thanks!

**Comment by samiuljoy** [comment]
@ebalazs-sv I think clearing Fenix from recents is also necessary. I've tested Fenix 88.0.0.2 beta on Android 5.1.1 and Android 10, quiting(from the X on the snackbar) does not revert custom changes, however if fenix is cleared from recent app, then these changes reverts back to default. Clearing fenix from recent apps is necessary to reproduce this issue apparently.

**Comment by ebalazs-sv** [comment]
When I tested this issue, I exited Fenix by closing it from Recent apps and did not reproduce the issue on the mentioned builds and device.

**Comment by samiuljoy** [comment]
@ebalazs-sv well, that's odd, I've made a adb screenrecord while trying out fenix on my Samsung running Android 10
* Included the build number
* went to about:config and changer the https value to true
* then quit fenix
* the clear fenix from recents
* start fenix and visit about:config and check the https value
* the https value reverts to false

https://user-images.githubusercontent.com/51329626/114296371-e7544e80-9acc-11eb-9e6e-4cce20a4169b.mp4

**Comment by njdarger** [comment]
This happens to me on multiple devices, including Android 11 on OnePlus Nord. Most often on devices with less RAM where Firefox has been closed when switching to other applications. I can reproduce it on multiple different devices (Android 11/Nord, Android 9 on Huawei MediaPad M5 8.4") by:
* Going to about:config
* Disabling JavaScript
* Rebooting the device.
* JavaScript has now reverted back to enabled.

**Comment by yeezylife** [comment]
Same issue here on (Android 11/Xiaomi 10/Beta 89.0.0-beta.5) I've changed "security.enterprise_roots.enabled"to "true" 3 times,because I need to solve the security certificate problem caused by adguard.
But everytime it goes back to default after exiting firefox.

**Comment by djec** [comment]
Hello, same issue here. I installed firefox nightly because i needed to change security.enterprise_roots.enabled for AdGuard, but the setting keep revert to default value.
I'm on a OnePlus 8 with Android 11.

90.0a1 (Build #2015808843)
AC: 90.0.20210504190127, 37e9d2a69
GV: 90.0a1-20210504092024
AS: 75.2.0

**Comment by cadeyrn** [comment]
> Hello, same issue here. I installed firefox nightly because i needed to change security.enterprise_roots.enabled for AdGuard, but the setting keep revert to default value

There is a visible option in the secret settings now. That's why this option in about:config no longer works.

**Comment by djec** [comment]
Indeed, thank you for the information, I'll try it !
![Screenshot_20210508-115236](https://user-images.githubusercontent.com/28660446/117535010-1db1ba80-aff4-11eb-86f4-752ece44cafa.jpg)

**Comment by yeezylife** [comment]
> > Hello, same issue here. I installed firefox nightly because i needed to change security.enterprise_roots.enabled for AdGuard, but the setting keep revert to default value
> 
> There is a visible option in the secret settings now. That's why this option in about:config no longer works.

I'm using Beta 89.0.0-beta.5 and I can't seem to find this setting anywhere,maybe it;s only on nightly?

**Comment by iamtalhaasghar** [comment]
I tested "javascript.enabled" setting on Firefox nightly. It does reverts back to "true" when you close all tabs and clear firefox from recent apps screen.

Firefox Version:
90.0a1 (Build #2015809611)
AC: 90.0.20210510143050, 471da2b44
GV: 90.0a1-20210510093555
AS: 75.2.0
Monday 5/10 @ 5:35 PM

**Comment by jt15s** [comment]
Using Firefox Nightly (the latest build) and can't seem to find the "secret settings" page mentioned above anywhere. Has this been rolled out yet to all Nightly users?

**Comment by cadeyrn** [comment]
> Using Firefox Nightly (the latest build) and can't seem to find the "secret settings" page mentioned above anywhere. Has this been rolled out yet to all Nightly users?

Yes. It's called "Secret Settings" because it's a "secret" page and not visible by default. You have to open the settings > About Firefox screen and tap the Firefox logo five times. Then you can see the new "Secret Settings" item in the settings screen.

**Comment by jt15s** [comment]
Ah okay. Thanks for helping me out!

**Comment by INFERNO777** [comment]
Hello, same issue here. I installed firefox nightly because i needed to change security.enterprise_roots.enabled for AdGuard, but the setting keep revert to default value. Samsung A51 android 11

**Comment by jt15s** [comment]
> Hello, same issue here. I installed firefox nightly because i needed to change security.enterprise_roots.enabled for AdGuard, but the setting keep revert to default value. Samsung A51 android 11. broke quickly, but there is no way to fix it. 3 months have already passed. A great desire to abandon firefox forever, too many problems

Hey @INFERNO777, you can fix the issue by following @cadeyrn's instructions above my reply from 10 days ago. I should mention that the issue is fixed now after following the steps.

**Comment by esjarc** [comment]
Unfortunately this issue is still relevant for other configuration options, like `dom.security.https_only_mode`.

**Comment by cadeyrn** [comment]
Adding support for HTTPS only mode is #16952.

**Comment by hackel** [comment]
It is **extremely** important that Fenix never revert any manually set about:config settings without user intervention.  If there is a legitimate need to do so, a message should pop up listing which settings have been changed from the user-specified values.

Many of these settings are critical security and privacy preferences.  Allowing users to continue browsing without knowing they have been changed is dangerous and irresponsible.
