### ISSUE TITLE
FNX-5334 ⁃ [Bug] maps.google.com icon is not displayed on Settings-Site permissions-Exceptions

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#1919]
## Steps to reproduce
1. Go to maps.google.com.
1. Allow access to location.
1. Go to Settings ~~> Site permissions~~ > Exceptions and observe the icon.

### Expected behavior
The page from step 1 should have a favicon displayed.

### Actual behavior
The icon displayed is a green square with a with "W" letter, no matter which site is in the exceptions.

### Device information
* Android device: Google Pixel (Android 9), Samsung Galaxy Tab S3 (Android 8), Nexus 6 (Android 7.1.1)
* Fenix version: 1.0.1917 (Build#11121210)

### Note: 
Based on #188 the favicons should be displayed.

![Untitled](https://user-images.githubusercontent.com/40694158/56580805-2cc79a80-65dc-11e9-8fde-8d2a73c4faa1.png)

**Comment by cpeterso** [comment]
AC needs to extract website icons from the page: mozilla-mobile/android-components#2080

**Comment by abodea** [comment]
The issue still reproduces, exactly like in the [description](https://github.com/mozilla-mobile/fenix/issues/1919#issue-436158955).
Tested on the latest build **`1.0.1922 (#build11480607), with Samsung Galaxy Note 9(Android 8.1.0) and Google Pixel 3(Android 9).`**

**Comment by Amejia481** [comment]
Be aware, that some sites like maps.google.com their icons are not showing  even on the home page, but other website like https://permission.site/ and https://www.mapquest.com/ are showing properly. I don't know if we have a issue for that.

![Screenshot_20190531-175834](https://user-images.githubusercontent.com/773158/58737048-11676080-83ce-11e9-8990-891d5cd17872.png)


![image](https://user-images.githubusercontent.com/773158/58736750-f9431180-83cc-11e9-8f44-991f46e0a8b5.png)

**Comment by softvision-miralobontiu** [comment]
The icon of maps.google.com is still not displayed, on the latest build 1.0.1922 (#11530616), with Google Pixel (Android 9).
Considering the STR were strictly for this page (maps.google.com), I'll rename this issue accordingly.

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/android-components/issues/3294

**Comment by Amejia481** [comment]
This was fixed by https://github.com/mozilla-mobile/android-components/commit/05fed1975c48524dd556fb0a69eee286e15d8bb8

**Comment by abodea** [comment]
I can still reproduce this issue on the latest build **`6/28(1.0.1926(Build #11791805 68.0-20190612114833))`** with Samsung Galaxy Note 9(A 8.1.0).
Please note that not even permission.site icon is displayed.
I tried with android 5, 6, 7, 8, 9.
![Screenshot_20190701-144252_Firefox Preview](https://user-images.githubusercontent.com/42831109/60434092-08f18800-9c0f-11e9-840d-c580dcfd9fd8.jpg)
Also, for maps.google.com I was able to reproduce #3795

**Comment by abodea** [comment]
Verified as fixed on the latest build from **`7/3 with Samsung Galaxy Note 9(Android 8.1.0).`**
The google Icon is displayed accordingly.
