### ISSUE TITLE
FNX-5377 ⁃ [Bug] Previously searched term remains on the address bar after the user leaves DDG to a result when DDG is set as default search engine.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1980]
## Steps to reproduce
Set DDG as default search engine
Search anything from the address bar
Touch a result
Touch the address bar

### Expected behavior
The address bar shows the address of the page you are in

### Actual behavior
The address shows the previously searched term as if you still are on duckduckgo.com

### Device information
* Android device: 8.0
* Fenix version: 1.0.1917

**Comment by kbrosnan** [comment]
@Lululalu this should be fixed by #1205. Please re-test when you get a chance.

**Comment by Lululalu** [comment]
@kbrosnan I re-tested it, and it's not fixed. Maybe the fix for #1205 was even what caused this bug in the first place. I recorded a video showing the bug happening.

https://streamable.com/2t1hv

**Comment by kbrosnan** [comment]
@sblatz this is similar to #1205 but for non-Google, Amazon, Wikipedia search engines. Bing, DGG, and Twitter fail to show the address after navigating and then pressing the back button.

**Comment by vesta0** [comment]
We had a similar bug in Focus and filed a [GV ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1487542) for it. It would be worth to look into what GV implemented.

**Comment by Lululalu** [comment]
This bug is not reproducible for me anymore, therefore I am closing this issue.

#4717 is still there though.
