### ISSUE TITLE
FNX-5387 ⁃ [Bug] address bar is partly hidden after using fullscreen mode (Device with physical buttons issue)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1998]
### Steps to reproduce
1. open https://davidwalsh.name/demo/fullscreen.php
1. press "Launch Fullscreen" button
1. press "Hide Fullscreen" button

### Expected behavior
The browser toolbar is visible.

### Actual behavior
Only the half of the browser toolbar is visible and you can't make it fully visible.
<img width=350 src=https://user-images.githubusercontent.com/1100614/56689528-937fad80-66db-11e9-94a3-3c90ce3e4a8a.png>

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision eadce68e520d1bc2c6be853d1481b5f62b620449

**Comment by ekager** [comment]
This will also be closed by https://github.com/mozilla-mobile/fenix/pull/1999

**Comment by cadeyrn** [comment]
@ekager It's *not* fixed by #1999.

**Comment by ekager** [comment]
There hasn't been a new build today yet with #1999 included, did you build master locally?

**Comment by cadeyrn** [comment]
Yes, I tested with a new build from master (after f897c2e295cd1b97d4024c7a9cb45dceb7a2fa89 so #1999 is included).

**Comment by ekager** [comment]
Have you tested this again? I am not able to reproduce on my device on master.

**Comment by cadeyrn** [comment]
Yes. I compiled a new build from master (after e6c34f7045f36c091848c0ecaffbb09d5c95d35e) and it's still an issue.

![20190427_084739](https://user-images.githubusercontent.com/1100614/56845997-90e2ab00-68c9-11e9-95d7-f15546a36cf3.gif)

**Comment by softvision-miralobontiu** [comment]
Hi,

I can reproduce this issue on HTC 10 (Android 8.0), on the latest build 1.0.1920 (#11350639).
I followed the STR from [Comment 0](https://github.com/mozilla-mobile/fenix/issues/1998#issue-436878271):
1. Open https://davidwalsh.name/demo/fullscreen.php
2. Tap on "Launch Fullscreen" from the page loaded at Step 1.
3. Tap on "Hide Fullscreen" from the page loaded at Step 1.
4. Observe the address bar.

Thanks,

Notes: Not reproducible on Google Pixel (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by ekager** [comment]
See also #2101 where an HTC device is having issues with the window flags we are settings. Possibly related.

**Comment by sblatz** [comment]
I have a feeling this may have been fixed by [disabling the dynamic toolbar](https://github.com/mozilla-mobile/fenix/issues/2689). I don't have an HTC device on hand, though. @softvision-miralobontiu are you able to reproduce still?

**Comment by cadeyrn** [comment]
No, disabling the dynamic toolbar did not fix this issue.

**Comment by softvision-miralobontiu** [comment]
Still reproducing with the latest build 1.0.1922 (#11501805), on HTC 10 (Android 8).

**Comment by sblatz** [comment]
I time-boxed an investigation for this and cannot seem to find any reports of HTC not respecting certain window flags. My thought is redrawing the window when exiting fullscreen could help if it's stuck in this broken state, but that's really just a band-aid. 

I also don't have an HTC device to be able to test any solutions I have. I'm going to leave this ticket open for an engineer who has an HTC device to pick up.

**Comment by sv-ohorvath** [comment]
@sblatz This is not an HTC device issue, it's happening on devices with physical buttons:
e.g. HTC 10, Samsung Galaxy Tab 3, Xiaomi Mi 4i.

**Comment by ekager** [comment]
Hi @sv-ohorvath ! Just added a change to test something that *may* fix this issue but really not positive. Could someone test with one of these physical button devices? Thanks!

**Comment by cadeyrn** [comment]
@ekager It's fixed by your change (HTC U11).

**Comment by ekager** [comment]
That's great! Because I wasn't sure what else to try ;) 
Will wait for QA confirmation as well, but glad it fixed your device @cadeyrn thanks for checking!

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest build 1.0.1924 (6/10), with Samsung Galaxy Tab A 6 (Android 5.1.1), and THTC 10 (Android 8).
