### ISSUE TITLE
[Bug] Bookmarks get the last used folder as parent in edit mode

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#19993]
Similar to #1596

## Steps to reproduce

1. Creat or edit a bookmark.
2. Edit a second bookmark.

### Expected behavior
Second bookmark:
The correct folder of the bookmark is displayed.

### Actual behavior
Second bookmark:
Instead, the last (current) folder of bookmarks from step 1 is displayed. If this is not corrected manually, the bookmark is actually moved incorrectly as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11024)

**Comment by WebworkrNet** [comment]
**Device information**

    

- Samsung Galaxy XCover 4s, Android 10
- Firefox for Android version: 89.1.1

**Comment by SoftVision-LorandJanos** [comment]
Hi @WebworkrNet ! Thank you for your report! I was able to reproduce the issue you described.
Tested on the latest Nightly (Monday 6/14 @ 5:07 AM)
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by codrut-topliceanu** [comment]
@WebworkrNet Is this the behavior you are referring to ? (confirmed with @SoftVision-LorandJanos , that is the behavior he reproduced)


https://user-images.githubusercontent.com/60002907/122398215-58f3c180-cf82-11eb-830e-104ab4fe086c.mp4

I have not been able to reproduce the same "wrong folder" issue when editing from the actual Bookmarks fragment ( 3dot menu -> Bookmarks -> edit)

@topotropic Could you please confirm that the behavior seen in the above video is NOT intended?
(Personally I've always found it quite handy when I want to bookmark several websites at the same time in the same folder)

**Comment by WebworkrNet** [comment]
@codrut-topliceanu 
No, the video describes another process that I previously assumed was deliberately implemented that way.

The difference is that I didn't talk about saving a second bookmark, but only (!) editing an existing bookmark in step 2.

Based on the example in the video, it would look like this: In step 2, an entry from the "test 1" folder is edited. However, the "test 2" folder is then incorrectly output for editing in the dialog.

**Comment by topotropic** [comment]
> @topotropic Could you please confirm that the behavior seen in the above video is NOT intended?
> (Personally I've always found it quite handy when I want to bookmark several websites at the same time in the same folder)
Yes, this is correct.

What @WebworkrNet describes sounds like a bug. I can't reproduce it though.

**Comment by codrut-topliceanu** [comment]
@WebworkrNet I'm really sorry but I'm not able to reproduce the issue. Maybe I'm not following the steps correctly. Could I bother you to post a recording of the erroneous behavior in question? 
Or maybe QA can help with STRs?

**Comment by WebworkrNet** [comment]
I try to do this.

This may take a few days.

Should someone else be faster, feel free ...

**Comment by abodea** [comment]
I was not able to reproduce this issue on the latest **Nightly 6/24 with Google Pixel 4 XL (11).**
@WebworkrNet can you also provide a video while reproducing this issue? 
Removing `eng:qa:needed` until further information.

**Comment by WebworkrNet** [comment]
I have gone through the scenario again in detail.
The phenomenon occurs when editing the active tab, which is already saved as a bookmark.

**Comment by WebworkrNet** [comment]
https://user-images.githubusercontent.com/43509007/135357240-4a9e2174-a723-47de-99a6-9872760fea0f.mp4

**Comment by ddarfantasy** [comment]
Another problem: if I restart the browser, fenix won't remember my last folder.

**Comment by amedyne** [comment]
@WebworkrNet #20307 has been fixed. Can you validate if that addressed the issue here, too?

**Comment by WebworkrNet** [comment]
I'm sorry, but I can't confirm that. The error I reported in #19993 still occurs in the same way.

- Samsung Galaxy XCover 4s
- Android 11
- Firefox Daylight
96.3.0 (Build #2015859795), 5a685e67c+
AC: 96.0.15, 0178a6fde9
GV: 96.0.3-20220126154723
AS: 86.2.2

**Comment by amedyne** [comment]
Thank you for checking this on the latest Firefox version.

**Comment by WebworkrNet** [comment]
Tested again, error still occurs.

- Samsung Galaxy XCover 4s
- Android 11
- Firefox Daylight
97.1.0 (Build #2015860771), 365e9fb59+
AC: 97.0.10, d6ce171289
GV: 97.0-20220131171509
AS: 87.1.0

**Comment by WebworkrNet** [comment]
@ddarfantasy 
> Another problem: if I restart the browser, fenix won't remember my last folder.

I am not sure if this is really a mistake. It could be intentional. 

If necessary, I think you should search for an already opened ticket that shows your situation or open a new one.
