### ISSUE TITLE
[Bug] Interacting with video in fullscreen mode makes status bar appear permanently

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#20240]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
View a video with, for example, the native video player in fullscreen mode and long press it, or watch a youtube video in fullscreen and change the quality

### Expected behavior
The android status bar appears, after the context menu (or youtube settings) is dismissed, the status bar disappears again. This is the behaviour of other browsers
### Actual behavior
The status bar stays visible until exiting fullscreen mode
### Device information

* Device vendor / model and Android version: Huawei Nova 6 (Android 10) 
* Firefox for Android version: 91.0a1 (Build #2015819787)

**Comment by Nickoriginal** [comment]
Reproducible in 89.1.1 on **Samsung Galaxy A20s**, but, in my case, navigation bar too appear permanently.

**Comment by SoftVision-LorandJanos** [comment]
Hi @mobd ! Thank you for your report! I can reproduce the issue you described on Samsung Galaxy Tab 3 (Android 9). Using a Motorola Nexus 6 (Android 7.1.1), I can reproduce your issue with the detail @Nickoriginal added (the navigation bar remains on screen as well). However using a Google Pixel 4 (Android 11) the issue is not reproducible, the full screen remains clean after the interaction.
Tested with the latest nightly (91.0a1 - 2021-07-05T05:06:51.686).

**Comment by mcarare** [comment]
Note: This is a known issue: https://issuetracker.google.com/issues/156065476.

**Comment by mobd** [comment]
@mcarare I'm not sure I understand that report but it seems to be about the status bar and navbar appearing at all, rather than permanently. In edge, dismissing a context menu in fullscreen hides the status bar and navbar again.

**Comment by mcarare** [comment]
Should be fixed by https://github.com/mozilla-mobile/android-components/pull/10576.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly (94.0a1 - 2021-09-13T05:10:02.695825). Tested on Huawei P30 with Android 10.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible.
Verified as fixed on the latest Nightly (2022-01-10).
Device used: Oppo Reno 6 (Android 11).
Closing the ticket as fixed.
