### ISSUE TITLE
[Bug] Several missing icons in all themes

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#20292]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open any website
2. Open the three-dot menu

### Expected behavior
All icons are present.

### Actual behavior
**In all themes (light, dark, private)**, several icons are missing, see the screenshots below:

![missing_icon1_marked](https://user-images.githubusercontent.com/42788925/124884281-696fe880-dfd2-11eb-9699-a44cabe1a2af.png)
![missing_icon2_marked](https://user-images.githubusercontent.com/42788925/124884297-6d036f80-dfd2-11eb-9e32-2b7dbe3fc878.png)

### Device information

* Device vendor / model and Android version: Sony Xperia Z2, Android 6.0.1
* Firefox for Android version: 91.0a1 (Build #2015820745)
AC: 91.0.20210707143115, 8bf33ff684
GV: 91.0a1-20210707095209
AS: 79.0.0

**Comment by hwinnemoe** [comment]
Since this hasn't been caught on other android versions, this may be an API specific issue. I'm experiencing this issue since 2021-07-06, so maybe https://github.com/mozilla-mobile/fenix/commit/a7a45df8fb7650ce230664123520ca9cccf7e5e6 could be the culprit here since it was not tested on Android 6 devices.

**Comment by Nickoriginal** [comment]
Hello!
_Not reproducible_ in Nightly 91.0a1 2021-07-07T20:05:59.523 on **Samsung Galaxy A20s**
<img src = https://user-images.githubusercontent.com/85299944/124908645-376e7e80-dff2-11eb-927c-0c0999e5084b.jpg width = 45%> <img src = https://user-images.githubusercontent.com/85299944/124908663-3c333280-dff2-11eb-9e42-cefebd08d4cc.jpg width = 45%>

**Comment by Nickoriginal** [comment]
Related to #20154.

**Comment by AndiAJ** [comment]
Hi, **reproducible** on the latest Nightly 91.0a1 using the following devices:
• OnePlus A3 (Android 6.0.1)
• LG Nexus 5 (Android 6.0.1)

► Video
![20210708-141304](https://user-images.githubusercontent.com/51314259/124913788-36d8e680-dff8-11eb-8958-699b4b28da57.gif)

**Comment by Nickoriginal** [comment]
@hwinnemoe, you are right. Confirmed in Nightly 91.0a1 2021-07-07T20:05:59.523 on Samsung Galaxy J2 Prime (Android **6.0.1**)
<img src = https://user-images.githubusercontent.com/85299944/124915302-0e51ec00-dffa-11eb-84d5-9171ca6de9ce.png width = 45%> <img src = https://user-images.githubusercontent.com/85299944/124915313-114cdc80-dffa-11eb-9a6e-b5ef117b0979.png width = 45%>

**Comment by mcarare** [comment]
AC issue: https://github.com/mozilla-mobile/android-components/issues/10571.

**Comment by SoftVision-LorandJanos** [comment]
Still reproducible on the latest Nightly (91.0a1 - 2021-07-14T05:06:58.101). Will be retested tomorrow.

Device used: LG Nexus 5 (Android 6.0.1).

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed in the latest Nightly (92.0a1 2021-07-15T05:06:45.440).

Device used: LG Nexus 5 (Android 6.0.1).

**Comment by AndiAJ** [comment]
Still reproducible on Firefox Beta 91.0.0-beta.1 using a OnePlus A3 (Android 6.0.1)

**Comment by sflorean** [comment]
Reproducible also with Huawei MediaPad M2 (Android 5.1.1) on the above build.

**Comment by amedyne** [comment]
@mcarare Can you put a PR to uplift the fix on Beta for this? Thanks!

**Comment by Nickoriginal** [comment]
There are also missing lock icon in the pop-up window and V symbol opposite the selected language in the Settings -> Language.
<img src = https://user-images.githubusercontent.com/85299944/125978827-464464e0-d8e3-4801-af22-5de43226ee5a.png width = 35%> <img src = https://user-images.githubusercontent.com/85299944/125978847-d02d1d44-4399-4b05-9b69-ad7bd6c9d431.png width = 35%>
(Samsung Galaxy J2 Prime, Android 6.0.1, 91.0.0-beta.1)

**Comment by Nickoriginal** [comment]
Fixed in Firefox **91.0.0-beta.2** on Samsung Galaxy J2 Prime (Android 6.0.1)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed with the latest beta (91.0.0-beta.2).
Device Used: LG Nexus 5 (Android 6.0.1).
Not reproducible on the latest Release (RC 90.1.2).
