### ISSUE TITLE
[Bug]: Push Notification doesn't open url

### ISSUE THREAD

**Issue by mohitkuldeep** [mozilla-mobile/fenix#20379]
### Steps to reproduce

Click on any push notification, it won't open any url on Firefox Android.

### Expected behaviour

It should open the url as specified while sending the push notification

### Actual behaviour

It just opens the browser.

### Device name

Samsung Galaxy S10 Lite

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.1

**Comment by Sipaw3310** [comment]
Potential duplicate #18663

**Comment by sheikh-azharuddin** [comment]
This is one of the long pending bug but no one is looking....😐

**Comment by Bakso69** [comment]
Firefox Mobile 95.2.0 same problem.

**Comment by LaurentiuApahideanSV** [comment]
The issue has been fixed by https://github.com/mozilla-mobile/fenix/issues/24618. I will close this issue as fixed.

**Comment by sheikh-azharuddin** [comment]
Not fixed properly...when firefox is active (in recent app panel) then only click working..for others it is simply opening the homepage
