### ISSUE TITLE
FNX-5452 ⁃ [Bug] Videos played from Custom tabs do not stop when custom tab is closed

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#2097]
## Steps to reproduce
* Open a link in a custom tab (e.g. from my email) whose page has video content
* Play the video
* Press back button in toolbar to close custom tab

### Expected behavior
Video's audio stops playback

### Actual behavior
Video's audio continues playing. **afaict, it's impossible to stop the video:** the custom tab is closed from the calling app (e.g. gmail) so you can't reopen it and opening Fenix directly does not give you access to the custom tab or video.

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1917

fwiw, as an Android user, it concerns me that Fenix (and likely GV specifically) continues running in the background even after I've closed the app without my consent, using my battery and hurting device performance. This goes back to my concern from #1838 where Fennec would run in the background (even without videos playing), slowing down my entire low-end device.

**Comment by ekager** [comment]
See related:
https://github.com/mozilla-mobile/fenix/issues/1679
https://github.com/mozilla-mobile/fenix/issues/1117

We need a GV API exposed through the AC engine
https://github.com/mozilla-mobile/android-components/issues/2827

**Comment by jonalmeida** [comment]
From the same bug in r-b https://github.com/mozilla-mobile/reference-browser/issues/660:
> Pressing the system back button does show the correct behaviour, which means we may need to duplicate that same functionality on the close button as well

This means that we aren't closing the session as we should when the CT back button is pressed so I don't believe this is related to the same GV bug.

**Comment by jonalmeida** [comment]
The a-c issue was just fixed; the next Fenix build should have this change.

**Comment by bsurd** [comment]
This is still not fixed in the latest build (5/10). Tested on a OnePlus 5T and Nexus 6.

@jonalmeida was the fix not merged?

**Comment by jonalmeida** [comment]
@bsurd yes it was, I'm able to follow the STR from the issue and I can see that it is fixed. Can you let me know what STR you are using where it doesn't work?

**Comment by bsurd** [comment]
@jonalmeida Followed the steps in the description, and I can still reproduce this with the latest (5/13 now) build.

Open a custom tab with a video (from mail, vimeo in my case) > play the video > press the device back button to exit the custom tab > video should stop..

If pressing the back button from the custom tab, playback does stop but Fenix also crashes, logged an issue #2447 for this

I would upload a video but cannot find a way to record sound and video at the same time... This way of recording seems to be blocked for now.

**Comment by jonalmeida** [comment]
Ah, I see the issue now: while the a-c feature fixes the issue, Fenix needs to allow the Custom Tabs feature to support `onBackPressed` presses here: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt#L540

I'll add a PR in fenix for it.

Nice catch @bsurd !

**Comment by sv-ohorvath** [comment]
Testing currently blocked by #2447

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 5/23, with Nexus 6P (Android 8.1.0), Huawei Honor 8 (Android 7), and Sony Xperia Z2 tablet (Android 6.0.1).
