### ISSUE TITLE
[Bug] A dotted contour/outline shows up when certain elements are touched

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2184]
## Steps to reproduce
Touch some links on Google.com (or other websites)

### Expected behavior
No contour shows up

### Actual behavior
An ugly contour appears.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1918

This dotted outline it's not helpful by any means, indeed it even disturbs the user experience sometimes.
![20190430](https://user-images.githubusercontent.com/32398857/56997133-1cd02d80-6b7d-11e9-81c8-45f322bcf936.jpg)UNITO-UNDERSCORE!191744!
![Screenshot](https://user-images.githubusercontent.com/32398857/56997141-235ea500-6b7d-11e9-9d9c-a1ac3d129a7f.jpg)UNITO-UNDERSCORE!20190430-172843!UNITO-UNDERSCORE!Firefox Preview!

**Comment by cpeterso** [comment]
This is GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1545499

**Comment by cpeterso** [comment]
Gecko bug 1545499 has been fixed in GV 69 Nightly, but we don't plan to uplift to GV 68 Beta.

**Comment by cpeterso** [comment]
I removed the `Needs GV work` and `blocked` labels because the GV bug has been fixed in GV 69 Nightly. We should retest this bug after Fenix updates to GV 69.

**Comment by ekager** [comment]
We are now on GV69 so let's test this :) Adding QA Needed

**Comment by AndiAJ** [comment]
Hi, fixed for pressing links, on the other hand still happening when pressing the "Go" button from the above mentioned page.
Tested on **Nightly Build #12112106 from 30/7** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video Google Pixel 3a 
![20190731_115738](https://user-images.githubusercontent.com/51314259/62199402-1a53be80-b38c-11e9-9eb4-d0936bf55675.gif)

**Comment by ekager** [comment]
If this is still happening we may need to file a followup bug in GV so let's retest

**Comment by cpeterso** [comment]
The GV bug was fixed in GV 69, so we should confirm this Fenix bug is also fixed.

https://bugzilla.mozilla.org/show_bug.cgi?id=1545499#c15

**Comment by AndiAJ** [comment]
Hi, this is **still reproducible when pressing the "Go" button** on Nightly Build #12621819 from 19/9 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20190920_151320](https://user-images.githubusercontent.com/51314259/65326380-feb1ab00-dbb9-11e9-9403-9633a655de03.gif)

I'll remove the QA needed label until further clarifications.

**Comment by ekager** [comment]
I reopened the Bugzilla bug

**Comment by cpeterso** [comment]
> Hi, this is still reproducible when pressing the "Go" button on Nightly Build #12621819 from 19/9

[Emilio says](https://bugzilla.mozilla.org/show_bug.cgi?id=1545499#c18) the "Go" button outline is a different bug. He fixed the outlines around regular links, but the "Go" button is an actual HTML `<button>` element. That will require a different fix, so I filed a new bug for that:

https://bugzilla.mozilla.org/show_bug.cgi?id=1583381

Chrome doesn't show a dotted button outline, but it does flash a blue highlight box for the same button. Thus fixing this Gecko issue will probably be a very low priority.

**Comment by AndiAJ** [comment]
Hi, reproducible using a Google Pixel 3a XL ( Android 10) when tapping on the "Try again" from the "Address Not Found" page on :
• Beta Build #13112229 from 7/11
• Nightly Build #13120608 from 8/11

► Video
![20191108_101416](https://user-images.githubusercontent.com/51314259/68460730-40052500-0211-11ea-87b7-f4618d33a0ce.gif)

**Comment by finn0** [comment]
@Lululalu, 
> This dotted outline it's not helpful by any means, indeed it even disturbs the user experience sometimes.

I'm strongly disagree with you, it helps us to confirm whether we've clicked at right link. If dotted rectangle isn't correctly aligned around text (or button) that's a different issue, removing it would be very bad idea.

For example, open [this](https://codeforces.com/contest/1336) link in Fenix, and try to click any question which is surrounded by two other question using your thumb; probably you'll end up with clicking on wrong question, and there is no way you know, you've clicked at wrong place unless page isn't opened (indeed here first zoom-in then click on link is a good solution), but this becomes very annoying when I read Editorials, Op-ed Columnists etc in which author usually add link to multiple references in set of words and just one after another; where there is no way which I've clicked (right now I don't have link to the article), unless there isn't a highlight.

Even if we want remove outlined box, we should look for another solution like Chromium based browser have color text with `blue` color.

Let's see what others have to say about it.
/cc @cpeterso @ekager

**Comment by lilydjwg** [comment]
> This dotted outline it's not helpful by any means, indeed it even disturbs the user experience sometimes.

I too miss the outline, because it's a clear indication that I've tapped the link and the page is loading. Without the outline (what I currently get with fenix) I'm puzzled whether I've tapped the link or I've missed and tapped outside the link. I have to look further to the colorful process bar to check that. This is not responsive.

**Comment by kbrosnan** [comment]
bz-1637771 has been fixed closing.
