### ISSUE TITLE
FNX-5522 ⁃ [Bug] Display landscape app menu from bottom

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#2219]
## Steps to reproduce
Go to landscape, open site, open menu

### Expected behavior
I see the bottom area of the menu to navigate back or reload

### Actual behavior
I don't see the back/reload options and have to scroll down to get to it

**Comment by sblatz** [comment]
This is another [a-c dependent issue](https://github.com/mozilla-mobile/android-components/issues/3211)

@vesta0, @bifleming

**Comment by softvision-miralobontiu** [comment]
This is not fixed yet, the menu is displayed from the top.
Tested with the latest build 1.0.1924 (#11620622), on Motorola Nexus 6 (Android 7.1.1), OnePlus 5T (Android 9), and Samsung Galaxy S8 (Android 9).

![landascape](https://user-images.githubusercontent.com/40694158/59268998-9e27df00-8c56-11e9-9ce3-235bec275d6c.png)

**Comment by sblatz** [comment]
This shouldn't have been moved to QA needed just yet. The fix [just landed](https://github.com/mozilla-mobile/android-components/issues/3211#event-2404292019) this morning. It should be fixed in tomorrow's nightly.

**Comment by Amejia481** [comment]
@sblatz After the new snapshot is available,  there is minimal work to be done in Fenix, before this issue is fixed :)

We need to add:
```kotlin
    override val menuBuilder by lazy { BrowserMenuBuilder(
        items = menuItems,
        endOfMenuAlwaysVisible = true
    ) }
```

To `DefaultToolbarMenu.kt`
https://github.com/mozilla-mobile/fenix/blob/7c37f77cfc0e2ec950540b3b98f4bc9220b836c2/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt#L27

**Comment by sblatz** [comment]
Awesome, I'll make sure to add this. Thanks @Amejia481

**Comment by softvision-miralobontiu** [comment]
This is not fixed yet on Android 5 & 6 devices, on the latest build 1.0.1924 (#11640609).
On Nexus 5 (Android 6.0.1), Huawei P9 Lite (Android 6), and Xiaomi Mi4i (Android 5.0.2) the menu is displayed like this:

![Screenshot_2019-06-13-14-23-07](https://user-images.githubusercontent.com/40694158/59429534-a879e280-8de8-11e9-9870-e7d7d125f09c.png)

On Android > 6 it is fixed. Tested on Google Pixel 3 (Android 9), OnePlus 5T (Android 9), Motorola Nexus 6 (Android 7.1.1), Motorola Moto G6 (Android 8).

**Comment by vesta0** [comment]
I am removing MVP blocker since this is only impacting Android 5 & 6 devices.

**Comment by sblatz** [comment]
This is also only broken in landscape now, too, @vesta0. So definitely doesn't feel like an MVP blocker. That being said @Amejia481 is close to a fix for these issues :) (and it should remain blocked until he makes the appropriate a-c changes)

**Comment by sblatz** [comment]
Looks like @Amejia481 just got this fix merged into A-C. It should be fixed on the nightly!

**Comment by AndiAJ** [comment]
Hi, I'm still able to reproduce this issue on the latest Fenix build (1.0.1926 Build #11780608from 27/6) on the following devices:

#### • Samsung Galaxy J7 (Android 6.0.1)
![SamsungJ7A6 0 1](https://user-images.githubusercontent.com/51314259/60268248-ab9ac580-98f4-11e9-8d42-cbec44361fbf.png)

#### • Sony Xperia Z3 (Android 5.1.1)
![SonyXperiaZ3A5 1 1](https://user-images.githubusercontent.com/51314259/60268257-af2e4c80-98f4-11e9-94c4-6f1711ed375c.png)

Based on this I'll remove the "QA needed" label.

**Comment by Amejia481** [comment]
This change is not part of the snapshot yet.

**Comment by sblatz** [comment]
My bad, I got a little trigger happy with the "QA Needed" label. I will add it this evening when it's in the snapshot :)

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Fenix build (#11790617 from 28/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy J7 (Android 6.0.1) [Picture](https://drive.google.com/file/d/1AZG0LU1jNYMGAFpYerydz664-WIm1dxj/view?usp=sharing)
• Sony Xperia Z3 (Android 5.1.1) [Picture](https://drive.google.com/file/d/1fsOYyzdYLg3uYAySScralnlBbpOU7bFO/view?usp=sharing)
