### ISSUE TITLE
The "Edit" and "Bookmarks" buttons slightly overlap in the 3-dot menu in Greek locale

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22509]
### Steps to reproduce

1. Set the app language to Greek
2. Open any webpage and add to bookmarks
3. Open the 3-dot menu on the same webpage

### Expected behaviour

The buttons are separated in a clear manner

### Actual behaviour

The buttons are overlapping each other

![258136554_244737070915809_1806450447909129897_n](https://user-images.githubusercontent.com/89511597/142651798-1ac68899-dc27-4c7a-8b99-29d7e1de0136.jpg)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1 2021-11-19

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18675)

**Comment by amocirean** [comment]
Hello @mariansima  , thank you for submitting the issue.
I was not able to reproduce it on the latest RC or Nightly
Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?
Also, could you provide a video regarding the issue?

Device Used: Huawei P40 Lite
Android Version: 10

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible.
Tested on the latest Nightly 102.0a1 (2022-05-23) build.
Device used: Google Pixel 4 (Android 12).
The buttons are no longer overlap each other.
Closing the ticket as fixed.

**Comment by bigConifer** [comment]
@SoftVision-LorandJanos @amocirean This bug is not fixed. It's still reproducible on the latest Nightly build 102.0a1 (2022-05-25).

If you just increase the system font size a little bit you will see that the edit button is still overlapping:

<p>
  <img src="https://user-images.githubusercontent.com/64743731/170231094-050c3d4b-cb05-4a64-bead-034bc2e5f068.jpg" width="45%" />
  <img src="https://user-images.githubusercontent.com/64743731/170231335-72df4848-baa4-4d45-a32e-a798a592c11d.jpg" width="45%" /> 
  </br></br>
</p>

A fix would be to clip the overflowing text and display an ellipsis ("...").

**Comment by bigConifer** [comment]
It's a bug in the `BrowserMenuImageTextCheckboxButton` menu item on AC side.

There are already other issues with it. See #24560, https://github.com/mozilla-mobile/android-components/issues/11958.

**Comment by SoftVision-LorandJanos** [comment]
Hi @bigConifer!
You are right, it does reproduce with increased font size, before it was reproduced with default, that's why it seemed fixed.
If you think the fix to the mentioned bug would fix this as well, we can leave it as it is, otherwise, I can reopen it.

**Comment by SoftVision-LorandJanos** [comment]
Reopening the ticket.

**Comment by sryze** [comment]
I noticed a similar issue with Russian language, though the button is not exactly overlapping the menu text there, it's located very close to it (no margin between them).

<img width="260" alt="Screen Shot 2022-10-15 at 05 11 31" src="https://user-images.githubusercontent.com/4525736/195956311-52df8b32-f9bd-4fa6-b408-158d7efe39e4.png">

It seems that the menu width is calculated based on the size of the longest item, so for example in the Ukrainian version it doesn't look as bad because some items have longer text.

**Comment by sryze** [comment]
I opened a PR at android-components repo that should fix the overlapping issue, but It seems that without increasing the max width of BrowserMenu, it will still truncate the checkbox title. Is it a good idea to increase it in dimens.xml from 314dp to 350dp or this can break something?

**Comment by SoftVision-LorandJanos** [comment]
I can still reproduce this on the latest Beta 109.0b3.
Device used: Oppo Find X5 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Beta 110.0b2 build.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812825

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
