### ISSUE TITLE
Long press on the address bar displays only the "Copy" option

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#23863]
### Steps to reproduce

1. Navigate to a site (e.g https://webcompat.com/)
2. Long tap a text from the page and copy it.
3. Long tap the address bar. 
4. Observe available options.

### Expected behaviour

"Copy", "Paste" and "Paste & Go" options are available.

### Actual behaviour

"Copy" is the only option available.

### Device name

Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

### Android version

Android 12, Android 9

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 99.0a1 (🦎 99.0a1-20220220070007)

### Additional information

1. The issue is not reproducible on Chrome (different implementation)
2. The issue is reproducible on any site.
3. If I don't copy the text before the issue does not occur.
![image](https://user-images.githubusercontent.com/12184325/154991862-9e11f226-3184-4a80-b3d2-696fc47eed06.png)

3. This was previously reported here: https://github.com/webcompat/web-bugs/issues/99484

4. Screenshot attached.
![image](https://user-images.githubusercontent.com/12184325/154990632-a1a5e5d0-270c-461c-aca7-7cb00876ac86.png)
![image](https://user-images.githubusercontent.com/12184325/154991395-3afbf708-c41f-4799-9b00-f818e89a185d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19580)

**Comment by mcarare** [comment]
AFAIK the options "Paste" and "Paste & Go" are only available for cases when the text copied to the clipboard is an URL, not plain text. So IMO this is not a bug.

**Comment by g-l-n** [comment]
This is absolutely a bug any other browser will give you the option to paste and then use your search engine of choice. The fact that nightly and regular Firefox too for that matter have the paste and paste and go options available when first installed and then eventually disappear through usage shows that it's an actual bug

**Comment by grigoryk** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/24294

**Comment by softvision-oana-arbuzov** [comment]
I can confirm I have "Copy" and "Paste" options now. 
![image](https://user-images.githubusercontent.com/12184325/161713491-ee308310-a97f-416a-833c-0530d31063c9.png)

Per "Expected results" and according to https://github.com/mozilla-mobile/fenix/pull/24294, "Paste & Go" options should also be available, so this is partially fixed. 

**Tested with:**
Browser / Version: Firefox Nightly 100.0a1 (🦎 100.0a1-20220404093932) 
Operating System: Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

Based on the above this should be reopened.

**Comment by SoftVision-LorandJanos** [comment]
As mentioned above, the "Paste & Go" option should be available, based on #24294.
As this part of the expected result is not yet fixed, I will reopen this ticket.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812826

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
