### ISSUE TITLE
[Bug]: Firefox Android won't fill passwords in apps, only in the browser.

### ISSUE THREAD

**Issue by kehkou** [mozilla-mobile/fenix#24257]
### Steps to reproduce

1. Firefox Android as system password manager
2. Open an app and attempt to log in
3. Firefox prompts to unlock; unlock Firefox
4. Select login username from list on top keyboard row.
5. Username not filled
6. Manually type username and select to fill the password
7. Warning that firefox "cannot authenticate". This happens in _any_ app. Select 'Yes'.
8. Password is not filled; paste option disappears from keyboard
9. Close and reopen keyboard to regain paste option
10. Manually copy and paste password to log into app

### Expected behaviour

Firefox fills the username and password in other apps

### Actual behaviour

Firefox does _not_ fill the username or password; soft-crashes keyboard paste option.

### Device name

Blackview BV6600

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

Latest

### Additional information

This issue happens in all apps when Firefox is set to fill passwords. All relevant settings are enabled. However, Lockwise will still fill passwords when set to fill passwords. Device is already in 'factory condition'.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19832)

**Comment by Theluga** [comment]
I second that! 
Apps that I know do not work with the AutoFill  
Binance, Conect SUS. 
AutoFill in other apps only work when the login is with webview like FGTS app.

**Comment by Mugurell** [comment]
@kehkou The issue about logins not being autofilled after being selected should be fixed in the current Firefox Nightly.
Can you please try that and report back?

**Comment by kehkou** [comment]
It is working with the Allstate and SiriusXM apps now, but does not respond after unlocking Nightly in the Plex apps (Plex, Plexamp, Plex Dash).

**Comment by Mugurell** [comment]
Thank you!
Can reproduce the said issue on Plex.
Also seeing in logs
```
2022-03-18 15:21:55.007 1722-1791/? E/Parcel: Class not found when unmarshalling: mozilla.components.feature.autofill.structure.ParsedStructure
    java.lang.ClassNotFoundException: mozilla.components.feature.autofill.structure.ParsedStructure
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3338)
        at android.os.Parcel.readParcelable(Parcel.java:3272)
        at android.os.Parcel.readValue(Parcel.java:3174)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.Bundle.putAll(Bundle.java:292)
        at android.content.Intent.fillIn(Intent.java:10288)
        at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:315)
        at com.android.server.wm.ActivityTaskManagerService.startActivityIntentSender(ActivityTaskManagerService.java:1222)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1577)
        at android.os.Binder.execTransactInternal(Binder.java:1165)
        at android.os.Binder.execTransact(Binder.java:1134)
```

**Comment by kehkou** [comment]
I also forgot to mention that in the Allstate app, it gave the message "failed to authenticate", but still filled the password correctly after selecting 'yes'.

**Comment by Mugurell** [comment]
> > `Firefox prompts to unlock; unlock Firefox`
> 
> I can't even do this step, with beta or nightly... I see the button but its greyed out and pressing it does nothing :/
> 
> Update: greyed out is only with switfkey has a keyboard, with gboard its not greyed out but still doesn't do anything.

That might be a different bug.
Please open a new ticket in we'd need the following information:
- device and Android version
- firefox version used
- keyboard used
- 3rd party application in which autofill is tried
- logcat for when tapping the "Unlock <Firefox> button> - [steps on how to get logs from device logs](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information) (instead of loggins crashes we'd log what happens when the button is tapped)
- video

**Comment by mike-pt** [comment]
thanks @Mugurell yes it might you're correct I created a new issue with logs and video https://github.com/mozilla-mobile/fenix/issues/24423

**Comment by gomarcus** [comment]
Issue still not fixed 😢

**Comment by mike-pt** [comment]
I was able to get the prompt by add a permision (details in the other ticket) but now I'm have this exact issue :(

**Comment by gomarcus** [comment]
For me the autofill only works when I
1. Select a field
2. Long press and hold field
3. Pressing 3 dots on opening menu
4. Select in context menu search firefox
5. Authenticate
6. Do steps 1-4
7. Done

**Comment by mike-pt** [comment]
This is even more buggy than lockwise, lockwise had similar issues ate times but mostly worked... I getting mixed results, in one case it was even listing the logins in the bottom for selection just after prompt, but most time I have to navigate into other areas (not all apps have this option though).

Also I never see "Search Firefox", I can long press and select "autofill" which sometimes triggers it, but most times I have to do some random navigation go back to login and that works, I wondered if it was just a time thing (like it takes a bit to populate, but It doesn't seem like so, since waiting is not working for me)

And FYI this is in the nightly builds, the stable release still doesn't work at all for me.

Is everyone else also using MIUI? (MI/Redmi/Poco)?

**Comment by kehkou** [comment]
As of April 22, 2022, neither Nightly _nor_ stable will autofill beyond asking for authentication. With this widespread bug and the discontinuation of Lockwise, Mozilla effectively deleted autofill as a Firefox feature (remember the addons?).

This seriously **needs to be escalated to the highest priority** if only because of the fate of Lockwise, otherwise it would be a low priority bug. 

At this point, a crappy and inconsistent Edge 'reader mode' is the only thing that is keeping me from switching to that browser (Firefox, by comparison, has a superb Reader Mode).

**Comment by gomarcus** [comment]
Firefox on Android has actually left its glory days behind. Gone are the days of free choice when installing extensions. Gone are the days of printing a page as a PDF. No more reading aloud without that Pocket garbage. No more source code view. No more DEV tools. And so on and so forth ... 

Who thought it was a good idea to reduce the number of built-in features and at the same time deprive users of the possibility to add missing features through extensions.

Just imagine, one would have to say... I go to Google, Apple or Microsoft to have more freedom.

**Comment by 1human** [comment]
Still wrong！！！

**Comment by Mugurell** [comment]
> It is working with the Allstate (sort of) and SiriusXM apps now, but does not respond after unlocking Nightly in the Plex apps (Plex, Plexamp, Plex Dash).

This particular issue - autofill not working immediately after unlocking should be fixed in today's Nightly.
(I tested with Plex)

**Comment by mike-pt** [comment]
Just tested with plex to in Firefox stable and then nightly, it's working perfect with nighly, get the prompt for fingerprint and the auto fill instatly shows.

Thanks so much for the fix, hope it comes to satble soon

**Comment by 1human** [comment]
> Just tested with plex to in Firefox stable and then nightly, it's working perfect with nighly, get the prompt for fingerprint and the auto fill instatly shows.
> 
> Thanks so much for the fix, hope it comes to satble soon
Sad
The browser will prompt you to unlock with your fingerprint on the keyboard top
But nothing happens when you unlock it
It still can't remember the login information of the app

MI10T pro  A12  
Firefox Nightly

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1379657

**Comment by maximilionus** [comment]
Any progress on this issue 🥲? It's really sad that I can't use Firefox's autofill service at full power on android device.

**Comment by Mugurell** [comment]
@maximilionus This issue should have been resolved based on the reports from https://github.com/mozilla-mobile/fenix/issues/24199 and https://github.com/mozilla-mobile/fenix/issues/23707 with https://github.com/mozilla-mobile/android-components/pull/11893 fixing the report we saw in https://github.com/mozilla-mobile/fenix/issues/24257#issuecomment-1072412944 and I such I will close this issue also.

If this is still an issue for you please add here:
   -  the Firefox version used
   -  the keyboard used
   -  the device used: model and Android version
   -  in which 3rd party application you are trying to autofill?
   -  a video of the exact scenario.
   
and we'll restart the investigation.
