### ISSUE TITLE
FNX3-16349 ⁃ [Bug] Crash in BookmarkFragment

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2474]
* Build: 917399d8971c97e6d9b7c197c30b70ff75d74670
* Device: Pixel 2 (Android 9)

1. From the Library, open a bookmark in a new private tab
1. Tap the 'All Tabs' button on the address bar

(CC @colintheshots @sblatz)

```java
2019-05-14 11:28:30.256 11585-11585/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 11585
    java.lang.IllegalStateException: Fragment BookmarkFragment{b10d5fb (72dbc11f-f8ca-479e-85b1-063963453973) id=0x7f0800e1} did not return a View from onCreateView() or this was called before onCreateView().
        at androidx.fragment.app.Fragment.requireView(Fragment.java:1708)
        at org.mozilla.fenix.library.bookmarks.BookmarkFragment$navigation$2.invoke(BookmarkFragment.kt:62)
        at org.mozilla.fenix.library.bookmarks.BookmarkFragment$navigation$2.invoke(BookmarkFragment.kt:56)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.mozilla.fenix.library.bookmarks.BookmarkFragment.getNavigation(Unknown Source:25)
        at org.mozilla.fenix.library.bookmarks.BookmarkFragment.onDestroy(BookmarkFragment.kt:123)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2873)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1018)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1300)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1871)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1817)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by sblatz** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/2499

**Comment by softvision-miralobontiu** [comment]
Hi,
The crash still reproduces. Tested with Samsung Galaxy S8 (Android 9), HTC Desire 820 (Android 6.0.1), HTC 10 (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by ttxhhh** [comment]
在HUAWEI HONOR 8上也有这个问题（系统为EMUI8.0.0基于Android 8.0.0）

**Comment by softvision-miralobontiu** [comment]
Testing is blocked by #2682.

**Comment by sv-ohorvath** [comment]
This is still reproducing on the 5/22 build, with the same steps.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest build 5/23, with:
- Nexus 6P (Android 8.1.0),
- Sony Xperia Z2 tablet (Android 6.0.1),
- Huawei P9 Lite (Android 6),
- OnePlus 5T (Android 9),
- HTC Desire 820 (Android 6.0.1).
