### ISSUE TITLE
App menu shows "Sign in to sync" menu item until I tap it, even though I'm already signed in to sync

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#25486]
### Steps to reproduce

1. Log into your FxA Sync in Fenix.
2. Kill Fenix.
3. Launch Fenix.
4. Open the app menu.
5. See "Sign in to sync". I think this is a bug!
6. Tap the "Settings" menu item.
7. See at the top of the Settings screen that you are already signed in.
8. Exit the Settings screen.
9. Open the app menu again.
10. See that the "Sign in to sync" menu item has been replaced with your sync account name. This is the result I expected in step 5 above.

Maybe I am experiencing https://github.com/mozilla-mobile/fenix/issues/24112? But I don't think my account is in a bad authentication state.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20628)

**Comment by gabrielluong** [comment]
We probably have multiple duplicate issues related to this https://github.com/mozilla-mobile/fenix/issues/19657 and an existing PR that was approved but never landed https://github.com/mozilla-mobile/fenix/pull/21488

**Comment by Alexandru2909** [comment]
While investigating this I noticed that in the current implementation of `HomeMenu`, when the `onAuthenticated` callback is invoked, we update the menu builder, thus [dismissing](https://github.com/mozilla-mobile/android-components/blob/d18be7813ece1c2abd837970fad72cd744893ed3/components/browser/menu/src/main/java/mozilla/components/browser/menu/view/MenuButton.kt#L101) the menu, if it is being displayed at that moment. Updating the menu does not also update the `syncItem`, as it is [stored as a class property](https://github.com/mozilla-mobile/fenix/blob/f1e7b49425bf2a419fb7997c0d29739f13f3626e/app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt#L96-L102). 

This behavior is fixed in the contributor's PR, however the menu dismissing is something we may not want to add.

https://user-images.githubusercontent.com/35462038/183077411-a2cb740d-35f8-4149-8b6c-3ec35ac66ccc.mp4

https://user-images.githubusercontent.com/35462038/183077459-395a1512-0a59-49b3-9868-161b8cf582d7.mp4

Since the authentication state takes some time to be updated and notify the observers about it, the `Sign in to sync` item is displayed for a few seconds before the menu is dismissed.

There are several solutions we can apply to avoid this: One would be to avoid displaying the menu for those few seconds, another would be to add another state (auth in progress) until we get an update from the account manager.
Another solution we could use is not dismissing the already displayed menu, allowing the builder to be updated while also keeping the user's menu.

https://user-images.githubusercontent.com/35462038/183080491-460a9a24-2655-4f8e-be8e-dfa4d8be70fc.mp4

**Comment by rocketsroger** [comment]
Confirmed this has been fixed in Nightly.  Closing

**Comment by ckarlof** [comment]
I'm still experiencing this bug in Firefox Nightly 110.a1 (Build #201592213). The STR are the same as originally reported with the added step of disabling network before launching Fenix in step 3 (i.e., I experience this problem most frequently when I have poor network access).

**Comment by cpeterso** [comment]
@rocketsroger This bug is still reproducible in Nightly 110.a1.

**Comment by mavduevskiy** [comment]
Was able to find a quick fix, now need time to make sure it doesn't break anything. Implementations of `HomeMenu` and `ToolbarMenu` are quite different, and I have to make sure it works correctly in both cases.

The issue looks rather simple. The menu items are build upon the screen opening, but the account manager at that point doesn't have the actual state. It takes just a few millisecond for it to get updated usually, but we never update the items in the list. (with the exception of [account error](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt#251), but I have yet to verify that it works for authentication errors).

**Comment by Kate-Galetski** [comment]
Hi
So we had a conversation with @Mike Avduevskiy @Verdi @ewachowiak and decided on this:

1. Short term: add a new state for when the status is unknown/being checked. Text is: “Account info”
2. Longer term: Look at how to use the last known status (cahce)

**Comment by mavduevskiy** [comment]
The long term solution is caching the profile. A-S will provide us with the API to always get a cached profile ([ticket](https://github.com/mozilla/application-services/issues/5328)), then we have to support it on the A-C and fenix side.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 111.0a1 (2023-01-26) build.
The "Sign in to sync" menu item has been replaced with your sync account name on first time accessing the menu after logged in and closing-opening the app.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
