### ISSUE TITLE
block location permission request is not persisted in private tab

### ISSUE THREAD

**Issue by JustinWebDev** [mozilla-mobile/fenix#26470]
### Steps to reproduce

1) open a private tab
2) browse to ihop.com
3) when Fx prompts to allow the site to use your location, check the box for "Remember decision for this site", tap "Don't allow"
4) browse to another page on ihop.com, like order or menu

### Expected behaviour

The user is not prompted again for location permission.

### Actual behaviour

The user is prompted again for location permission.

### Device name

Samsung SM-T280 tablet

### Android version

5.1.1

### Firefox release type

Firefox

### Firefox version

103.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21301)

**Comment by amocirean** [comment]
Hello @JustinWebDev  , thank you for submitting the issue.
I was able to reproduce it on Nightly 105.0a1.

Devices Used: Huawei P40 Lite (Android 10), Samsung Galaxy A32 5G (Android 11), Google Pixel 6 (Android 13).

**Comment by amedyne** [comment]
@kbrosnan This looks related to this: https://bugzilla.mozilla.org/show_bug.cgi?id=1746031. What do you think?

**Comment by jonalmeida** [comment]
This should have been fixed with https://github.com/mozilla-mobile/firefox-android/pull/156.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 111.0a1 (2023-01-31) build.
Device used: Oppo Find X5 (Android 12).
Removing the QA needed label.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814188

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
