### ISSUE TITLE
Camera permission flow do not handle : `Ask Every Time` permission

### ISSUE THREAD

**Issue by Timshel** [mozilla-mobile/fenix#27177]
### Steps to reproduce

1. On android 11 or later
2. Go the address bar
3. Use the scanner feature
4. When the permission prompt open select : Only this time
5. Close the application
6. Force it to stop (Long press on icon / Info / Force stop)
7. Reopen and select the scanner feature again

### Expected behaviour

The permission prompt should open and allow to grant the permission.

### Actual behaviour

Another dialog window open which prompt the user to grant the permission. It offers two actions : ignore or bring the user to the application settings.
But when going to the application settings the camera permission appear correctly as  `Ask every time`.

### Device name

Google Pixel 4a (5G) on CalyxOS

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

105.1.0 

### Additional information

First some of the label I'm quoting might be wrong since I'm running in French on my phone sorry ^^.

As mentioned, I believe the `Ask every time` option appeared with Android 11 ([Source](https://support.google.com/android/answer/9431959?hl=en))

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21674)

**Comment by Timshel** [comment]
Additionally I built a custom version removing the different [checks](https://github.com/mozilla-mobile/fenix/commit/3a4e2984ccfc5ddae9bdd72f5b8316237a051ae2) and letting the qrCode component trigger the permission prompt.

The issue with this solution is if the user deny the permission twice in a row then the prompt will not appear anymore (https://developer.android.com/about/versions/11/privacy/permissions#dialog-visibility). 
With a combination of a settings to count successive denial and `shouldShowRequestPermissionRationale` it should be possible to display the dialog to change permission only when the permission prompt was not offered.

I did not test on an older android version but will wait for some feeedback before looking at it more.

**Comment by AdinaPetridean** [comment]
I reproduced a crash related to "Camera permission - Ask every time" on Firefox Beta 106.0b3 with OnePlus 9 Pro (Android 12) and Xperia 10 (Android 12)with the following steps:

**Prerequisites:** Make sure the Android Camera permission is set to “Allow only when using the app".

**Steps** to reproduce:
1. Launch the Firefox application.
2. Go to Settings - Account - Synchronize and save your data.
3. Tap "Ready to Scan"
4. Put the app in the background and go back to the Android Camera permission.
5. Select "Ask every time"
6. Bring the Firefox app to the foreground and notice "Allow Firefox Beta to take photos and record video"
7. Wait about 10 seconds. Note the crash.

Please check the video attached.


https://user-images.githubusercontent.com/108326843/193288140-62011d7a-51ef-4c80-9e17-08c175fd7371.mp4

**Comment by Mugurell** [comment]
Regarding the steps described in the original comment it seems like the scenario of
- changing camera permission to "Ask every time" in Android settings
- showing "Camera access needed" popup dialog when trying to access again the camera 

is the expected scenario following https://github.com/mozilla-mobile/fenix/issues/14239 and https://github.com/mozilla-mobile/fenix/pull/15097.

**Comment by Timshel** [comment]
I see no mention of the `Ask every Time` setting in #14239 (Note the issue was created before the release Android 11, released September 8  2020, which introduce the feature and one of the dev mention working on Android 10).

Looking at one of the last comment :
> Our contacts at Google suggested that we need to reserve sending a user to the app settings until the app has detected that the 'Always deny' option has been selected.

Which is not the case here since the permission is set to `Ask every time` not 'Always deny' .

In #15097 there is mention of : 

>4. Ask for permission every time
    Result: Show popup dialog

Which I believe is the core of the issue, in the [android doc I Iinked](https://support.google.com/android/answer/9431959?hl=en)  it is mentioned :

> Ask every time: Every time you open the app, it'll ask to use the permission. It can use the permission until you’re done with the app.

Which is not was is done since the `Camera access needed` popup is to change the permission itself not to grant it.

With the current scenario it ignore the choice made by the user when he either selected  `Only this time` or changed the permission to `Ask every time`.  Opening the `Camera access needed` dialog force the user to change the permission which is not what the user want and I don't believe it's the behavior recommended by the comment I mentioned from #14239 or the android doc I linked.

**Comment by Timshel** [comment]
I see you edited your comment and added : 

> Agree we can improve on that though, avoid persisting ourselves the permission status and only show that popup dialog when the permission is denied and the app feature can't work without it.

Does it means that what I tested ([cf](https://github.com/mozilla-mobile/fenix/commit/3a4e2984ccfc5ddae9bdd72f5b8316237a051ae2)) might be interesting or do you envision something else ?

**Comment by Mugurell** [comment]
> I see you edited your comment and added :
> 
> > Agree we can improve on that though, avoid persisting ourselves the permission status and only show that popup dialog when the permission is denied and the app feature can't work without it.
> 
> Does it means that what I tested ([cf](https://github.com/mozilla-mobile/fenix/commit/3a4e2984ccfc5ddae9bdd72f5b8316237a051ae2)) might be interesting or do you envision something else ?

As Mike said here https://github.com/mozilla-mobile/fenix/issues/27228#issuecomment-1264100044 using flags to reason about the current permissions status is not ideal. 
At a quick glance it seems like we can avoid the `settings().setCameraPermissionNeededState` / `settings().shouldShowCameraPermissionPrompt` calls and persisting the permissions status and only evaluate just in time what the status is and what should we do next:
- pemission granted:
    -> continue with complete app functionality
- permission denied:
    - `shouldShowRequestPermissionRationale` == true
        -> show a rationale (not mandatory)
        -> request the permission
    - `shouldShowRequestPermissionRationale` == false
        -> show the "<permissions> access needed" dialog.
        -> tapping "Cancel" in this dialog will avoid starting the otherwise wanted functionality.

**Comment by Timshel** [comment]
Hum it appears I misused the `shouldShowRequestPermissionRationale` using it after requesting the permission and not before.
I will test it, hoping it will allow to fix the issue I had with the denied twice in a row logic.

**Comment by mavduevskiy** [comment]
>     * pemission granted:
>       -> continue with complete app functionality
> 
>     * permission denied:
>       
>       * `shouldShowRequestPermissionRationale` == true
>         -> show a rationale (not mandatory)
>         -> request the permission
>       * `shouldShowRequestPermissionRationale` == false
>         -> show the " access needed" dialog.
>         -> tapping "Cancel" in this dialog will avoid starting the otherwise wanted functionality.

When the user has selected "ask everytime" option for camera permission,`permission` will be `denied`, not `granted`. That's what's causing the current bug. The user sets `ask every time`, app checks if the permission has been granted – it is not, and it shows the rationel window (Camera access needed) instead of requesting the permission window again.

So keeping the logic like this won't really help us.
```

if (isPermissionGranted(CAMERA)) {
   launchCamera()
} else {
   if (shouldShowRequestPermissionRationale) {
       requestPermission()
   } else {
       showRationel() // the Camera access needed window
   }
}
```
`Ask everytime` will lead to `showRationel()` scenario, but we want `requestPermission()`.

We can't rely on `shouldShowRequestPermissionRationale`. It will be always false, except once check after user has selected `don't allow`. It works like this:

always false -> user selects don't allow permission -> it become true for one check only -> it switches back false again.

So the `requestPermission() ` won't be triggered after `Ask everytime`. It won't also be triggered in [denided-forever](https://developer.android.com/about/versions/11/privacy/permissions#dialog-visibility) case, after the second `don't allow`.

Overall, we have two problems with android11+. First, "ask everytime" is treated like denied. Second, handling `denided-forever` without flags doesn't seem possible. And though not ideal, I fail to see other solutions.

**Comment by Timshel** [comment]
I just did some additional tests.

 - `isPermissionGranted` as mentioned will return true only when the user granted the permission either by setting it with `Always` or after clicking on `Only once` for the runtime of the application.
 - `shouldShowRequestPermissionRationale` will be `true` if the user denied once the permission. If the user deny a second time it will switch back to `false`. 
 
 If the user change the permission to `denied` in the setting then it will count as a first refusal (`shouldShowRequestPermissionRationale` will then return `true`). From my tests the user cannot set the forever denied state.
 
 The main issue is that `isPermissionGranted` and `shouldShowRequestPermissionRationale` will return `false` when : 
  - The user was never asked
  - The user has previously selected `Ask for permission`
  - The permission is denied forever.
  
 Without storing information I have no idea how to differentiate those at the moment. 
But we can identify the transition when the app enter the state denied forever : `shouldShowRequestPermissionRationale` will switch from being `true` before asking to `false` after a second refusal.
 
 I will make a test version to check if it works, additional issues might be compatibility with older version of android.

**Comment by Timshel** [comment]
Ok made a version which is not too bad I think : https://github.com/Timshel/fenix/commit/ca4d53b73b574fd83a60cf80fa4317751d00dce2

The idea is to always ask for the permission and handle the logic around the denied forever state in the `onRequestPermissionsResult`. This way we are sure that we cannot be in a state where we do not prompt the user even if possible because of an external permission state change.

Note for quick testing I reused the `CameraPermissionNeededState` to indicate the denied forever state.

I will try to test it on an old phone running Android 10.

**Comment by Timshel** [comment]
Found a phone running Android 10, from what I tested the handling is quite similar it's just that instead of the denied forever being automatic  the user is presented with an additional `deny  forever` option after declining a permission once.

Still made a small change in https://github.com/mozilla-mobile/fenix/commit/b581f1ce2a73634927917c867b6724ceb34b0002 (using `wasBlocked`) to better handle the cases when the user change the setting himself and prevent displaying the dialog when the user just refused the permission.

On android 10 there is still a scenario where the user will see the permission prompt and after refusing will be presented with the change permission dialog if : 
 - After refusing once the permission the user activate the `Denied forever` option
 - Then the user change the permission switching to `allowed` then back to `deny` (From the OS pov we are back to denied once state)
 - When prompt again click the  `Denied forever`
 - The permission change dialog will then appear since we had memorized that we were already in the `Denied forever` state 
 
 I believe it's an edge case which result in a sub-optimal flow but non blocker ?

**Comment by Mugurell** [comment]
> May be we could fix `Ask for permission every time` for now, and discuss `Denied forever` with the whole team? It's one of those cases where the Android API is quite _imperfect_, and may be flags would be okay.

https://github.com/mozilla-mobile/fenix/pull/27264 should fix the “Ask every time” scenario
The permission denied scenario would remain the only one showing the “Camera access needed” dialog.

But the scenario from https://github.com/mozilla-mobile/fenix/issues/27177#issuecomment-1267039572 still remains a bug, it stemming from us having another permission level (and persistance) on top of Android's.

**Comment by mavduevskiy** [comment]
@Mugurell 
Tested the [#27264](https://github.com/mozilla-mobile/fenix/pull/27264) patch, it still fails the original bug scenario on this issue: 

```
    On android 11 or later
    Go the address bar
    Use the scanner feature
    When the permission prompt open select : Only this time
    Close the application
    Force it to stop (Long press on icon / Info / Force stop)
    Reopen and select the scanner feature again
```

Here is the video with changes from [AC](https://github.com/mozilla-mobile/android-components/pull/12883):
[device-2022-10-04-113422.webm](https://user-images.githubusercontent.com/92760693/193900669-0a4c854a-8b61-4e18-a53e-88d2726bb6e7.webm)


The problem is [this](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt#349) line of code. The "ask every time" option will return `isPermissionGranted == false`, and we will show rational instead of requesting the  permission. It is not about user changing permissions in settings, it's about handling "ask every time" scenario.

**Comment by Mugurell** [comment]
> @Mugurell Tested the [#27264](https://github.com/mozilla-mobile/fenix/pull/27264) patch, it still fails the original bug scenario on this issue: ...

https://github.com/mozilla-mobile/fenix/pull/27264 was intended to solve https://github.com/mozilla-mobile/fenix/issues/27228 and the ANR from https://github.com/mozilla-mobile/fenix/issues/27177#issuecomment-1263631497.
The "Camera access needed" dialog can be researched more and fixed in this ticket.

**Comment by mavduevskiy** [comment]
@Timshel 
Hey, thanks for putting so much effort into it!

I checked your patch, it works and it handles the [scenarios](https://github.com/mozilla-mobile/fenix/issues/27177#issuecomment-1266280152)!

**Comment by mavduevskiy** [comment]
@Timshel L
et me check the team would support the flag solution. Generally we try to avoid using additional flags, so if we make an exception here, it should be thoroughly considered. Let me get back to you.

**Comment by Timshel** [comment]
@mavduevskiy I missed your message and worked on the PR ^^
 
 A note on the flag : it replace an existing one and the code will be less dependent on it since it will come into play only when the user deny the permission.
 
 Additionally the logic could be implemented without it but it would mean opening the permission dialog change when we reached the Denied Forever state just after the user refused to grant the permission.

 A bit obnoxious I believe but since it's an edge case it might be acceptable.

**Comment by Timshel** [comment]
@mavduevskiy any feedback on the flag usage ?

**Comment by mavduevskiy** [comment]
@Timshel 
Hey! We discussed a lot, and decided to pass this to the UX team first. It looks like there is a [recommended flow](https://developer.android.com/training/permissions/requesting#workflow_for_requesting_permissions) by google which adds a showing rationale step first before actually requesting permission.

Interestingly enough, the recommended flow doesn't handle the denied forever state, but Chrome actually does handle it well, but fails to handle the "Only this time" use case. My guess they are using flags for it, but who knows.

Anyway, it looks like Firefox doesn't handle the "Only this time" perfectly, but given the overall _complexity_ of the API we handle it as good as others. So, before going to use flags to change the status quo, we would like to revisit the overall permission flow – not only the Camera one.

**Comment by Timshel** [comment]
Ok, I'll still try to insist one last time :).

First I want to mention that from an user point of view especially if he accepts there is almost no change to the UX. So merging this now would not be a case of changing an UX flow to modify it again one month later.

Additionally adding a rationale in this case is probably tricky since here the use case is quite clear : if you want to scan you need the camera; having the correct balance of informative but not to bothersome might take some time.

In the mean time, I believe the change I propose would be a better flow to work from :
 - It fix the current bug
 - Limit dependency to flags since it just rename an existing one and rely less on it which improve resiliency to outside change of permission.
 - I did some additional test and the ``Ask every time` is already supported when using the webcam on a website so it would make things more coherent.

Thank you.

**Comment by Timshel** [comment]
@mavduevskiy Hey, any feedback from the UX team ?

**Comment by Timshel** [comment]
Happy new year :).
Any news ^^ ?

**Comment by mavduevskiy** [comment]
Happy new year!

Sadly, no, the UX team has a lot on their plate, and since it's not a critical/blocking bug, it's not on the top of their priority list. The related issue is [this](https://github.com/mozilla-mobile/fenix/issues/28110) one.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815638

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
