### ISSUE TITLE
[Bug]: Status bar hidden

### ISSUE THREAD

**Issue by pigsonthewing** [mozilla-mobile/fenix#27731]
### Steps to reproduce

View any web page in Firefox Android app

### Expected behaviour

Status bar  (at top of screen by default) should remain visible

### Actual behaviour

Status bar is hidden

### Device name

OnePlus Nord

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

106.1.0 

### Additional information

![2022-11-06 11 37 23](https://user-images.githubusercontent.com/89541/200170722-4b530fd9-09f3-4ad6-8af8-fb44b715d986.jpg)
![2022-11-06 11 36 28](https://user-images.githubusercontent.com/89541/200170724-e93c276e-364e-4a29-b476-078cb0e7ed93.jpg)

Compare Firefox and Chrome (the latter displays status bar, with time 11:37 and battery 47%)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21941)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21941

**Comment by fice-t** [comment]
This should already be fixed in the next release. Would you be willing to try Firefox Beta from the Play Store to see if you can reproduce this issue on that version?

**Comment by AdinaPetridean** [comment]
@pigsonthewing thank you for your report! The issue is still reproducible on: Firefox 106.1.0 with Motorola Moto g ( 9 plus) - Android 11.
Not reproducible on Firefox Nightly 108.0a1- 7/11

**Comment by kbrosnan** [comment]
If it is not reproducable on nightly then the issue should be closed as works for me.
