### ISSUE TITLE
[Bug]: GPS not working in LineageOS 19.1

### ISSUE THREAD

**Issue by HelloGenericUser** [mozilla-mobile/fenix#27739]
### Steps to reproduce

Hello all, 

Under Lineage OS v19.1 for Pixel 3a, no OpenGapp or alt installed. Firefox installed via the APK found on Fenix site. 

For Firefox Android v106.1, location is enabled for Firefox under App permission

when you allow the website to access GPS within Firefox
eg Google Maps, you will see the green dot on the top right of the phone like it is using GPS for around 3 -4 seconds and then it will vanish. Within Firefox it will just keep spinning like trying to get location.

It does not matter which site you use, other website does the same. 

However if you use the default browser within LineageOS, the GPS works fine with Google maps and others. 

### Expected behaviour

The GPS should work on Google or Bing maps. 

### Actual behaviour

Can not acquire GPS location

### Device name

Google Pixel 3a

### Android version

Lineage OS 19.1

### Firefox release type

Firefox

### Firefox version

103.1

**Comment by cpeterso** [comment]
@HelloGenericUser Can you please retest this bug with Fenix 107? We fixed some geolocation bugs in Fenix 103 ([bug 1771229](https://bugzilla.mozilla.org/show_bug.cgi?id=1771229)) and 106 ([bug 1765835](https://bugzilla.mozilla.org/show_bug.cgi?id=1765835)). So this bug might be fixed in 107 or it might have been a regression caused by the geolocation changes in 103.

**Comment by HelloGenericUser** [comment]
Hi. I have updated to Fenix 107.1 and latest version of Lineage OS. It
still does not function. The GPS indicator will go green for a few seconds
on top right and then disappear, while the acq location hourglass keep
spinning in google or bing maps.

On Thursday, November 17, 2022, Chris Peterson ***@***.***>
wrote:
> @HelloGenericUser Can you please retest this bug with Fenix 107? We fixed
some geolocation bugs in Fenix 103 (bug 1771229) and 106 (bug 1765835). So
this bug might be fixed in 107 or it might have been a regression caused by
the geolocation changes in 103.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci4.googleusercontent.com/proxy/oeXrjG-nDyxspxdyyF_cQ5V51Xh0Ia3I1T5FuQwHnKCv6C-wH7JLdkOtoQDphAd2KHIKPpAEDMuswUDWcQfvGokmTF883OwRBjymkXBzEqSDuV8idPzRZLc981GgygBTEdTkInjvcjMLUVqtHah75OxtnvwyzEtHzYUwujjTHw5G7ASi0JEgYR7HTJvlAwUdZ0ckjF9SzAH9pI04PyUa9fhSxxvDsOqSqru4SJHg_LEqQw1wlw=s0-d-e1-ft#https://github.com/notifications/beacon/A4BPG3XYHATHQKCFAIZMVLDWIZ35LA5CNFSM6AAAAAARY6AJJ6WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSOT4S2Y.gif>Message
ID: ***@***.***>

-- 
~~~~~~~~~~
sincerely,
York

**Comment by cpeterso** [comment]
Thanks for testing. I'll share your new information in the Bugzilla bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1799485
