### ISSUE TITLE
The save button for editing logins is always active

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#27822]
### Steps to reproduce:
- Have at least one login available
- Start editing it

### Expected result:
- The save button is only enabled if all fields are valid and if the details are different

### Actual result:
- The save button is always enabled

### Additional info 
- Issue similar to https://github.com/mozilla-mobile/fenix/issues/21414

https://user-images.githubusercontent.com/11428869/201605586-ba73aa28-d237-4a83-8006-cecc73f6a205.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21980)

**Comment by Mugurell** [comment]
Issue was fixed in https://github.com/mozilla-mobile/fenix/pull/27430.
@ QA please verify.

**Comment by hakeem-gitstart** [comment]
@Mugurell i can confirm that this issue still exist on main.

[editLogin_issue.webm](https://user-images.githubusercontent.com/93866435/215469530-770cf7a3-ab6f-4ba2-aad3-0bb62a9ce2dd.webm)

**Comment by delia-pop** [comment]
Indeed, this is still reproducible on latest Nightly 111.0a1 from 01/30 with Xiaomi 12 Pro (Android 13). Although the problem was fixed in #21414 for the "Add login", for saved login edit the Save button remains active when incorrect credentials are entered.

**Comment by hakeem-gitstart** [comment]
@delia-pop i'll look into fixing this for `Edit Login` and Send a PR soon

**Comment by Mugurell** [comment]
Thank you both!

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814187

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by boek** [comment]
@hakeem-gitstart Please comment on the issue in Bugzilla and I will assign you there :)
