### ISSUE TITLE
FNX3-16595 ⁃ [Bug] App crashes while switching between tabs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2808]
## Steps to reproduce
Switch between multiple tabs quickly while the pages are still loading.
I can reproduce this mostly with an Onion article and a Youtube video.

## Expected
* Tabs switch as expected.

## Actual
* Crash :boom: 

```
      GeckoView  W  No GeckoSession attached to this GeckoView instance. Call setSession to attach a GeckoSession to this instan
                    ce.
     places_ffi  D  bookmarks_get_all_with_url
 AndroidRuntime  D  Shutting down VM
                 E  FATAL EXCEPTION: main
                 E  Process: org.mozilla.fenix.debug, PID: 20973
                 E  java.lang.RuntimeException: Failed to call observer method
                 E      at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
                 E      at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
                 E      at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
                 E      at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserv
                    er.java:36)
                 E      at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
                 E      at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
                 E      at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
                 E      at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
                 E      at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
                 E      at androidx.fragment.app.Fragment.performStart(Fragment.java:2675)
                 E      at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:908)
                 E      at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2087)
                 E      at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1861)
                 E      at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.jav
                    a:1817)
                 E      at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
                 E      at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
                 E      at android.os.Handler.handleCallback(Handler.java:873)
                 E      at android.os.Handler.dispatchMessage(Handler.java:99)
                 E      at android.os.Looper.loop(Looper.java:193)
                 E      at android.app.ActivityThread.main(ActivityThread.java:6718)
                 E      at java.lang.reflect.Method.invoke(Native Method)
                 E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                 E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                 E  Caused by: java.lang.IllegalStateException: Display already acquired
                 E      at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:2181)
                 E      at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:390)
                 E      at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:353)
                 E      at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:84)
                 E      at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineVi
                    ewPresenter.kt:51)
                 E      at mozilla.components.feature.session.EngineViewPresenter.start(EngineViewPresenter.kt:31)
                 E      at mozilla.components.feature.session.SessionFeature.start(SessionFeature.kt:27)
                 E      at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.start$support_base_release(ViewBoundF
                    eatureWrapper.kt:157)
                 E      at mozilla.components.support.base.feature.LifecycleBinding.start(ViewBoundFeatureWrapper.kt:193)
                 E      at java.lang.reflect.Method.invoke(Native Method)
                 E      at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
                 E      ... 22 more

```

* Android device: ?
* Fenix version: ?

**Comment by colintheshots** [comment]
This should be fixed by the other fixes to Display Already Acquired crashes.

**Comment by softvision-miralobontiu** [comment]
This is not fixed yet.
I could reproduce the crash with the latest build 1.0.1923 (#11560607) with Xiaomi Mi 8 Lite (Android 8.1).

![crash](https://user-images.githubusercontent.com/40694158/58955583-11d47280-87a5-11e9-938f-2901c914d7c8.gif)

**Comment by colintheshots** [comment]
@softvision-miralobontiu I cannot reproduce now, so I'll need LogCat to have any chance to fix the issue.

**Comment by colintheshots** [comment]
@softvision-miralobontiu The original bug as reported was fixed. If you can still reproduce with the same STR, please open a new bug with the LogCat stack trace. My guess is it's a content crash on a particular site you're using.

**Comment by softvision-miralobontiu** [comment]
@colintheshots apparently, I cannot reproduce the crash anymore with the latest build 1.0.1923 (#11561806), with Xiaomi Mi 8 Lite (Android 8.1).

**Comment by softvision-miralobontiu** [comment]
@vesta0, the "QA needed" label was set by mistake? I will remove it, but if there is anything else we need to investigate in this issue, please let us know.
Thank you!

**Comment by jonalmeida** [comment]
@softvision-miralobontiu I've updated the STR with Expected/Actual parts to it. Sorry for not following the right format. :)
