### ISSUE TITLE
FNX3-16757 ⁃ [Bug] Visiting a reddit bookmark always shows app popup or launches singular matching app

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#3058]
## Steps to reproduce
Open reddit.
### Expected behavior
Fenix loads reddit.
### Actual behavior
I see this app selection popup. [ekager EDIT: Also, if you only have one Reddit app available on your device, you just get launched to that app without prompt]
![Screenshot_20190531-220449_Android_System](https://user-images.githubusercontent.com/922368/58728824-6b791d80-83f0-11e9-978c-5ace6086d827.png)

I visit various reddit subs from bookmarks several times a day. Seeing that popup every single time is frustrating. The old UX from Fennec was really nice: I saw an android icon in the URL bar and if I wanted to open the link in reddit, I clicked it. 
### Device information

* Android device: 
![Screenshot_20190428-135941_Settings](https://user-images.githubusercontent.com/922368/58728968-c27ef280-83f0-11e9-8d14-babba492acf7.png)

* Fenix version: latest

**Comment by andreicristianpetcu** [comment]
can I disable this feature until this gets adressed? any workarounds?

**Comment by ekager** [comment]
Cc @jhugman is it possible to show the popup only when it's an intent to launch an app, and not just a link that *can* be handled by an external link?

**Comment by pwd-github** [comment]
Isn't this expected behaviour? Though an option to turn it off would be nice.

**Comment by andreicristianpetcu** [comment]
@pwd-github I cannot browse most web sites. How can this be expected? Neither Fennec nor Chrommium have this issue.

**Comment by pwd-github** [comment]
My experience differs from yours completely.

Upon loading Reddit, I'm only asked if I would like the site opened in Reddit once, after which I can navigate around the site without any difficulties or prompts to open the app. 

Perhaps it's because I'm using the latest build of Fenix? I would hope so, otherwise it's looking like a LineageOS bug.

**Comment by andreicristianpetcu** [comment]
@pwd-github It's the only app that does this. Pretty sure it's not a LineageOS bug. Part of the issue got fixed in the latest build.

It works fine when I visit reddit now. If I click to see the reddit thread then I hit back button, I see the popup again. Same with Twitter.

**Comment by pwd-github** [comment]
I'm glad you're seeing an improved user experience with the newest build. It sounds like your current user experience matches mine. I can navigate anywhere within Reddit and not see the prompt to open natively again, it's only when pressing back that I'm instantly promoted to reopen the app upon each page load from my history stack.

**Comment by andreicristianpetcu** [comment]
hmmm... it happens again https://vimeo.com/339843104

It's the only browser that does this. I multitab a lot and visit several reddit subs. I get this with every one.

I have been using Fenix since March, before it had multi tab support. This is the most frustrating bug I ever reported. Please roll back the feature until this gets adressed.

**Comment by sv-ohorvath** [comment]
I think this is an Android 8+ issue only, reproducing on devices like: Nexus 6P (Android 8.1.0), Galaxy S8 (Android 9), Pixel (Android 9). On websites like reddit and youtube (doesn't even matter if I have reddit installed on my device).
Not reproducing on: Sony Xperia Z5 Premium (Android 7.1.1), Nexus 5(Android 6)

**Comment by pwd-github** [comment]
I just tested on the NVIDIA Shield Tablet (Android 7).
1. Opening a new search and attempting to search for Reddit Firefox, Fenix crashed, but that's an issue for another bug).
2. Restarting Fenix and opening the DDG tab, I see the Firefox subreddit as the first result.
3. I tap that and I get Reddit's banner asking me if I want to open in the app or continue. I did not get the system prompt I should've got.
4. Upon pressing reload, I get the system prompt and select Fenix. Fenix reloads the UI and creates a second tab for Reddit.
5. I navigate within the tab and Fenix performs as expected and doesn't invoke the system prompt to open in the  Reddit app or Fenix.
6. Upon pressing back however, I receive the prompt.

So the two issues here are 
1. The intent prompt is inconsistent
2. The intent prompt should be suppressed when navigating backwards through the history stack

**Comment by andreicristianpetcu** [comment]
refresh activates it for me also

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest build 1.0.1923 (#11580610), with Samsung Galaxy Tab A6 (Android 5.1.1), and Samsung Galaxy S8 (Android 9).
I observed similar behavior for youtube.com, so I filed #3256.

**Comment by andreicristianpetcu** [comment]
I took the latest build from 7 hours ago and I still see the issue https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly/latest

@softvision-miralobontiu

**Comment by pwd-github** [comment]
This is working properly for me in 1.0.1923 (Build #11570616 🦎 68.0-20190604110028)

I'm able to navigate Reddit backwards and forwards without seeing the prompt at all, lest I press the open in app buttons.

**Comment by andreicristianpetcu** [comment]
my build is 1.0.1923 (Build #11580611 🦎68.0-20190604110028)

**Comment by softvision-miralobontiu** [comment]
@andreicristianpetcu you're right!
I was able to reproduce this with OnePlus 5T (Android 9), with the latest 1.0.1923 (#11580610).
I will reopen it.

**Comment by jhugman** [comment]
@softvision-miralobontiu are the Steps to Reproduce still the same?

**Comment by softvision-miralobontiu** [comment]
@jhugman yes

**Comment by andreicristianpetcu** [comment]
Latest build shows 2 or 4 popups on twitter :(

**Comment by andreicristianpetcu** [comment]
this is fixed now. tested with reddit, twitter and youtube
