### ISSUE TITLE
Opening youtube.com displays app popup or launches singular matching app

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3256]
## Steps to reproduce
1. Open youtube.com.

### Expected behavior
youtube.com is loaded, without any popups or matching apps launched.

### Actual behavior
On Android >= 6, youtube app is launched. If the device's back button is tapped twice, the user is returned to the opened tab.
On Android < 6, a popup is displayed. Tapping outside the popup dismisses the popup.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), Samsung Galaxy S8 (Android 9), Huawei P9 Lite (Android 6), Sony Xperia Z5 Premium (Android 7.1.1), Motorola Moto G6 (Android 8.1)
* Fenix version: 1.0.1923 (#11580610)

![youtube](https://user-images.githubusercontent.com/40694158/59102049-93f2a180-8933-11e9-81e2-525a2decdfbb.gif)UNITO-UNDERSCORE!android5!

**Comment by pwd-github** [comment]
YouTube doesn't offer to open the app at all for me.

**Comment by softvision-miralobontiu** [comment]
@pwd-github, here is the behavior on OnePlus 5T (Android 9):

![yt](https://user-images.githubusercontent.com/40694158/59108399-73324800-8943-11e9-861b-9cd64ad148b3.gif)

**Comment by pwd-github** [comment]
I'm going to wait for the newest build as that's aeons away from my user experience.

**Comment by sblatz** [comment]
(As seen in #3250 this also affects Wikipedia)

**Comment by jhugman** [comment]
Looking at the video, this should be fixed by [ac#3291][https://github.com/mozilla-mobile/android-components/issues/3291].

**Comment by cpeterso** [comment]
> Looking at the video, this should be fixed by ac#3291.

If this bug is fixed by ac#3291, then we can remove the "Needs GV work" label.

**Comment by softvision-miralobontiu** [comment]
This issue is not fixed on the latest build 1.0.1924 (#11620622), on Motorola Nexus 6 (Android 7.1.1), and Samsung Galaxy Tab A 6 (Android 5.1.1).

**Comment by softvision-miralobontiu** [comment]
maps.google.com has the same behavior on the 6/11 build, on Huawei MediaPad M2 (Android 5.1.1), and Google Pixel (Android 9).

**Comment by andreicristianpetcu** [comment]
this is fixed for me. please re test

**Comment by vesta0** [comment]
Let's re-test when the [Android Intent](https://github.com/mozilla-mobile/fenix/projects/19#card-23601803) work is done.

**Comment by softvision-miralobontiu** [comment]
This is fixed on the latest Nightly build 11/21.
