### ISSUE TITLE
FNX3-16904 ⁃ [Bug] Undo Snackbar with multiple deletions is Wonky (again)

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#3275]
Seems to be related to https://github.com/mozilla-mobile/fenix/pull/3191
Talked to @sblatz and we will investigate next week

## Steps to reproduce
1. Close multiple tabs on home screen 

### Expected behavior
Smooth executed pending delete jobs

### Actual behavior
Tabs are reappearing/not deleting/swiping strangely

### Device information
* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
@vesta0 @bifleming I think this should be an MVP Blocker.

**Comment by sblatz** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/3324#event-2404741054

**Comment by sv-ohorvath** [comment]
There are still some tabs being displayed again after removal: Nexus 5 (Android 6.0.1), Galaxy Tab S3 (Android 8):
![20190612_144030](https://user-images.githubusercontent.com/4037709/59348739-92085400-8d20-11e9-8bd3-7d8c4379e4e6.gif)

Can't reproduce on a Samsung Note 8 (Android 9).

**Comment by sblatz** [comment]
@sv-ohorvath Emily and I paired on this and think we found perfect STR:

1. Open tabs from a collection
2. Before some tab **titles** are loaded, close ANY tab (with swipe or the "x")


Then it will do the behavior you showed above. We fixed believe we fixed this in #3393! 😄

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1924 (#11640609) with Nexus 5 (Android 6).

**Comment by sv-ohorvath** [comment]
@sblatz I saw an issue still reproducing, but my comment didn't make it for some reason...
Open tabs from a collection.
Close one, 2 tabs individually.
The tap close all tabs.
![20190613_155341](https://user-images.githubusercontent.com/4037709/59445110-b559fe80-8e07-11e9-8e4b-95f41e87bdb5.gif)

I'll file a new issue, so this one can rest :))

**Comment by sblatz** [comment]
@sv-ohorvath that can be tracked in this ticket. re-opening.

**Comment by LaurentiuApahideanSV** [comment]
I have verified the issue using on a Samsung Galaxy Tab A (Android 7.0) on the latest Firefox Preview 1.0.1924 (Build #11650657) 6/14 and the issue no longer occurs.

**Comment by sblatz** [comment]
Moving this back to QA needed since we did a bit of a refactor.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1,0,1925 (#11701806), with HTC 10 (Android 8), Samsung Galaxy Note 8 (Android 9), Samsung Galaxy Tab S3 (Android 8), and Xiaomi MiPad 2 (Android 5.1).
