### ISSUE TITLE
Can't download any video file [webm, mov, mp4, etc]

### ISSUE THREAD

**Issue by 1known** [mozilla-mobile/fenix#3703]
With either Firefox preview or Firefox Focus, no video file can be downloaded from websites. Webp, jpeg, and mostly other files along with music files can be straight forward downloaded. Video files cannot. 

When clicking a video on firefox for android, the option to download it shows up.

On Focus and Firefox preview, the long press button doesn't even open on any media content that isn't an image or music. 

Huawei P smart 2018 and Galaxy s8

Fenix: 1.0.1926

**Comment by NotWoods** [comment]
Filed mozilla-mobile/android-components#4021

**Comment by francoism90** [comment]
Any news on this? Firefox Nightly has been upgraded yesterday and previously it did support this.

**Comment by rocketsroger** [comment]
@1known issue was fixed with https://github.com/mozilla-mobile/android-components/issues/4021.  I've confirmed nightly have this fix.  Can you please confirm the fix is working as expected?  Long press on the video you should see "Save file to device" option.  Thanks,

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 3/4 with Sony Xperia Z5 Premium (Android 7.1.1), and OnePlus 5T (Android 9).
Tested on https://standaloneinstaller.com/blog/big-list-of-sample-videos-for-testers-124.html and https://file-examples.com. I was able to download and view the following video formats: 3gp, avi, mp4, flv, m4v, mkv, move. ogg.

**Comment by francoism90** [comment]
On what version should this be fixed? I've tested with the latest update in the Play Store (NL) yesterday and it still doesn't play direct videos in the external app, i.e. https://example.com/video.mp4 -> still direct downloads, current FF opens direct in app.

Is this the same ticket or didn't I understand this one? :)

**Comment by rocketsroger** [comment]
> Is this the same ticket or didn't I understand this one? :)

This ticket is the opposite problem.  This is so the user can long press on the video that is currently playing in the browser to download it.  If you open an issue with actual vs expected behaviour, I can investigate.

**Comment by francoism90** [comment]
@rocketsroger Thanks, I've opened an issue, hopefully this isn't a duplicate: https://github.com/mozilla-mobile/fenix/issues/9760
