### ISSUE TITLE
[Bug] "Firefox Account" text is displayed, instead of the email

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4019]
## Steps to reproduce
1. Go to Turn on Sync.
2. Sign in (it doesn't matter if it is through QR code or email).
3. Observe the FxA account section.

### Expected behavior
The email account should be displayed.

### Actual behavior
"Firefox Account" text is displayed, instead of the email of the account.

### Device information
* Android device: all
* Fenix version: Nightly build 190712 (#11930609)

![20190712_Trim_1](https://user-images.githubusercontent.com/40694158/61116726-acf3f280-a49d-11e9-83b3-d7f247477191.gif)

**Comment by vesta0** [comment]
I believe this has been fixed. @softvision-miralobontiu would you please confirm?

**Comment by softvision-miralobontiu** [comment]
It is not fixed yet on the latest Nightly build 190717 (#11980613) with Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), and HTC 10 (Android 8), and on the latest Nightly build 190717 (#11980614) (aarch64) with Nexus 6P (Android 8.1.0).

**Comment by AndiAJ** [comment]
Still reproducible on 1.1.0-rc.1 using a HUAWEI MediaPad M3 Lite 10.

**Comment by liuche** [comment]
Closing as a dupe of #2021.
