### ISSUE TITLE
[Bug] Certain favicons not loading

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4090]
Many favicons fall to load in Fenix (in search, home screen, and bookmarks/history)
Examples include:
- Twitter
- [Addons.mozilla.org](https://github.com/mozilla-mobile/fenix/issues/3140)

Potentially related: https://github.com/mozilla-mobile/fenix/issues/2925

**Comment by NotWoods** [comment]
This is likely caused by browser-icons throwing away icons if they are too big or small.

**Comment by liuche** [comment]
Can be fixed in AC.

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/android-components/issues/3294

**Comment by NotWoods** [comment]
Twitter and other sites with large icons has been fixed by mozilla-mobile/android-components#3619. 

Small icons is still under consideration or dropped: mozilla-mobile/android-components#3814

**Comment by sblatz** [comment]
Thanks @NotWoods!!

**Comment by softvision-miralobontiu** [comment]
Verified that twitter.com and other sites with large icons are fixed (reddit.com, amazon.com, linkedin.com, facebook.com) on the latest build of RC 1.2.0-rc.2 with Huawei P9 Lite (Android 6), and Motorola Moto G6 (Android 8).

**Comment by klint** [comment]
Favicon of https://showrss.info still does not load with latest nightly.
Same for http://radiooooo.com/
Shall I open a new bug or reuse this one? Thanks

**Comment by NotWoods** [comment]
For the time being, this is intended behaviour because they don't supply any icons larger than 16x16. 

See mozilla-mobile/android-components#3814 for small icon support.

**Comment by klint** [comment]
Hi again
The favicons for following sites are not handled by Fenix, although they seem to be 32x32 this time :)
https://www.labanquepostale.fr
https://www.lemonde.fr
Thanks
