### ISSUE TITLE
[Bug]Vimeo Cookie policy banner can't be dismissed

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4147]
## Steps to reproduce
1. Navigate to Vimeo.com
2. Search for a video
3. Tap the close sign from the Cookie policy banner
![rsz_screenshot_20190718-1538300000](https://user-images.githubusercontent.com/51314259/61458156-87218e80-a972-11e9-99c9-5897202d489d.png)

### Expected behavior
Cookie policy banner can be dismissed anytime

### Actual behavior
The Cookie policy banner can't can be dismissed while searching for a video, it works only on the Vimeo homepage

### Device information

* Android device:
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)   

* Fenix version:  Nightly Build #11990109 from 18/7

### Notes

► Video from Googe Pixel 3a
![20190718_150723](https://user-images.githubusercontent.com/51314259/61458544-76254d00-a973-11e9-934c-f736ebba12d3.gif)

**Comment by cpeterso** [comment]
I don't see the cookie banner. Does it only show for users in the EU?

Can you reproduce this bug in Fennec, Focus, and R-B? I wonder if this problem is related to Fenix's (and R-B's) bottom address bar.

Perhaps this is the same problem as this Instagram "use the app" banner bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1542381

**Comment by cpeterso** [comment]
@AndiAJ - Can you still reproduce this problem with the latest Fenix Nightly?

I don't see the Vimeo cookie banner. Does it only show for users in the EU? I live in the US.

Can you reproduce this bug in Fennec, Focus (with GeckoView), or Reference Browser? I wonder if this problem is related to bottom address bar in Fenix and Reference Browser.

**Comment by cpeterso** [comment]
For comparison, how easily can you dismiss the cookie banner in Chrome?

**Comment by AndiAJ** [comment]
Hi @cpeterso  , yes this is still reproducible on both Fenix Nightly Build #12941812 as well as on Chrome using a Google Pixel 3a (Android 9) phone when trying to dismiss the banner after searching for a video.

► Video Fenix
![20191027_093329](https://user-images.githubusercontent.com/51314259/67283300-18f1e800-f4dc-11e9-995c-16cdc2302733.gif)

► Video Chrome
![20191027_093440](https://user-images.githubusercontent.com/51314259/67283377-3b840100-f4dc-11e9-9218-8a1dd3adfacc.gif)

On the other hand in both cases the banner can be dismissed without any problems from Vimeos homepage. 

► Video Fenix 
![20191027_093553](https://user-images.githubusercontent.com/51314259/67283541-89990480-f4dc-11e9-9e18-dfc0cfecf061.gif)

► Video Chrome
![20191027_093633](https://user-images.githubusercontent.com/51314259/67283615-ab928700-f4dc-11e9-967a-200b5abccb99.gif)

Not sure about the banner, I recall that after reporting a Netflix banner issue, @ekager also told me that she can't see the banner.

**Comment by cpeterso** [comment]
Thanks for the screen captures. They're a big help.

Interesting that the cookie banner can be closed on the home page but not the search page.

Since Chrome exhibits the same behavior as Fenix, I don't think there is anything for us to fix here. I will ask our WebCompat team about contacting someone at Vimeo (and Instagram for [bug 1542381](https://bugzilla.mozilla.org/show_bug.cgi?id=1542381)).

**Comment by fluffyemily** [comment]
Current discussion has suggested that this is an issue with Instagram as the banner is also difficult to dismiss in Chrome for Android. A bug has been raised with Instagram to address.

**Comment by AndiAJ** [comment]
Hi, I've just re-checked this matter the latest **`Nightly Build # 20990609 from 4/8`**.

✔️ It seems to be properly working on the following devices:
• Xiaomi Redmi Note 8T (Android 9)
• Nokia 6 (Android 7.1.1)

► Video
![20200408-181229](https://user-images.githubusercontent.com/51314259/78804197-84ffd400-79c8-11ea-9953-e27edc1c6f78.gif)

❓ On the other hand, **when tapping the close button the video that's in the background gets opened**.
Only after the user goes back to the previous page (Vimeo video search) the banner can be dismissed.
Bumped in this issue on the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus 6T (Android 9)
• OnePlus A3 (Android 6.0.1) 

► Video
![20200408-182851](https://user-images.githubusercontent.com/51314259/78804850-55050080-79c9-11ea-98c2-c84c2346c705.gif)

@boek & @fluffyemily  - Please review and share your thoughts. ☺️ 

I'll remove the QA needed label until further notice.

**Comment by ekager** [comment]
Closing because the Bugzilla was resolved

**Comment by AndiAJ** [comment]
It's **still reproducible** on the latest **`Nightly 201217`** using the following devices:
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment]
Still reproducible on 85.1.3 using a OnePlus A3 (Android 6.0.1)
