### ISSUE TITLE
[Bug]  Text input problems: cursor jumps around, spaces are removed, characters are duplicated

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#4208]
## Steps to reproduce
1. find text field
2. start typing a sentence.
### Expected behavior
cursor won't jump, letters will stay in place, spaces won't be removed and parts won't be duplicated
### Actual behavior
all of the above happens :(

### Info
Also reproducible in Firefox Focus with GeckoView
I've noticed that typing incredibly slow avoids the issue. 

### Device information

* Android device: Galaxy S5 (I've also tested on other devices such as a Galaxy S4, Bluestacks 4)
* Fenix version: Nightly 190707 18:02 (Build #11881816)
📦: 3.0.0
🦎: 68.0-20190612114833

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12669)

**Comment by JonO7694** [comment]
interesting... have you tried clearing the apps cache?

**Comment by cadeyrn** [comment]
Which keyboard do you use? Which Android version? And have you tried it with a current Nightly build? Your build is outdated. I can't reproduce with HTC U11 / Android 8.0 / TouchPal keyboard.

**Comment by Poopooracoocoo** [comment]
I've tried it with Samsung Keyboard, Gboard, SwiftKey and Fleksy as well as Google Keyboard (old version of Gboard which is frankly faster). My build *was* outdated and after having updated, I'm still able to repro. Clearing the apps cache did nothing. 

Did you type that comment with your setup you mentioned? @cadeyrn I typed the issue with my setup and it was super painful. I'm typing this comment on a desktop tho.

**Comment by cadeyrn** [comment]
Not that comment but I typed a lot of other comments with my smartphone and without any problems.

Since there are not much more reports like this it looks like not many people are affected. So let's hope that someone from Mozilla can reproduce with one of their devices. :)

**Comment by sblatz** [comment]
@Poopooracoocoo are you able to reproduce in Reference Browser? What about Focus with GV disabled 🤔

**Comment by boek** [comment]
@cpeterso Since this is also happening in Focus it looks like it could be GV related?

**Comment by Poopooracoocoo** [comment]
@sblatz I haven't used ref browser in ages and don't have it anymore. It didn't happen in Focus without GV. @boek I'm pretty sure that this is a GV issue but I wanted to make an issue here as not only would it be seen but I wasn't sure.

**Comment by hakkikaancaliskan** [comment]
Writing is not so slow for me but selecting text with double tap or doing like this thing is a real pain.
Xperia XZ1 Android 9
Nightly 190723 18:04 (Build #12041810)

**Comment by Poopooracoocoo** [comment]
@hakkikaancaliskan I have the same issues with selecting text. Are you sure that your typing is not like what I said above? Which keyboard?

**Comment by hakkikaancaliskan** [comment]
> @hakkikaancaliskan I have the same issues with selecting text. Are you sure that your typing is not like what I said above? Which keyboard?

I'm sure, no problem on typing but editing is painful. Same on Gboard and Swiftkey.

**Comment by cpeterso** [comment]
Since this problem affects Fenix and Focus+GV, I filed a new GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1569007

This definitely sounds like a keyboard or IME problem.

@Poopooracoocoo - Can you reproduce the problem in Firefox 68 for Android? Is this problem reproducible in every web page with a text field?

https://play.google.com/store/apps/details?id=org.mozilla.firefox

**Comment by Poopooracoocoo** [comment]
I'm not sure whether it's a problem in every text field but it certainly happens in GotHub text fields such as username/email, feature request/bug/issues and comments. It doesn't happen in the password field but I'm not typing full sentences in the password field so it's hard to confirm.

I typed that comment on a desktop but retyped it on Fennec 68. I had no issues except for my own spelling errors :P

**Comment by Poopooracoocoo** [comment]
Hooray! I no longer have this issue!

I'm not sure what happened. I still have text selection issues though

**Comment by cpeterso** [comment]
> I still have text selection issues though

Is there a Fenix bug filed for your text selection issues?

**Comment by Poopooracoocoo** [comment]
@cpeterso arfggggggghhhhhhhghhh I'm now having those issues again.

**Comment by cpeterso** [comment]
> @cpeterso arfggggggghhhhhhhghhh I'm now having those issues again. I bet this still happens in Fenix.

OK. I'll reopen the corresponding GeckoView bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1569007#c2

**Comment by cpeterso** [comment]
> @cpeterso arfggggggghhhhhhhghhh I'm now having those issues again in Focus. I bet this still happens in Fenix.

@Poopooracoocoo - Focus has an old version of GeckoView. Can you please check whether the latest Fenix version still works on your device?

**Comment by rekotc** [comment]
> cursor won't jump, letters will stay in place, spaces won't be removed and parts won't be duplicated
I can confirm it happens to me, i have a fairly old phone which might be the culprit, Samsung Galaxy S2 (using LineageOS 14). But the problem doesn't happen in every webpage, i noticed it in particular using twitter.com, every tweet i write is a pain!

> I've noticed that typing incredibly slow avoids the issue.
Same here. It looks like the browser cannot keep up with the typing speed

**Comment by cpeterso** [comment]
@rekotc - Which Fenix version are you testing? Do you also seen this typing problem in Firefox for Android (Fennec 68)?

**Comment by Poopooracoocoo** [comment]
I've noticed that when this happens, the keyboard (Gboard in my case) will not have caught up with the browser (fenix and focus). I think that it's not the keyboards fault and that Fenix/Focus aren't telling the keyboard in time. Back to my point, the keyboard's suggestions will be rather late and sometimes not appear at all. Typing passwords is still normal.

**Comment by rekotc** [comment]
@cpeterso i'm using Firefox Preview 1.4.1 (Build #12531633), i can tweet normally using the regular Firefox 68.1.1

**Comment by cpeterso** [comment]
I've reopened the GeckoView bug for more investigation: https://bugzilla.mozilla.org/show_bug.cgi?id=1569007#c5

**Comment by Waqar144** [comment]
I am having text selection issues as well. 
But no problems with typing / editing so far

**Comment by cpeterso** [comment]
> I am having text selection issues as well.
> But no problems with typing / editing so far

@Waqar144 - Which Firefox Preview version are you using? Are you using Android's default Gboard keyboard?

**Comment by cpeterso** [comment]
This bug is in the GV team's Q4 (November or December) backlog.

**Comment by Waqar144** [comment]
> > I am having text selection issues as well.
> > But no problems with typing / editing so far
> 
> @Waqar144 - Which Firefox Preview version are you using? Are you using Android's default Gboard keyboard?

I am using SwiftKey.
And Firefox version: 2.2.0

PS: I just on the playstore there's a new update, I will install it right away and report back.

**Comment by makotokato** [comment]
> 
> 
> > > I am having text selection issues as well.
> > > But no problems with typing / editing so far
> > 
> > 
> > @Waqar144 - Which Firefox Preview version are you using? Are you using Android's default Gboard keyboard?
> 
> I am using SwiftKey.
> And Firefox version: 2.2.0
> 
> PS: I just saw that on the playstore there's a new update, I will install it right away and report back.
> 
> **Update:** Just checked. Selection is working! Seems good to me. Thanks.

Thanks.  Jump issue might be https://bugzilla.mozilla.org/show_bug.cgi?id=1563640.  And space issue was https://bugzilla.mozilla.org/show_bug.cgi?id=1571375.

**Comment by cpeterso** [comment]
Looks like the text selection problems have been fixed, but we still have reports of typing problems (possibly related to keyboard suggestions causing input event jank?).

@Poopooracoocoo was still able to reproduce typing problems on [September 16 ^](https://github.com/mozilla-mobile/fenix/issues/4208#issuecomment-532053657) and @rekotc on [September 17 ^](https://github.com/mozilla-mobile/fenix/issues/4208#issuecomment-532099425) (in Fenix but not Fennec 68).

**Comment by hakkikaancaliskan** [comment]
> Looks like the text selection problems have been fixed
@cpeterso not fixed :(
<img src="https://user-images.githubusercontent.com/17825767/67520168-ffee6000-f6b0-11e9-8f90-bd7a555da1df.png" width=300>

**Comment by makotokato** [comment]
> > Looks like the text selection problems have been fixed
> 
> @cpeterso not fixed :(

@hakkikaancaliskan Does it mean that toolbox position is invalid? (If so, this may be regression since I cannot reproduce it on non-Fenix Nightly)

**Comment by hakkikaancaliskan** [comment]
You mean non-nightly Fenix?
Yes, there is no problem on

**Comment by cpeterso** [comment]
Adding the GV bug to GV's November sprint because this bug is on Fenix's list of top 10 GV bugs.

https://bugzilla.mozilla.org/show_bug.cgi?id=1569007#c9

**Comment by makotokato** [comment]
@Poopooracoocoo I would like to define this issue cleary since I don't reproduce jump etc (If using arrow key on GBoard, cursor cannot set expected position) on Fenix Nightly.

Although you say https://github.com/mozilla-mobile/fenix/issues/4208#issuecomment-532053657, but no exactly reproduce step.  Do you have reproduce step for this issue?  And I would like to see screencast when this occurs.

**Comment by Poopooracoocoo** [comment]
@makotokato sorry but I have no clear steps on how to repro. Here's a screen recording though.

**Comment by yaomtc** [comment]
I've seen this happen using AOSP Keyboard on LineageOS. I don't know how to trigger the issue, though, and it hasn't happened for a while. If it happens again I'll try to get a screen capture and note when it started happening.

**Comment by makotokato** [comment]
I believe that this is fixed by GeckoView 75.0.  If @yaomtc , what version do you test?

**Comment by makotokato** [comment]
Fenix Nightly on Play store is 20200214 that will have the fix. @Poopooracoocoo, do you know whether this issue still occurs on the latest Fenix Nightly (Firefox Preview Nightly)?

**Comment by yaomtc** [comment]
@makotokato, the latest version on the fenix Github page, which is... 3.2.0.

**Comment by kuba-orlik** [comment]
Tried to reproduce it in the newest version and it seems that the bug is fixed

**Comment by makotokato** [comment]
> @makotokato, the latest version on the fenix Github page, which is... 3.2.0.

3.2.0 uses old version of GeckoView. 3.3.0 (current Fenix Nightly) will be GeckoView 75.

**Comment by ebalazs-sv** [comment]
Hi! I can reproduce this issue on the latest Fenix Nightly 200511 (Build #21320626) with Motorola Moto G6 (Android 8), following the steps:
1. Log in on Fenix and save the credentials;
2. Sign out;
3. Go to Turn on sync and tap "Use email instead";
4. On the Sign in page, tap "Use a different account";
5. Remove the first part of the email address and add a different one;

The characters are added in the opposite order.

Notes:
Not reproducible when deleting the entire email address or when not deleting the first letter.

![20200511_165311](https://user-images.githubusercontent.com/48799384/81570386-34094400-93a9-11ea-8118-a10adfdd63cb.gif)

 I will leave the needs:STR since this is only one of the issues from the description and there might be other steps to reproduce them.

cc @makotokato

**Comment by igalic** [comment]
behaviours i've noticed on github, specifically, where i write most text:

- trying to “quote" a passage from a previous comment on github, i paste it in the text box, and start adding `>`, they appear at the end

- deleting parts of a text (a bug that's prefilled, try to delete what doesn't apply) with the backspace key starts deleting words in front of it

im using

Nightly 200602 06:01 (Build #21540609)
44.0.20200531130125, 2ac91e358
GV: 78.0a1-20200529095426
AS: 0.59.0

on oneplus 5t, Android 10 / OxygenOS 10, with SwiftKey 7.5.5.19

**Comment by igalic** [comment]
and a new one, i just discovered:

- paste text
- select all
- fumble around to hit theqquote button
- the text is now quoted!hurrah!
- add or deleteaa single letter
- result: the entire text is gone.bbooo!

im leaving the "mistakes"inhere,as the browser/the keyboard / thewwebsite are making them, for you to see, and because it's too hard to fix

not least becauseii have so little time.
this isthe reason whyI use my phone to contributeto begin with: i have a small daughter to take care of, and can't just whip out my laptop

**Comment by igalic** [comment]
> and a new one, i just discovered:
> 
>     * paste text
> 
>     * select all
> 
>     * fumble around to hit theqquote button
> 
>     * the text is now quoted!hurrah!
> 
>     * add or deleteaa single letter
> 
>     * result: the entire text is gone.bbooo!
> 
> 
> im leaving the "mistakes"inhere,as the browser/the keyboard / thewwebsite are making them, for you to see, and because it's too hard to fix
> 
> not least becauseii have so little time.
> this isthe reason whyI use my phone to contributeto begin with: i have a small daughter to take care of, and can't just whip out my laptop

after this update:

Nightly 200603 06:00 (Build #21550609)
44.0.20200601130057, 2ac91e358
GV: 78.0a1-20200529095426
AS: 0.59.0

the above no longer happens

**Comment by igalic** [comment]
i didn't think it was possible, but this is bug shows about 10× worse in Gitea's Text input fields than here on github

i should do a screen recording of a review…

**Comment by Poopooracoocoo** [comment]
@igalic Yikes. I thought they had finally fixed this. and hooray! we finally have a great recording of this bug! <3

**Comment by Poopooracoocoo** [comment]
Still having issues in Firefox Nightly.

**Comment by test8421** [comment]
It is still a serious problem in many situations...
With different IME used, the problem occurs sometimes, causing an especially unpleasant inputing experience.
I hope it will be soon adressed completely.

**Comment by Waqar144** [comment]
It is just unbelievable that one year later we are still suffering from this bug. THIS IS BASIC STUFF.

**Comment by ekager** [comment]
Is everyone having issues using SwiftKey? It is helpful if everyone posts their hardware + keyboards being used so we can continue to investigate.

**Comment by ekager** [comment]
cc @makotokato are there open bugs for SwiftKey?

**Comment by Waqar144** [comment]
> Is everyone having issues using SwiftKey? It is helpful if everyone posts their hardware + keyboards being used so we can continue to investigate.

Google Pixel (sailfish) Android 10 with SwiftKey keyboard, running Firefox Beta

**Comment by Poopooracoocoo** [comment]
I'm still using Gboard on various devices, including a Galaxy S8 and Galaxy S5.

**Comment by igalic** [comment]
I'm also seeing this on [The Lounge](https://thelounge.chat/), which i run as Pwhich on mobile presents only a single input line

**Comment by makotokato** [comment]
> cc @makotokato are there open bugs for SwiftKey?

No, I don't know. I need more details to reproduce this.
Also, I will add logging code for GV Nightly, then I would like to look the log after that.

**Comment by wem1c** [comment]
Also having this issue. started a couple of days ago. Seems to happen when trying to insert text into existing strings. The cursor jumps, the letters you type are not letters that get inputed.

Tried both SwiftKey and Gboard, having the same issues with both when using Firefox Nightly for android. (Does not happen in any other app)

Device: Xiaomi Mi 8
Android: 10 QKQ1.190828.002 / MIUI Global 11.0.5 Stable
Firefox Nightly 201020 17:01 (Build #2015770827)

**Comment by Poopooracoocoo** [comment]
this issue will be turning two soon...

**Comment by makotokato** [comment]
GV 83+ issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1672095, I will fix this soon.

**Comment by orionlee** [comment]
Similar issues happened for me on Zooniverse talk pages ([example page](https://www.zooniverse.org/talk/14/5662)) as well.

Behavior:
- Entering text started out okay (at least for short messages I've tried).
- After entering a few more comments, e.g., traversing to different parts of the site and going back to another talk topic, the issue started to pop up, jumping around, preceding characters are duplicated (e.g. if preceding characters are `zo`, typing `o` will result in `zozoo`)
- Reload the page does not resolve the issue.
- The issue is resolved after closing the current tab, and opening a new tab with the old URL. 
- But it will happen again soon afterwards! :-(

Notes:
- the site is loaded by AJAX.
- the site's commenting also has its own auto complete (for auto completing hash tags)

Configuration:
- Gboard, Hacker Keyboard
- Firefox build: Firefox Nightly 20201024 17:01 from Google Play
- Android version: 7.0

**Comment by makotokato** [comment]
@orionlee
https://bugzilla.mozilla.org/show_bug.cgi?id=1672095 has been landed, but we doesn't merge with Fenix Nightly yet.

**Comment by ddarfantasy** [comment]
The problem still exists in some particular senarios, eg:
Move cursor to another position and immediately type space, the space would occur in the original place...

I'm not sure whether you can reproduce it.

**Comment by Waqar144** [comment]
Totally reproducible still. Especially when inserting text on a Gitlab comment text area.

**Comment by hebu** [comment]
I experienced the cursor issues on different web pages, but it does not occur always – so it is hard to reproduce.

- enter some text
- change cursor positon
- enter more text, the cursor us reset to the old position and the text is inserted there
- tap outside the textfield
- now place the cursor to a new position by tapping into the textfield
- enter more text, now the text is inserted in the new position

Other weird stuff happens, when trying to select and replace text...

Fenix version: 87.0.0-rc.1 (Build #2015799099)
Keyboard: GBoard 10.3.05

**Comment by orionlee** [comment]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1672095 has been landed, but we doesn't merge with Fenix Nightly yet.

The use case I encountered (Zooniverse talk pages) is resolved with current Fenix Nightly, with GV version 89.0a1

**Comment by Waqar144** [comment]
@makotokato did it ever land? Is there a possibility that this will be fixed anytime soon?

**Comment by makotokato** [comment]
> @makotokato The use case I encountered (Zooniverse talk pages) is resolved with current Fenix Nightly, with GV version 89.0a1

https://bugzilla.mozilla.org/show_bug.cgi?id=1672095 is already merged on Firefox 84+.  I need exactly reproduce step since I cannot reproduce original issue.

**Comment by igalic** [comment]
i don't understand how you're trying to reproduce this? 

this happens in every text input field which has JavaScript helpers for completion or editing

gitea's default input field is unusable. fortunately, it's on the way out: https://github.com/go-gitea/gitea/pull/15394
you can't use any @-completion or #-completion in TheLounge.

There's public instances of these things, you can just try it out

**Comment by staktrace** [comment]
@makotokato I've seen this issue in the past, and recently have started running into other cases where typing on the keyboard causes the caret to jump somewhere else and then the characters get entered at that new location (which obviously is not where I want them to go). It's not reliably reproducible but happens to me at least once a week, and once it gets into that state it's hard to clear. Are there prefs/logging I can turn on and collect that would help you with this?

**Comment by kevinlyles** [comment]
> @makotokato ... and recently have started running into other cases where typing on the keyboard causes the caret to jump somewhere else and then the characters get entered at that new location (which obviously is not where I want them to go). It's not reliably reproducible but happens to me at least once a week, and once it gets into that state it's hard to clear. Are there prefs/logging I can turn on and collect that would help you with this?

I have also been seeing this over the past month or so.  Today I saw it with the phone number field on https://register.moen.com.

**Comment by orionlee** [comment]
> I have also been seeing this over the past month or so. Today I saw it with the phone number field on https://register.moen.com.

As a data point, the phone number field on https://register.moen.com worked in my setup.
- A recent Firefox Nightly, GBoard or Hacker's keyboard, on a Android 7.0-based tablet.
- I tried filling the field quite a few times in a span of about 10  minutes. It consistently worked.

Firefox Nightly build info:
```
90.0a1 (Build #2015810955)
AC: 90.0.20210516190059, be02514d7
GV: 90.0a1-20210516091748
AS: 76.0.0
```

**Comment by makotokato** [comment]
@staktrace @kevinlyles 
If this issue mostly occurs on Gboard, this will be race condition between setting composition by Gboard and synchronizing internal Gecko text. Gboard sets composing text aggressively. So I am looking for another workaround...

**Comment by kevinlyles** [comment]
I can confirm that I'm using Gboard

**Comment by Mikaka27** [comment]
I'm not using gboard and I see similar issue in my bank's website.
If I'm typing account number the characters are inverted.
So if I type "1234" I may get "1243" or something like that.

This occurs on Samsung Galaxy J7 2017 stock keyboard, and Xiaomi Redmi 6 also stock keyboard.

I'm not sure if this is the same issue.

**Comment by makotokato** [comment]
I hope that some issues will be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1713588.

**Comment by zepfietje** [comment]
I believe this issue has not been fixed yet.

**Comment by ddarfantasy** [comment]
No, the problem certainly hasn't been solved.
It's really a frustrating experience to encounter the issue.
eg. If you type quickly at https://code.cs61a.org/

**Comment by makotokato** [comment]
> No, the problem certainly hasn't been solved. It's really a frustrating experience to encounter the issue. eg. If you type quickly at https://code.cs61a.org/

Your issue is another issue.  I guess that this site uses [Ace editor](https://ace.c9.io/), If you can reproduce https://ace.c9.io/, please tell me about your environment (Your Android version, software keyboard such as GBoard).

**Comment by Poopooracoocoo** [comment]
While I still have a lot of problems with the text entry experience in GeckoView, it's finally acceptable!! It looks like no work has been done here for a while though. Hopefully priorities will change around here. We can't quite close this issue yet. :(

Currently using Gboard on a Samsung Galaxy S20 running Android 11.

I'm so glad that I no longer pull my hair out when writing comments like these. Thanks Makoto. Selection and cursor manipulation is another area that could do with some attention.

**Comment by kbrosnan** [comment]
Makotokato resolved several major issues with cursor placement and text insertion in rich text fields. There may still be some problems but are best addressed as separate bugs reported at https://bugzilla.mozilla.org/enter_bug.cgi?product=Geckoview&component=IME including the website and keyboard that you are using.
