### ISSUE TITLE
Taskcluster job failing due to "createTask" "insufficient scopes"

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#4678]
TC build is marked as red.... in old taskcluster task view, the error shows incorrectly (per the taskcluster team) as "Error: Artifact "public/actions.json" not found at "/opt/fenix/actions.json" error "

However, the issue appears to be " createTask insufficient scopes" per 
https://taskcluster-ui.herokuapp.com/tasks/TEXBpgLkR8WJh9izT73xrQ/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FTEXBpgLkR8WJh9izT73xrQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

happening since commit: 71c48692da36466295c34ae3aef5c439fc7df8c0

cc @rpappalax, @AaronMT

**Comment by rpappalax** [comment]
fixed

**Comment by dragneelfps** [comment]
@rpappalax still getting the error: https://tools.taskcluster.net/groups/RkcUuXWiS1uuyae6h3vBgg
