### ISSUE TITLE
About page stays in session

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#513]
After a user navigates to the about page we are holding on to that session (so they see it when the go back home). We should likely destroy this session when they navigate away.

**Comment by boek** [comment]
This is another good reason to have something like InfoActivity in Fenix :+1:

**Comment by pocmo** [comment]
Yeah, agree. If we want a different behavior then this shouldn't open a `Session`/Tab (in `SessionManager`) at all and instead implement a custom screen.

**Comment by Sdaswani** [comment]
Yes, I encountered this too, a nit but no bueno.

![screenshot_20190220-195918_fenix](https://user-images.githubusercontent.com/4879954/53143822-8bc25200-354e-11e9-9255-55f8c6fd48ae.jpg)

**Comment by topotropic** [comment]
@vesta0 do we have an open ticket on the about page? I couldn't find one and it's not fixed yet. Thanks!

**Comment by vesta0** [comment]
@topotropic can you please clarify what needs to be fixed on the about page other than what's addressed in this ticket?

**Comment by vesta0** [comment]
This is fixed.

**Comment by bsurd** [comment]
This is still reproducible and also freezes/crashes the app.

### STR:
1. Go to any about page.
2. Tap on the back button.

### Expected:
The home page is displayed without any about pages in the session.

### Actual:
Fenix crashes, after you reopen the app the about page is also displayed.

### Notes & information:
* [Logcat](https://github.com/mozilla-mobile/fenix/files/3038433/log.txt)
* [Video](https://drive.google.com/open?id=1fy4q_dX4p7EgvqPgG_51AsXi6p4CluCJ)
* Fenix 1.0.1914 (#10921239)

**Comment by cadeyrn** [comment]
I am pretty sure this issue was about the "About Fenix" page which no longer stays in the session since it has been implemented as an Android Fragment, not about about: pages like about:telemetry. But FWIW I can confirm the freeze/crash with about:telemetry. ;-)

**Comment by sblatz** [comment]
@cadeyrn is correct on this. I will create a follow up ticket to address this other issue!

**Comment by bsurd** [comment]
@cadeyrn Ah yes, you are right, marking as verified as this is fixed.
