### ISSUE TITLE
[Bug] Private custom tabs still record history

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#5592]
Originally filed as #5590 by @joshsleeper

## Steps to reproduce

Turn on "Launch links in private tab", then:

- navigate to another app (Reddit, Google News, etc.) that easily opens links in a custom tab
- open said link in a custom tab
- close the custom tab
- open Firefox Preview proper and navigate to the History section
- see that the link visited in a custom tab was not added to the browsing history

### Expected behavior
No history is saved, since the browsing is in private mode.

### Actual behavior
When I'm browsing a service like Reddit or Google News, I regularly follow links as I scroll through the app that must open a custom tab to view the content.

For example, sometimes a Reddit post will be an image that automatically opens in the Reddit app, but sometimes it'll just be a link that opens a custom tab just to show the image. Now I have some arbitrary, not-terribly-searchable history entry for some image I likely don't care about past that point.

**Comment by mohamediburan** [comment]
Hey guys, I have been able to fix this issue. It needs some changes in custom tabs intent processing( and some minor changes in android-components customTabIntentProcessor.kt file). I am not well versed in android and If you guys give me some guidance, I might be able to provide a PR for my first bug fix or I can provide details so someone can fix this.

**Comment by NotWoods** [comment]
@mohamediburan Feel free to put up a draft PR in android-components with what you have so far. Link to this issue (`mozilla-mobile/fenix#5592`) and we can help guide you!

**Comment by sv-ohorvath** [comment]
I'm still seeing visited links in history, from custom tabs in apps like reddit & gmail. Open links in private is set to always.
device: Pixel (Android 9)
build: Nightly 10/8

**Comment by mohamediburan** [comment]
@sv-ohorvath To fix this, We needed some changes in android-components (PR mozilla-mobile/android-components#4579) and it was merged as part of 16.0.0-Snapshot. I will create a PR to fix this issue.

**Comment by athomasmoz** [comment]
Need to verify this has been fixed in Fenix. We have upgraded to the version of AC that should have the fix

**Comment by AndiAJ** [comment]
Hi, **still reproducible** on the latest **Nightly Build #13300628 from 11/26** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)

► Video
![20191126_151639](https://user-images.githubusercontent.com/51314259/69637294-0a5d9a00-1061-11ea-87da-a5c7a9d097ba.gif)

I'll remove the QA needed label until further notice.

**Comment by athomasmoz** [comment]
This is because custom tabs don't have a private mode. There is a ticket to add that feature #5334
