### ISSUE TITLE
[Bug] Android 5&6 - "Set as default browser" opens the SUMO page in background

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6000]
## Steps to reproduce
1. On an Android 5/6 device, go to Settings>Set as default browser.
2. Tap the toggle.
3. Go to the homescreen.
### Expected behavior
Redirect the user to the opened tab maybe?
### Actual behavior
The SUMO page opens in the background as many times you tap the toggle, without any indication to the user.
### Device information

* Android device: any Android 5 & 6
* Fenix version: RC 2.2.0-rc1.

**Comment by ekager** [comment]
Fixed by #5973

**Comment by AndiAJ** [comment]
Hi, still reproducible on **Fenix 2.2.0-rc.2** using a OnePlus A3 (Android 6.0.1) phone.

#### Note:
► Video
![20191016_111145](https://user-images.githubusercontent.com/51314259/66900843-34558280-f006-11e9-853b-5499b441991e.gif)

Same as the problem described in [#5898 ](https://github.com/mozilla-mobile/fenix/issues/5898#issuecomment-540991804)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Fenix **2.2.0-rc.2** using the following devices:
• Samsung Galaxy S6 (Android 6.0.1)
• OnePlus A3 (Android 6.0.1 )
• LG Nexus 4 (Android 5.1.1)
• Samsung Tab Active (Android 5.1.1)

► Video
![20191017_153234](https://user-images.githubusercontent.com/51314259/67009895-50841d00-f0f5-11e9-8355-39cca63c7515.gif)
