### ISSUE TITLE
[Bug]Improperly displayed folder icon in edit mode using the dark theme

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6076]
## Prerequisites
Have the Dark theme selected.

## Steps to reproduce
1. Navigate to any website
2. Bookmark the page
3. Tap on the "Edit" button from the snackback
4. Once in edit mode tap on the Folder (Bookmarks)
5. Go back
6. Check the color of the folder sign

### Expected behavior
Folder icon should be visible.

### Actual behavior
Folder icon is barely visible.

### Device information

* Android device: OnePlus 3A (Android 6.0.1)

* Fenix version: 
•  2.2.0-rc.2 
• Nightly Build #12900612 from 17/10

### Notes 
Regression of [#3569](https://github.com/mozilla-mobile/fenix/issues/3569)

► Video
![20191017_112252](https://user-images.githubusercontent.com/51314259/66995556-e741e100-f0d7-11e9-97f0-7bff266a1ab5.gif)

**Comment by NotWoods** [comment]
Should be fixed now

**Comment by AndiAJ** [comment]
Hi, **still reproducible** on **Debug Build from Master 1.0.1947 (Build # 1) 📦: 23.0.0, 9b8e27603 🦎: 72.0a1-20191119043902 from 11/22** using a **OnePlus A3 (Android 6.0.1)**

► Video
![20191122_135137](https://user-images.githubusercontent.com/51314259/69423906-fef03300-0d2f-11ea-9d5a-839273ea0545.gif)

However, no issues encountered on: 
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• LG Nexus 4 (Android 5.1.1)

**I'll remove the QA needed label until further notice**

**Comment by AndiAJ** [comment]
Reproducible on Fenix 3.0.2 Build #20081833 from 1/8 using a OnePlus A3 (Android 6)

**Comment by AndiAJ** [comment]
**Not reproducible** anymore  on the latest **`Nightly Build 201117`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
