### ISSUE TITLE
[Bug]Pausing & resuming a download creates multiple partially written files with same name

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#7267]
## Steps to reproduce
1. Navigate to https://www.thinkbroadband.com/download and download a file.
2. While downloading the desired file Pause & Resume a couple of times.
3. After the download is done, using the device file manager check the Downloads 

### Expected behavior
The file should be listed only once.

### Actual behavior
The file is listed multiple times and seems to be downloaded multiple times.
**Number of files = Number of download resumes**

### Device information

• Android device: 

❌ Reproducible on:
• Google Pixel 3a (Android 9)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)

✔️ Not reproducible on:
• Huawei Mate 20 Lite (Android 8.1.0)
• LG Nexus 4 (Android 5.1.1)
• [sblatz] Samsung Galaxy S9 (Android 9)

• Fenix version: Nightly Build #13520613 from 12/18

### Notes

► Video from Google Pixel 3a
![70712177-e00c0d80-1ceb-11ea-8267-77c72b413be8](https://user-images.githubusercontent.com/51314259/71069662-d9651680-2181-11ea-8951-a990f59ab372.gif)

► Video from Huawei Mate 20 Lite
![70712242-02059000-1cec-11ea-921f-0fb71620fb1d](https://user-images.githubusercontent.com/51314259/71069716-ed107d00-2181-11ea-9382-cedae7632403.gif)

**Comment by sblatz** [comment]
This is a really strange bug. I cannot reproduce this on my Galaxy S9 on Android 9. 

@csadilek do you have any idea what may be going on here? It may be related to this patch: https://github.com/mozilla-mobile/android-components/pull/5286/files

I'm digging into this a bit and my thoughts for possible issues are: 
* Download pause doesn’t kill the job? Resuming starts a new one so many files are written.
* Download resume creates a new file immediately with same name

Neither of these really make sense to me, but I'm unsure what else it would be. I'm going to see if I can reproduce this in an emulator of a Pixel.

**Comment by sblatz** [comment]
I've got it! Patch incoming :)

**Comment by sblatz** [comment]
Should be fixed in the next nightly 😄

**Comment by AndiAJ** [comment]
Hi, still reproducible on the latest **Nightly build #13530608 from 12/19** 

❌ Reproducible on:
• Google Pixel 3a (Android 9)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)

✔️ Not reproducible on:
• Huawei Mate 20 Lite (Android 8.1.0)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191219_112902](https://user-images.githubusercontent.com/51314259/71162533-113c8e80-2254-11ea-82a8-8286a93adda8.gif)

**Comment by sblatz** [comment]
Oops, sorry about that @AndiAJ, the AC version hadn't been updated. I'll make sure that gets merged before putting qa needed on this again 😄

**Comment by sblatz** [comment]
AC version has been updated to 27 so this should work on master/next nightly.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13570608 from 12/23** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191223_111818](https://user-images.githubusercontent.com/51314259/71349198-157beb00-2577-11ea-89c3-bb84c00d692c.gif)

Great job @sblatz ! ☺️
