### ISSUE TITLE
bela-lugosi.de is cropped on bottom when toolbar is on top

### ISSUE THREAD

**Issue by 1jj** [mozilla-mobile/fenix#7534]
**Move toolbar on top**
and visit http://bela-lugosi.de
Wait until animation ends.

### Expected behavior
Should display an ellipse sized over the whole viewport.

### Actual behavior
Ellipse is cropped on bottom.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
--

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
no

### Can you reproduce in Chrome (or other non-Mozilla browser)?
no

### Device information

* Android device: 7.0
* Fenix version: 71.0

**Comment by s-ankur** [comment]
this happens with many more websites and even the no internet connection page

**Comment by sv-sdeiac** [comment]
Hello, I can confirm this issue using the latest version from Playstore of Firefox Preview Nightly 1/8 build #20080617 and Firefox Preview RC 3.0.1 build #13502256.

#### Devices:
- Xiaomi Mi 8 Lite (Android 9);
- Google Pixel 3 (Android Q).

**Comment by mcarare** [comment]
This seems to have been fixed. QA for conformation. Thank you!

**Comment by sflorean** [comment]
@mcarare I wasn't able to reproduce the issue on Nightly 9/25 with Pixel 3 (Android 11).
@s-ankur based on your comment, can you check on the other websites you were mentioning? or some STR will be helpful, and I can check. Thank you!

**Comment by s-ankur** [comment]
I don't remember the other websites but I can still see this on 
![Screenshot_2020-09-25-22-22-41-922_org mozilla fenix](https://user-images.githubusercontent.com/33252312/94294627-b754bc00-ff7d-11ea-90a1-7325ec53ba23.jpg)
Nightly 200925 06:01 (Build #2015765939)
AC: 61.0.20200923190103, 50960c843
GV: 83.0a1-20200922094538
AS: 63.0.0

**Comment by s-ankur** [comment]
Also able to see this on a different reload
![Screenshot_2020-09-25-22-25-52-911_org mozilla fenix](https://user-images.githubusercontent.com/33252312/94294925-27634200-ff7e-11ea-9d16-c10d675a4233.jpg)

**Comment by Mugurell** [comment]
Thank you all!

Seems to be a layout issue in GeckoView for which I created https://bugzilla.mozilla.org/show_bug.cgi?id=1668845

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Nightly 201204 GV 85 from 12/4 with Pixel 2 (Android 9).
I will keep the qa:needed label to check this issue again on Nightly 12/7.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Nightly 201207 GV 85 from 12/7 with Pixel 2 (Android 9), by scrolling the page after the page is loaded.
I will remove the qa:needed label for now.

![20201207_093936](https://user-images.githubusercontent.com/48799384/101322795-4892b980-3870-11eb-8fb4-77088d81b724.gif)

**Comment by Mugurell** [comment]
Thank you Eliza
I can reproduce it also 
<img src="https://user-images.githubusercontent.com/11428869/101323404-4c730b80-3871-11eb-9da2-94e676bcd8af.gif" width="30%" />

Thinking that maybe after migrating the top toolbar to use a similar behavior as the bottom one (https://github.com/mozilla-mobile/fenix/issues/10686) this issue might be fixed.

Asking @hiikezoe if we should reopen the GV ticket, if there's anything else that can be done on GV.

**Comment by hiikezoe** [comment]
If this issue doesn't happen with the bottom toolbar, it's probably a Fenix issue.

**Comment by Mugurell** [comment]
Then let's have this waiting for when we unify the top/bottom dynamic toolbar implementation.

**Comment by Mugurell** [comment]
I think this issue is rather fixed by now.
In the latest Nightly I see the page not scrolling and the toolbar not animating, as expected.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 6/9 with Samsung Galaxy S7 (7) and Google Pixel 4 XL (11).
Note that the bottom looks fine and nothing is cropped.
