### ISSUE TITLE
[Bug] [a11y] Consider making the "Send crash report to Mozilla" item larger

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7752]
## Prerequisite
Make sure you have Accessibility Scanner installed and turned on.

## Steps to reproduce
1. Launch Fenix, open a website.
2. In the same tab, go to about:crashcontent.
3. Scan the page using Accessibility Scanner.

### Expected behavior
No major discrepancies are reported.

### Actual behavior
The "Send crash report to Mozilla" item is suggested to be increased from 32dp to 48dp or larger.

### Device information
* Android devices: Huawei Honor 8 (Android 7), Samsung Galaxy Tab S3 (Android 8)
* Fenix version: 01/16 Nightly build

![Screenshot_20200116-105758_Accessibility Scanner](https://user-images.githubusercontent.com/40694158/72511528-fdd11300-3853-11ea-9465-06c59101063d.jpg)

**Comment by sblatz** [comment]
Again my be fixed by my patch but I'll make sure!

**Comment by Diana-Rus** [comment]
Hi, this outcome is still present for "Send crash report to Mozilla" checkbox on Nightly 04/07 (Build #20980610) with Samsung Galaxy S9 (Android 8).

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/9 with LG G7 FIT (Android 8) and Google Pixel (Android 10). No suggestions are made for about:crashcontent page.
