### ISSUE TITLE
[Bug]uBlock Origin icon flicker

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8111]
## Steps to reproduce
1.From the home screen tap the 3 dot button and open Settings.
2.  From the "Advanced" section open "Add-ons".
3. Check the uBlock Origin icon.

### Expected behavior
No UI issues.

### Actual behavior
When opening the "Add-ons" the uBlock Origin flickers, sometimes displaying a puzzle (image) instead of the actual icon for a couple of seconds. 

### Device information

* Android device: 
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly Build #20360606 from 2/5

► Video
![20200205_162152](https://user-images.githubusercontent.com/51314259/73851194-bf68bb80-4835-11ea-8218-5d004d10dac8.gif)

**Comment by csadilek** [comment]
We're loading icon in a separate thread so it comes in at a later time (we don't want to block on it), but we're thinking of adding an animation to make this smoother.

**Comment by Amejia481** [comment]
@AndiAJ this should be fixed by now, would you mind retesting?

**Comment by AndiAJ** [comment]
Hi @Amejia481 , I've just checked this matter on the latest **`Nightly Build #20550606 from 02/24`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Sony Xperia Z5 Premium (Android 7.1.1)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

❌It seems that when using the "Dark" theme, the animation has some problems, namely the background pic (puzzle) is displayed causing transition inconsistency.

✔️ While using the "Light" theme everything seems to be properly working. 

► Video Dark theme
![20200224-103913](https://user-images.githubusercontent.com/51314259/75138698-849aca80-56f3-11ea-976d-d3fb39439596.gif)

► Video Light theme
![20200224-104422](https://user-images.githubusercontent.com/51314259/75138787-c3c91b80-56f3-11ea-89f6-f3359896a6a1.gif)

**Comment by Amejia481** [comment]
Now we should go it, @AndiAJ it should be fixed now in the latest Nightly. Would you mind retesting?

**Comment by AndiAJ** [comment]
Hi @Amejia481 , unfortunately **it's still reproducible** on the latest **`Nightly Build #20550606 from 02/25`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video 
![20200225-092642](https://user-images.githubusercontent.com/51314259/75225021-621bb680-57b2-11ea-8076-adb25a29e9b7.gif)

**Comment by Amejia481** [comment]
Thanks @AndiAJ, 
It looks like the change didn't make it to the last snapshot, I will let you know as soon the change is in.

**Comment by Amejia481** [comment]
@AndiAJ the fix is now in the latest Nightly. could you please verify? Thanks in advance :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200226-153426](https://user-images.githubusercontent.com/51314259/75349604-c8393400-58ad-11ea-9fc1-3929d448b841.gif)

Great job @Amejia481 ! ☺️

**Comment by Amejia481** [comment]
Thank you for the quick response ❤️
