### ISSUE TITLE
[Bug]There is no indication in the Add-ons page that the add-on is disabled/enabled

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/fenix#8161]
## Prerequisites
uBlock Origin is installed in Fenix
## Steps to reproduce
1. From the home screen tap the three-dot button and open Settings
2. Scroll down and tap on “Add-ons”
3. Notice the aspect of the installed add-on (color, icon, text, tags, status etc.)
4. Tap on the add-on
5. Disable the add-on via the toggle button
6. Return to the Add-ons page via the back button at the top of the screen
7. Observe that there is no indication that the add-on is disabled (no disabled tag, no change in colors, no change in status)
### Expected behavior
Users should be able to distinguish between the enabled/disabled state of the add-on in the Add-ons page.
### Actual behavior
There is no indication that the add-on is disabled in the Add-ons page.
### Device information
* Samsung Galaxy S7 (Android 8.0.0)
* Samsung Galaxy S7 Edge (Android 8.0.0)

* Fenix version: #20370605 02/06/2020

![missing enabled-disabled indicator](https://user-images.githubusercontent.com/50236075/73948026-15eefc00-4901-11ea-8b72-1eb5f954d35f.gif)

**Comment by Amejia481** [comment]
I think this wasn't part of the original design, @brampitoyocould could help us to confirm

**Comment by brampitoyo** [comment]
@Amejia481 @gabrielluong Correct.

Yes, enabling and disabling add-ons – and labelling disabled add-ons – was in the specs. They were indicated as “post-launch”. We were not going to launch with it. However, @csadilek had made time to develop the toggle.

If we now still have time to continue the work by labelling these disabled add-ons, I would highly recommend it.

The Miro board is still located on the same URL. I’m posting only the relevant user flow below:

<img width="1204" alt="Screen Shot 2020-02-10 at 10 45 02 AM" src="https://user-images.githubusercontent.com/51007/74110580-ab84d700-4bf2-11ea-8516-9b79918eb7ee.png">

There are two changes to note here:

1. In the Add-ons Manager that there’s a new label called “Disabled”
2. The current label for installed add-ons is “Installed”. Disabled will introduce a new state. To follow, we will need to rename “Installed” → “Enabled”

-----

Additionally, we’re planning to ship “Not yet supported” add-ons one day. This will mean that add-ons can have many possible states:

- Enabled (old name: Installed)
- Disabled
- Recommended
- Not yet supported

Given many possible scenarios, what’s the ideal order of sections within the Add-ons manager?

- IF no add-on installed
    - Recommended ← comes first
    - Not yet supported
- IF ≥1 add-on installed
    - Enabled ← comes first
    - Recommended
    - Not yet supported
- IF ≥1 add-on installed AND ≥1 add-on disabled
    - Enabled ← comes first
    - Disabled
    - Recommended
    - Not yet supported

**Comment by Amejia481** [comment]
@acornestean  this should be fixed by now, would you mind re-testing?

**Comment by Amejia481** [comment]
@brampitoyo Thanks for details :)

**Comment by acornestean** [comment]
Re-tested the issue on the latest build #20410606 from 02/10/2020 on Samsung Galaxy S7 (Android 8.0.0), Samsung Galaxy S7 Edge (Android 8.0.0) and Nexus 9 (Android 7.1.1).

The issue is still present i.e. there still isn’t any indication in the add-on listing page that the add-on is enabled or disabled. It behaves just like before.

**Comment by softvision-miralobontiu** [comment]
I'll remove the eng:qa:needed label until the fix can be verified.

**Comment by Amejia481** [comment]
It looks like the change didn't make it to the snapshot, I will let you know when it is in

**Comment by Amejia481** [comment]
Now it's on master :),  @softvision-miralobontiu or @ acornestean  would you mind re-testing? Thanks in advance

**Comment by acornestean** [comment]
As requested, I’ve re-tested the issue on the latest Nightly build #20420611 from 02/11/2020 on Samsung Galaxy S7 (Android 8.0.0), Samsung Galaxy S7 Edge (Android 8.0.0) and Nexus 9 (Android 7.1.1). 

The issue is Verified Fixed in the current build.

A “Disabled” header appears above the add-on when it’s disabled. When enabled, the header states “Installed”.

![Disabled](https://user-images.githubusercontent.com/50236075/74217976-aa66af00-4cb1-11ea-89b3-4f2c08348600.jpg)

![Enabled](https://user-images.githubusercontent.com/50236075/74217980-af2b6300-4cb1-11ea-889d-5385446f4e27.jpg)

**Comment by brampitoyo** [comment]
All looks good. We just need to relabel “Installed” to “Enabled”, if possible.

**Comment by Amejia481** [comment]
@gabrielluong Already did that change https://github.com/mozilla-mobile/android-components/commit/cf6ed19c86f6e0034eccdb9443f76d2daaf172d2? now it is on nightly :)

![image](https://user-images.githubusercontent.com/773158/74353236-9beac700-4d87-11ea-9f3d-8fe47100269d.png)
