### ISSUE TITLE
[Bug]Logins prompt icons aren't properly displayed while using the Light theme 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8577]
## Prerequisites
Have the Light theme selected 

## Steps to reproduce
1. Navigate too goo.gl/vi7z6
2. Fill in the Username and Password and proceed by tapping the Login button
3. Check the Login prompt

### Expected behavior
The icons from the prompt are visible

### Actual behavior
The icons aren't visible 

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Beta 4.0.0-beta.1 from 2/19
• Nightly #20510607 from 2/20

### Notes
► Screenshot
![rsz_screenshot_20200220-151624](https://user-images.githubusercontent.com/51314259/74937463-c5919700-53f4-11ea-8c35-1c3ef2d5440c.png)

**Comment by ekager** [comment]
Should be fixed by https://github.com/mozilla-mobile/android-components/pull/6029

**Comment by AndiAJ** [comment]
Hi @ekager , still reproducible on the latest `Nightly Build #20550606 from 02/24` using the OnePlus A3 (Android 6.0.1)

►Screenshot
![rsz_screenshot_20200224-091107](https://user-images.githubusercontent.com/51314259/75135628-d25f0500-56ea-11ea-90a2-487369fd5225.png)

**Comment by ekager** [comment]
Could we test this again? I can't reproduce

**Comment by AndiAJ** [comment]
Hi @ekager , unfortunately it's **still reproducible** on the latest **`Nightly Build #20630607 from 03/03`** using the OnePlus A3 (Android 6.0.1)

►Screenshot
![rsz_screenshot_20200303-102049](https://user-images.githubusercontent.com/51314259/75756426-517eb980-5d39-11ea-846c-0ce15e9b26e3.png)

✔️ Not reproducible on the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• LG Nexus 4 (Android 5.1.1)

**Comment by AndiAJ** [comment]
Hi, I've re-checked this issue on the latest **`Nightly Build #20660604 from 3/6`** and it's still reproducible on:
• OnePlus A3 (Android 6.0.1)
• OnePlus A2005 (Android 6.0.1)

► Screenshot
![rsz_1screenshot_20200306-091836](https://user-images.githubusercontent.com/51314259/76062511-85065180-5f8e-11ea-9fae-029b12f68df7.png)


✔️ Not reproducible on the following devices:
• Google Pixel 3a XL(Android 10)
• Google Pixel 3a (Android 9)
• OnePlus 6T (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• LG Nexus 4 (Android 5.1.1)

**Comment by ekager** [comment]
Okay I fixed every other vector compat issue and I'm not sure why this one is being a pain 🤔 Worst case scenario we can force it to tint dynamically in code in `LoginDialogFragment` in AC
