### ISSUE TITLE
[Bug] Private custom tab opened when signing in to sync records history

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#8716]
# Steps to reproduce

1. Make sure sync is not turned on and you are in private browsing mode. Go to **Main Menu > Settings > Turn on Sync**.
2. Click on the **Use email instead** button. This will launch a private custom tab prompting the user to sign in.

# Expected behavior

The private custom tab does not record any history, like normal private custom tabs opened from other applications.

# Actual behavior

This private custom tab records the browsing history.

![](https://user-images.githubusercontent.com/45960387/75226441-51396800-57e7-11ea-8d46-0edd4d28d624.gif)

One behavior I noticed is that this is a "special" private tab - it does not follow the "Open links in private tab" option, rather, it follows the browsing mode settings was opened in. For example, even if "Open links in private tab" is enabled, opening settings when in normal browsing mode and then clicking on the **Use email instead** button will open a normal custom tab (not private).

# Device information

* Android device: Oppo Reno 2, Android 9
* Fenix version: Nightly 200225 06:00 (Build #20560607)

**Comment by ekager** [comment]
I believe this should also be fixed by #8740

**Comment by AndiAJ** [comment]
Hi, **still reproducible** on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200226-124602](https://user-images.githubusercontent.com/51314259/75337959-a1bbce80-5896-11ea-8d85-5a40aed0a082.gif)

**Comment by sv-ohorvath** [comment]
Note: History is recorded in any private custom tab, in Gmail for example.

**Comment by SL-Lee** [comment]
I don't think that's true. If a private custom tab records history, that is likely caused by #9037 (a stylistic issue), where the "Open links in a private tab" is **off** and Fenix was left in private browsing mode, leading users to believe that they are using a private custom tab when they are actually not.

Quote from #9037:

> Custom tabs appear as private custom tabs, but pressing "Open in Firefox Nightly" opens it in a normal tab (which means it DOES record history -- hence may be related to #8716).

This issue focuses more on why clicking on the "use email" button **always** opens a normal tab (and gets its colors overridden by #9037 if you just so happen to be in private browsing mode when clicking the button), and not respecting the "Open links in a private tab" setting.

**Comment by sv-ohorvath** [comment]
@SL-Lee thanks for the clarification.

**Comment by SL-Lee** [comment]
Note: Though #9037 does not reproduce anymore on **Nightly 200929 17:11 (Build #2015766795)**, this issue is *still* reproducible on the same version. So this issue might **not** be caused by #9037 (as I had [thought before](https://github.com/mozilla-mobile/fenix/issues/8716#issuecomment-631537102)).

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on Beta 82.0.0-beta.4 with Samsung Galaxy Tab S6 (Android 10).

**Comment by softvision-miralobontiu** [comment]
The issue is reproducible on the latest RC 81.1.5 with Samsung Galaxy Tab S6 (Android 10).
I've signed in with a valid FxA account while accessing Settings - Turn on sync in private mode, and all the browsing was visible in History.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 1/13 Nightly build with Sony Xperia Z5 PRemium (Android 7.1.1), and Google Pixel (Android 10).
I've signed in, in private browsing, both by pairing, and by using email. No records were visible in History.

**Comment by AndiAJ** [comment]
**Still reproducible** on **`85.1.0-rc.1`** using a OnePlus A3 (Android 6.0.1)

**Comment by softvision-miralobontiu** [comment]
Reproducible on RC 85.1.1 too, with Sony Xperia Z5 Premium (Android 7.1.1).
