### ISSUE TITLE
[Bug] Dynamic Nav Bar leaves white space on certain websites

### ISSUE THREAD

**Issue by serovar** [mozilla-mobile/fenix#8768]
## Steps to reproduce
Go to your feeds on feedbin.com and scroll down
### Expected behavior
The bottom nav bar hides itself leaving way for the webpage content.
### Actual behavior
The bottom nav bar hides itself but leaves a white space.
### Device information

* Android device: Pixel 2 XL, Android 10
* Fenix version: Nightly 200226 (Build #20570605)

![screen](https://user-images.githubusercontent.com/6732420/75343241-ed1eae80-588f-11ea-859f-8381e5f99470.gif)

**Comment by TitanNano** [comment]
This also happens on:

- https://squoosh.app
- https://web.telegram.org
- https://maps.google.com

**Comment by PopeRigby** [comment]
Also having this issue on https://www.gog.com

**Comment by KWierso** [comment]
I have Twitter running in Firefox Preview Nightly as a PWA, and it acts weird, too.
![image](https://user-images.githubusercontent.com/172215/75379694-ad08fd00-588a-11ea-9ce3-19e910f7b0db.png)


I don't know if it's this exact issue, but it started happening after Nightly updated this morning.

**Comment by ekager** [comment]
Starbucks order page behavior with dynamic bottom toolbar (this is a PWA-able page but not using it as a PWA)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25442310/75393171-50194100-58a2-11ea-88b4-9e368a7393ec.gif)

**Comment by TitanNano** [comment]
@sblatz your title change is not correct. This affects both PWA standalone activity and the browser activity. For many sites the bottom and top toolbar leave a white gap when they disappear. If the same page is opened in PWA mode, the white gap is always present.


![browser_mode](https://user-images.githubusercontent.com/4500858/75429617-5cf16f80-594a-11ea-90a8-61ffbef32e25.gif)
normal browsing

![pwa_mode_small](https://user-images.githubusercontent.com/4500858/75434284-99749980-5951-11ea-97bd-c88492953aea.gif)
PWA mode

**Comment by sblatz** [comment]
@snorp mentioned it's related to this GV issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1618582

**Comment by serovar** [comment]
Edited title since I noticed that the problem remains even with the nav bar on top.

**Comment by snorp** [comment]
The GV changes have landed, so now we'll be able to use this in Fenix. A while back we added a separate `onTouchEventForResult()` method to the `GeckoView` class. Instead of returning a `boolean` as `onTouchEvent()` does, it returns an `enum` (well, `int)` indicating how the event was consumed[1]. There are three values: `UNHANDLED`, `HANDLED`, and `HANDLED_CONTENT`. Fenix should *only* move the toolbar if it gets a `HANDLED` result back from this. That means that we used it to do a panning or zooming operation (and also passed it on to web content). If Fenix gets `UNHANDLED`, it should make the toolbar visible and not move it in response to further events for that touch. This is what will happen for non-scrollable pages. `HANDLED_CONTENT` means event was in a region where the page has touch event listeners (e.g., Google Maps). Fenix could probably treat this the same as `UNHANDLED` because it should not move the toolbar in such a case. Whether it should also make the toolbar visible is debatable, but probably the safest thing.

[1] https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/PanZoomController.html#INPUT_RESULT_HANDLED

**Comment by liuche** [comment]
Also see #9031 - we can check this for when we pick up these GV changes in AC.

If @sblatz has other things he's working on next week (let me know!), we should be able to find someone to take a look at this. Nav Bar is Nightly only right now, so this won't be hitting any release users yet.

**Comment by sblatz** [comment]
Based on snorp's comment this will require an AC patch. I'm looking into it now.

**Comment by sblatz** [comment]
I have poked around on this on the AC side. What's odd is that I'm able to fix it in AC but not in Fenix. We must be doing something else on the Fenix side. I'm going to keep investigating here.

**Comment by sblatz** [comment]
Submitted an AC patch: https://github.com/mozilla-mobile/android-components/pull/6244

**Comment by bogas04** [comment]
Possible duplicate https://github.com/mozilla-mobile/fenix/issues/8777

**Comment by abodea** [comment]
Might be related https://github.com/mozilla-mobile/fenix/issues/9226.

**Comment by petterill** [comment]
Possible duplicates #9371 and #9299

**Comment by hiikezoe** [comment]
Note that issues with top toolbar transition are #6940.

**Comment by abodea** [comment]
I can still reproduce issue following the examples from above, is the fix already in latest nightly @sblatz?
Re-checked this on the latest Nightly 3/26 with Google Pixel 4 XL (Android 10).
I will remove the `eng:qa:needed` until further notice,

![20200326-145939](https://user-images.githubusercontent.com/42831109/77652598-26be0480-6f77-11ea-89ef-c575e8ce2bba.gif)
![20200326-145826](https://user-images.githubusercontent.com/42831109/77652604-29205e80-6f77-11ea-9628-bfb286d4ac22.gif)

**Comment by TitanNano** [comment]
this also still affects many PWAs

**Comment by hiikezoe** [comment]
The issue on https://squoosh.app is a different one.  I should note that if the content is scrollable, it's not the same issue.  The issue on squoosh looks https://bugzilla.mozilla.org/show_bug.cgi?id=1619169, but I am not 100% sure.

On starbucks it looks correct to me.

Anyways, on Pixel4, as far as I know, WebRender is enabled by default so there is another issue remaining (https://bugzilla.mozilla.org/show_bug.cgi?id=1610731).

**Comment by hiikezoe** [comment]
The issue on squoosh.app also happens with the top toolbar, it makes me wonder the site does something when scrolling happens, if it does it's an issue in the site itself I think.

**Comment by karlcow** [comment]
fwiw it creates a certain number of webcompat issues reports.

**Comment by TitanNano** [comment]
@hiikezoe with out any investigation, I'd say the page is setting a container to 100% height and then scrolls inside the container.

**Comment by hiikezoe** [comment]
That's super helpful info.  So, I think I was confused by the vertical scroll bar there. I thought the scrollbar is for the root scroll container, but it seems not.  That means that the dynamic toolbar shouldn't be moved at all.

@snorp, @sblatz, I believe the issue on squoosh.app is still an issue in interactions with GV and Fenix.

**Comment by Rorschach1010** [comment]
I only use 2 PWAs but both have this issue (Instagram and Twitter). Waiting patiently for a fix.

**Comment by sblatz** [comment]
Snorp seems to have fixed this with the bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1627737

![fixed scrolling 2020-04-13 11_26_58](https://user-images.githubusercontent.com/4400286/79148031-b76b5180-7d79-11ea-93f8-2ab04a1e4a62.gif)

**Comment by sblatz** [comment]
I'm filing a follow up for PWA's (like Twitter): https://github.com/mozilla-mobile/fenix/issues/9892

**Comment by softvision-miralobontiu** [comment]
This issue is not fixed yet.
Tested on the following sites: feedbin.com, squoosh.app, maps.google.com, gog.com/forum, twitter.com, starbucks.com, cdc.gov, instagram.com, krcw.com, bnonews.com, and wp.pl,
with OnePlus 5T (Android 9), Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1), with the latest Nightly build from 4/16.

On Google Pixel the following pages, the dynamic nav bar leaves spaces:
- twitter.com,
- instagram.com,
- cdc.gov,
- wp.pl.
I'll remove the qa:needed flag.

![instagram](https://user-images.githubusercontent.com/40694158/79442863-c3f1e300-7fe1-11ea-9eac-351e1c2c501d.gif)

**Comment by sblatz** [comment]
@softvision-miralobontiu that looks like the correct behavior to me. If all you're seeing is the small gap that happens while scrolling that's the best we can do for now. If the gap persists and doesn't follow the scroll that's what we're worried about.

Did all of the sites you tested have the behavior shown in your GIF? If so I think we can close this!

**Comment by serovar** [comment]
I think you can't close this yet.

![Screenshot_20200416-220159](https://user-images.githubusercontent.com/6732420/79501278-10631000-802e-11ea-9e4f-0dac7a8aace3.png)

feedbin.com, Nightly 200416 18:00 (Build #21071807) (the latest).

**Comment by sblatz** [comment]
@serovar we are having delays with our nightly builds right now. This should be fixed on master.

**Comment by serovar** [comment]
I know, my Nightly is the latest from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest), you can check the build that I wrote.

**Comment by hiikezoe** [comment]
There seems a rare condition that the touch handling results are misrecognized on images in the case of feedbin?

**Comment by serovar** [comment]
It does it only with two rapid downward scrolls.

**Comment by hiikezoe** [comment]
It might be better to open a new issue to track down the race.

**Comment by serovar** [comment]
It does it with a single swipe if the bar is on top, are you sure that I should open a separate issue? And, if yes, should I open two separate issues for the top bar and the the bottom one?

Top bar
![feedbintop](https://user-images.githubusercontent.com/6732420/79515847-ff27fc80-8049-11ea-9eb5-0aa19b327f9f.gif)

Bottom bar
![feedbindown](https://user-images.githubusercontent.com/6732420/79515859-06e7a100-804a-11ea-9764-5fb0b4e7ac47.gif)

**Comment by hiikezoe** [comment]
The top bar case is totally different one. https://github.com/mozilla-mobile/fenix/issues/6940. sblatz has been hardly working on the issue.

**Comment by Blaze-Thunder** [comment]
This bug is not solved yet. I am on latest Fenix Nightly 200420 06:01. On Telegram WebApp, there is still white bar present at bottom.

**Comment by hiikezoe** [comment]
As far as I can tell, the PWA case should have been fixed in https://github.com/mozilla-mobile/fenix/issues/9892

@Blaze-Thunder it's worth filing a new issue with detailed descriptions.
Thanks!

**Comment by softvision-miralobontiu** [comment]
> @softvision-miralobontiu that looks like the correct behavior to me. If all you're seeing is the small gap that happens while scrolling that's the best we can do for now. If the gap persists and doesn't follow the scroll that's what we're worried about.
> 
> Did all of the sites you tested have the behavior shown in your GIF? If so I think we can close this!

@sblatz I could see the small gap only on Google Pixel, on the following pages
* twitter.com,
* instagram.com,
* cdc.gov,
* wp.pl.

I saw the exact behavior like in the GIF on all 4 pages from above.

**Comment by sblatz** [comment]
This also affects Telegram as mentioned [here](https://github.com/mozilla-mobile/fenix/issues/10071)

**Comment by karlcow** [comment]
for those checking only their email notifications, there seems to be a big class of issues related to this or close that are reported through webcompat. You can see the links here in this issue going to the webpage.

**Comment by sblatz** [comment]
I'm not able to reproduce this on the latest nightly on: 

maps.google.com (PWA or regular site)
telegram.com (PWA or regular site)
twitter.com (PWA or regular site)

QA can you please verify?

**Comment by hiikezoe** [comment]
Note that if you still see blanks at the top and the bottom of the contents, please check whether WebRender is enabled or not in about:support. If WebRender is enabled, it's a known issue, https://bugzilla.mozilla.org/show_bug.cgi?id=1619169 I've started looking into.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 6/5 with Samsung Galaxy Note 8 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), and OnePlus 5T (Android 9), on the following pages:
* feedbin.com, 
* facebook.com,
* twitter.com,
* instagram.com,
* squooch.app,
* maps.google.com,
* cdc.gov, and
* youtube.com.

**Comment by serovar** [comment]
>     * feedbin.com

I don't know if it makes sense to consider feedbin.com as "fixed", since now if you login (using it as in the screencast in the first post, not simply going to feedbin.com without logging in) the navigation bar is fixed (i.e., it does not hide itself when scrolling).

**Comment by softvision-miralobontiu** [comment]
Hi @serovar,
The issue was regarding the dynamic bar leaving white spaces on certain websites.
I've retested on feedbin.com with the latest Nightly build from 6/11 with Samsung Galaxy Tab S6 (Android 9), signed in with a valid account, and no such white spaces where displayed. Indeed, the bottom navigation bar is fixed, is not dynamic - this should be a new issue.

Setting the navigation bar to the top doesn't display the white space either, but the navigation bar set at the top is dynamic.

**Comment by serovar** [comment]
> Setting the navigation bar to the top doesn't display the white space either

With the navbar to the top, I still get the with space at the bottom on the latest nightly (Nightly 200611 06:01, Build #2015745587).

![feedbin top navbar](https://user-images.githubusercontent.com/6732420/84372180-03504080-abdb-11ea-9118-c0200d329805.gif)

**Comment by softvision-miralobontiu** [comment]
I will reopen the issue, I was able to reproduce the white spaces having the navigation bar set to the top, on 6/11 Nightly build using Google Pixel (Android 10), Google Pixel 3a (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
I've tested on a tablet before, and it didn't reproduce there.
Thank you!

**Comment by sv-ohorvath** [comment]
There is https://github.com/mozilla-mobile/fenix/issues/11389 covering the same issue, so we can close this.

> I will reopen the issue, I was able to reproduce the white spaces having the navigation bar set to the top, on 6/11 Nightly build using Google Pixel (Android 10), Google Pixel 3a (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
> I've tested on a tablet before, and it didn't reproduce there.
> Thank you!

**Comment by aquaductape** [comment]
I also see the same bug, on my website https://aquaductape.github.io/3nRow/, 

I have a screen recording https://photos.app.goo.gl/ZyqXHFM3UTgbWvyL9

In the video
0:00 - 0:04: I am on Chrome Android, I'm scrolling down, but since the page is 100% to viewport, I'm already at the bottom of the page, you can tell because I am activating Chrome's Refresh Page button. This is how I expect Firefox to behave ( except the Refresh Page button behavior ).

0:08: I open my website on Firefox, everything seems normal

0:08 - 0:14 For some reason I am able to scroll down, and and html background, which is blue, is revealed.

0:16: White space is revealed, and I am no longer able to scroll down.

**Comment by imannms** [comment]
After 1 year and this bug still exists

**Comment by erperejildo** [comment]
still facing the same issue. Can't see footer unless I scroll down

**Comment by xcjs** [comment]
I can confirm this is still an issue when the navigation bar is on the top. Web pages still render as if the bottom bar is present, especially if they have a "sticky footer". Firefox on Android is not calculating the viewport size correctly, and hasn't since the option to display the address bar on the bottom was released.

**Comment by thomasaarholt** [comment]
I too would like this issue reopened.

**Comment by TrissieTheHusky** [comment]
Same. I run IOS Firefox. My website has a white space at the bottom and me using Firefox a majority of the time. Really think this should be addressed/Fixed.

**Comment by hiikezoe** [comment]
> I can confirm this is still an issue when the navigation bar is on the top. Web pages still render as if the bottom bar is present, especially if they have a "sticky footer". Firefox on Android is not calculating the viewport size correctly, and hasn't since the option to display the address bar on the bottom was released.
> 
> @sv-ohorvath What's needed to reopen this issue?

Opening a new issue with at least one site you can see the issue would be nice. A simple test case would be much appreciate. Thanks!

**Comment by oalfred** [comment]
I wanted to add here that I have the same problem when zooming in on an image, and it happens regardless of if the tool bar/address bar is at the top or at the bottom.

Steps to reproduce:
* View an image in Firefox on Android, for example https://en.wikipedia.org/wiki/Image#/media/File:Image_created_with_a_mobile_phone.png.
* Zoom in until the image covers the entire screen.
* Scroll up and down a bit

Screenshot, note the white area above the touch controls:
![Screenshot_20210908-150245_Firefox](https://user-images.githubusercontent.com/38034577/132515292-e32d166b-3f74-48fa-9b53-a632fb24803b.jpg)

**Comment by adrianvincent91** [comment]
After some debugging, this problem seems to occur when 'overflow: hidden' is added to document.body. As a temporary fix, I'm adding an alternative to the body when I detect Firefox Android.

`body.overflowHiddenFirefoxMobile {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
}`

**Comment by greddyz** [comment]
I`m fixed it for Firefox Android add rule "top:100%"

`.nav {
    position: fixed;
    top: 100%;
    left: 0;
    right: 0;
    bottom: 0;
}
`
