### ISSUE TITLE
[Bug] Fenix reloads every page after being backgrounded

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#9039]
## Steps to reproduce
Restart phone so plenty of free memory
Close all Fenix tabs
Open arstechnica.com in Tab 1
Open mozilla.org in Tab 2
(mozilla.org page is visible)
put Fenix into background using Android home button
bring Fenix to foreground by tapping its icon
(mozilla.org page is visible)
switch to arstechnica.com tab by tapping tab counter & arstechnica tab
blank screen, arstechnica.com tab reloads which takes ~1-2 seconds
**---> incorrect behavior, IMHO tabs should not need to reload when there is plenty of spare memory, they should be instantly visible**

### Device information

* Android device: Galaxy A40, Android 9
* Fenix version: Today's

**Comment by mattcoz** [comment]
I've been noticing this also.

**Comment by Mentis** [comment]
I have the same issue.
Android 10, Pixel 3 XL

**Comment by ekager** [comment]
cc @pocmo could this have anything to do with https://github.com/mozilla-mobile/android-components/pull/6170 ?

**Comment by Mentis** [comment]
Moreover, it happens to me on switching between tabs also.

**Comment by itzXian** [comment]
still having the issue, it really bugs me :-/

**Comment by ekager** [comment]
cc @pocmo I don't think https://github.com/mozilla-mobile/android-components/issues/5529 / https://github.com/mozilla-mobile/android-components/pull/6381 are related here since those were specifically tab collections. Is it possible we aren't restoring correctly somewhere else? And that this problem could have started with https://github.com/mozilla-mobile/android-components/pull/6170?

**Comment by liuche** [comment]
@sblatz adding this to AC top 10 - not sure what's causing this but seems likely something from AC, and needs some investigation.

**Comment by Maxnor** [comment]
Having the same issue on Samsung Note 10+ with plenty of memory available. The problem doesn't happen instantly when switching tabs.
What I did notice is that Firefox Preview is already using over 2 GB memory although only a few tabs are open.

**Comment by jonalmeida** [comment]
I see this in r-b as well. Seems like the page is getting unloaded when I'm switching between many tabs.

**Comment by victor-bayas** [comment]
Experiencing the same problem on my SM-G970F with OS 10

**Comment by joelocandol** [comment]
I have the same bug with Android 7.0 Oukitel c5 firefox nightly

**Comment by ccboxes** [comment]
Have the same bug. 
In fact, there are similar problems when fenix being used in the foreground. When a tab is placed in the foreground for a long time, switching to another tab will cause a reload. Change 'browser.cache.memory.capacity' to -1 seems to help. But it doesn't work after being background.

**Comment by andreicristianpetcu** [comment]
same. one plus 5t

**Comment by Mentis** [comment]
This bug is quite annoying and makes multitasking between multiple tabs impossible. Hope this will be fixed once Fenix will be promoted to stable

**Comment by pocmo** [comment]
@psymoon Have you already looked into this? Otherwise I can help too. We landed a patch in AC that correctly restores the engine session. But I assume this is a different bug if it still reproduces in the latest Nightly.

**Comment by psymoon** [comment]
@pocmo I haven't had the chance to look at this yet. Feel free!

**Comment by pocmo** [comment]
We landed a patch for this in AC and it should make it into the next Nightly. I'll add the QA label.

**Comment by andreicristianpetcu** [comment]
@pocmo it does not seem fixed in the current fennec nightly :(

**Comment by xsikor** [comment]
Same shit.. not fixed yet
Veraion Nightly 200509 06:01
But now if you disable internet connection - firefox will be restore tabs from cache

**Comment by victor-bayas** [comment]
@pocmo Fenix is still unusable for me, the patch seems to only make it restore tabs faster but it stills unload those tabs from RAM when you switch to other app.

**Comment by Mentis** [comment]
Can confirm. Can't notice any change. Tabs are still getting unloaded. For me I don't even need to switch to another app. Tabs are getting unloaded on simple switching between them.

**Comment by lindongbin** [comment]
This bug started to appear from this version
https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly.2020.03.06/latest

This version is normal
https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly.2020.03.05/latest

**Comment by victor-bayas** [comment]
Can confirm that 03/05 nightly works fine, whatever change they introduced in the next nightly is likely the culprit of this bug.

**Comment by AndiAJ** [comment]
Hi, **still reproducible** on the latest **`Nightly Build 200511 from 5/11`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200511-103157](https://user-images.githubusercontent.com/51314259/81535893-46688b00-9373-11ea-998b-8403953329d3.gif)

**Comment by pocmo** [comment]
@AndiAJ Can you check whether the scroll position for example restores? A quick loading bar can appear - however from the gif I can't really see whether we are actually reloading or restoring. Can you maybe make some logs accessible? :)

**Comment by AndiAJ** [comment]
Hi @pocmo , 
Yes, the scroll position is properly kept.
Yes, a quick load bar is displayed.

► Video
![20200511-114526](https://user-images.githubusercontent.com/51314259/81543065-428e3600-937e-11ea-8bb2-21dad3770cbd.gif)

[Log](https://github.com/mozilla-mobile/fenix/files/4608543/lg.txt)

Please review and share your thoughts. ☺️

**Comment by itzXian** [comment]
Fenix `5.0.0` from [Play Store](https://play.google.com/store/apps/details?id=org.mozilla.fenix)
and
Fenix Nightly `200305 06:01` from [the comment](https://github.com/mozilla-mobile/fenix/issues/9039#issuecomment-626325474)

**Steps**:
- Play a Youtube video in a new tab 
- Jump to a whatever position of the video
- Switch to another tab
- Go to Launcher
- Go back to Fenix
- Switch back to the Youtube tab
**On Fenix `5.0.0`**
Reloading(or Restoring?) the page and playing the video from start
**On Fenix Nightly `200305 06:01`**
What I expected


[Record](https://i.imgur.com/53crpGn.mp4)

**Comment by pocmo** [comment]
Thank you, @AndiAJ, this looks good.

@itzXian Thank you too! It looks like this specific issue is still reproducible and I'll try to debug what's going on in that case.

**Comment by xsikor** [comment]
Ok, little one more info.
I think it's das a full rerender of page because if we use an anchor on page - then tab will not remember scroll position after backgrounding and start scroll position at anchor  

Example
![sample](https://user-images.githubusercontent.com/3236447/82162789-c8930b00-98af-11ea-9812-3b3093e1f9fc.gif)

Build #200517

**Comment by itzXian** [comment]
I was wondering if this commit related
89a260e

**Comment by xsikor** [comment]
@itzXian almost fixed
It's still re render pages, but now it's very fast

**Comment by Mentis** [comment]
For me main issue is that form content is being lost during the reload. This makes multitasking between multiple tabs almost impossible.

> @itzXian almost fixed
> It's still re render pages, but now it's very fast

**Comment by buttercookie42** [comment]
@Mentis Does this happen everywhere, even on very simple form fields (like e.g. one of the text inputs here: https://www.456bereastreet.com/lab/html5-input-types/), or only on more complex pages?

**Comment by Mentis** [comment]
@buttercookie42 wasn't able to repro it on this website. However can repro it like that: 
![20200524_184717](https://user-images.githubusercontent.com/273806/82770964-5bbbcb80-9def-11ea-93e2-ced23de24d3e.gif)

**Comment by SS1113** [comment]
It's really frustrating, I don't know when the tab will reload/restore and reset the position while restoring or lose the content I typed, even switching tab for a second or two cause it to restore, just a while back when I was browsing a reddit thread and switched to search something and when I got back after 3 seconds or so the position where I was at was reset so I had scroll to the exact position I was on and it was really frustrating because the thread was really long.

**Comment by buttercookie42** [comment]
@Mentis Okay, so that means that saving from data isn't completely broken, and restoring the search query on onliner.by is broken on Desktop as well [1], so that one is not a Fenix-specific problem.

[1] Though interestingly enough it does work in an older Firefox version.

**Comment by buttercookie42** [comment]
One thing that Fennec did was to effectively throttle memory pressure events through the way it tracked memory pressure [through the MemoryMonitor](https://hg.mozilla.org/releases/mozilla-esr68/file/tip/mobile/android/base/java/org/mozilla/gecko/MemoryMonitor.java).
I wonder to what extent that might explain the difference, or whether other factors are at play here (some actual bug in the tab unloading logic, Android having become more aggressive about signalling memory pressure, Fenix actually using more memory than Fennec?, ...)?

**Comment by pocmo** [comment]
We are definitely too aggressively freeing memory right now, I think. I filed this issue some time ago and intent to work on it soon: https://github.com/mozilla-mobile/android-components/issues/7011
We are currently always reacting to `TRIM_MEMORY_UI_HIDDEN` and trimming all non selected tabs. That's why it is easily reproducible with backgrounding right now. However some pages (like YouTube) just do not restore like you'd expect (but also in Fennec) and this may still happen, but just more rarely.

**Comment by buttercookie42** [comment]
That explains it - 'TRIM_MEMORY_UI_HIDDEN' definitively happens too early and often to discard tabs for.
@Mentis https://bugzilla.mozilla.org/show_bug.cgi?id=1640718 for the specific onliner.by problem.

**Comment by pocmo** [comment]
We landed a patch in AC to fix our memory pressure level handling. It should show up in Nightly soon.

**Comment by victor-bayas** [comment]
I tried latest Fenix debug version and it's working fine, thanks @pocmo 👏🏻👏🏻👏🏻

**Comment by xsikor** [comment]
Yay!! It's fixed!
Now I can use preview as default browser
Thank your all!

**Comment by Maxnor** [comment]
Also fixed the problem for me. Thanks

**Comment by lindongbin** [comment]
not fix on 5.28 pm nightly version
type something in input box or search box on google
open anther tab
Switch to the background and then back to the foreground
The contents of the search box disappear

**Comment by andreicristianpetcu** [comment]
@lindongbin it does not happen for me with the latest nightly. Please get your build from here https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/project.mobile.fenix.v2.fennec-nightly.latest/artifacts/public/build/arm64-v8a/geckoNightly/target.apk

**Comment by lindongbin** [comment]
> 
> 
> @lindongbin it does not happen for me with the latest nightly. Please get your build from here https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest

confirm that the latest nightly version (5.29 am) background page will not reload, thanks

**Comment by andreicristianpetcu** [comment]
The Google Play "Nightly" is more like "Some build from this week :crossed_fingers:". The real Nightly builds are from Mozilla servers.

**Comment by andreicristianpetcu** [comment]
Should we close this?

**Comment by SS1113** [comment]
@andreicristianpetcu Mozilla should share the builds with others who are willing to test early software builds. The links to the Firefox taskcluster are hidden and not mentioned and can't be found easily anywhere.

I stopped testing builds around when taskcluster links were changed a few months ago and only got them a while ago when someone shared this link with me: https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2 on Reddit. I have reported quite a lot bugs since having access to the builds early. Not only this they also don't publish compiled builds of Firefox Preview early and only have the source code. They only publish compiled builds once the Play Store also has it.

I request Mozilla to link the builds on GitHub readme page or somewhere easily visible. If someone willingly wants to test the early builds then I think Mozilla shouldn't stop them. It is apparent that Mozilla should do this as experienced recently with the Play Store situation. Now I know I can have access to Nightly versions early when things get normal; that is not what I want; I want to have access anything that Firefox developers publish. Just like the following link https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2

So please publish the links to the taskcluster builds. So that I don't lose access to the build when Mozilla changes the links to the taskcluster again.

**Comment by Maxnor** [comment]
Nightly 200528 06:00 (Build #21490607) from playstore yesterday solved the problem for me. 
How/when will the fix be ported to the non-nightly?

**Comment by SS1113** [comment]
@Maxnor when they believe it is stable enough I think.

**Comment by victor-bayas** [comment]
> The Google Play "Nightly" is more like "Some build from this week :crossed_fingers:". The real Nightly builds are from Mozilla servers.

My Nightly is updating every day from the Play Store

**Comment by SS1113** [comment]
@victor-bayas Yes, the situation is okay recently.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 5/29 with:
- Google Pixel (Android 10),
- Sony Xperia Z5 Premium (Android 7.1.1), and
- OnePlus 5T (Android 9).

**Comment by pocmo** [comment]
Thank you all for verifying and providing steps to reproduce early. That was helpful for figuring out the problem.

Regarding Nightly builds: Whenever a Nightly build shows up on taskcluster that build also gets published to Google Play. It takes a while until they show up for end users as an update though. So there are no hidden builds on taskcluster! The whole process just takes some time and well, sometimes there's also something broken in the pipeline. :)

**Comment by SS1113** [comment]
@pocmo I'm not saying that the builds themselves are hidden, what I'm saying is that the links to the Taskcluster aren't found easily anywhere.

**Comment by hakkikaancaliskan** [comment]
@pocmo hey dev, does this patch included in new beta update? I think this is deal breaker without it.

**Comment by SS1113** [comment]
@hakkikaancaliskan I have `5.1.0-beta.3`, and it still reloads the webpages.

**Comment by victor-bayas** [comment]
> @hakkikaancaliskan I have `5.1.0-beta.3`, and it still reloads the webpages.

Can confirm in my SM-G970F, issue persists in Fenix 5.1 (non-nightly)

**Comment by liuche** [comment]
Since this just landed, it won't be in the 5.1 release, but will be part of the 5.2 release.

**Comment by SS1113** [comment]
@liuche Is it available in the `77.0.0-beta.1`?

**Comment by victor-bayas** [comment]
> @liuche Is it available in the `77.0.0-beta.1`?

I downloaded the 77.0 beta 1 from here https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-beta/latest and it still discards backgrounded tabs

**Comment by SS1113** [comment]
@victor-bayas then we need to wait another 2 weeks before it gets included in 5.2. I think there's no difference between Firefox Preview and Firefox Beta; they both have the same codebase of you are keeping your build up-to-date form the Taskcluster.

**Comment by pocmo** [comment]
`77.0.0-beta.1` is the same as `5.1.0-beta.3` - The only difference being the versioning for different channels (Firefox Beta 77.0 vs. Firefox Preview 5.1)

**Comment by esjarc** [comment]
> The only difference being the versioning for different channels (Firefox Beta 77.0 vs. Firefox Preview 5.1)

But about:config is blocked in [Preview](https://play.google.com/store/apps/details?id=org.mozilla.fenix) and available in [Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta)? Are you sure the only difference is versioning?

![Firefox Beta](https://user-images.githubusercontent.com/53082773/84009209-3a241d80-a973-11ea-8129-405ef4b5b038.png)
![Firefox Preview](https://user-images.githubusercontent.com/53082773/84009212-3abcb400-a973-11ea-842b-633f869fb710.png)

**Comment by madb1lly** [comment]
Hi all,

I'm pretty sure this bug is still present, I can't keep anywhere near as many tabs live in Fenix as I can in Fennec.

Shall i raise a new issue?

Cheers 🙂

**Comment by lindongbin** [comment]
> Hi all,
> 
> I'm pretty sure this bug is still present, I can't keep anywhere near as many tabs live in Fenix as I can in Fennec.
> 
> Shall i raise a new issue?
> 
> Cheers 🙂

Sometimes switching tabs or open new website in the foreground will also cause other tabs to reload

**Comment by sheepycoder** [comment]
I also have this issue on latest nightly. And it is made worse by https://github.com/mozilla-mobile/fenix/issues/12664. Please reopen this issue.

**Comment by sheepycoder** [comment]
https://github.com/mozilla-mobile/fenix/issues/12731

**Comment by madb1lly** [comment]
Hi all,
Since this issue is closed it's probably best to post in @lorinet's new issue #12731. 
Cheers 🙂
