### ISSUE TITLE
[Bug]  Top Sites Needlessly Wrap in Horizontal Mode

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#9088]
![Screenshot_20200310-130114](https://user-images.githubusercontent.com/46655/76345811-f9642c00-62d1-11ea-976b-cd3171f89fdb.png)

## Steps to reproduce
1. Open the app with more than 5 top sites
2.  Turn your phone horizontal

### Expected behavior

All top sites are on one line

### Actual behavior

Top sites wrap

### Device information

* Android device: Pixel 4

**Comment by mcarare** [comment]
@darkwing On what version of Fenix did you test this? This should be fixed on the latest master.

**Comment by Cheap-Skate** [comment]
I have unnecessary wrapping / left justification in portrait mode on my Galaxy A40, with today's Nightly.

This behavior is new in the last couple of days, previously the grid was 5 wide and properly centered, now it's 4 wide and left justified.

Galaxy A40, Android 9, today's Fenix Nightly

![Screenshot_20200311-085951_Firefox Nightly](https://user-images.githubusercontent.com/40568887/76399650-e22b4a00-6376-11ea-944e-2faf8adbecf1.jpg)

**Comment by darkwing** [comment]
Good shout!  This is fixed!

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 3/19 #20790605.

Device: Samsung Galaxy Tab S6 (Android 9).

**Comment by Cheap-Skate** [comment]
I still have the left justification problem on today's Fenix, should I open a new issue? [I'm not sure what your comment https://github.com/mozilla-mobile/fenix/issues/9088#issuecomment-597651645 was referring to]

cheers

Galaxy A40, Android 9
Today's Fenix Nighly
