### ISSUE TITLE
[Bug] (regression) changing language requires an app restart now

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9413]
### Steps to reproduce

1. change the language within Fenix

### Expected behavior

The change applies immediately, as before https://github.com/mozilla-mobile/fenix/commit/5202c0a2f925b772ec8dca9e652b2e9593a620bf.

### Actual behavior

You have to restart Fenix to see the change of the language. It's a regression from the appcompat update in https://github.com/mozilla-mobile/fenix/commit/5202c0a2f925b772ec8dca9e652b2e9593a620bf.

But good news is that the update fixed #7559 - an app start is also required in this case, but it's much better than a feature that is not working at all.

/cc @eliserichards @ekager 

### Device information

* Android device: OnePlus 7T Pro McLaren Edition, OxygenOS 10.0.7 (Android 10)
* Fenix version: master branch revision 40ba43311e1782ffe6602e90d70c41a7b104998e

**Comment by Diana-Rus** [comment]
Hi, I confirm issue on FIrefox Preview Nightly 200326 (Build #20860605) GV: 76.0a1-20200324093140 with:
- Google Pixel 3 XL (Android 9)
![20200326-160131](https://user-images.githubusercontent.com/49859863/77656182-2a07bf00-6f7c-11ea-9978-1f0023540e92.gif)

- Samsung Galaxy S9 (Android 8)
- Sony Xperia Z5 (Android 7)

**Comment by liuche** [comment]
This should be fixed by https://github.com/mozilla-mobile/android-components/issues/6517, which landed earlier, so it will probably be in the next AC nightly version that gets pulled into fenix.

**Comment by cadeyrn** [comment]
This is working for me now.

**Comment by softvision-miralobontiu** [comment]
Hi all,

This is not entirely fixed yet. 
- In Fenix, I've set the language to Arabic/Urdu (or any RTL language), the language changed as expected in the app.
- Change back to follow the device's language, the app remained stuck between languages, meaning the language is changed, but the app is stuck in the RTL position.
- If Fenix is in the background and reopened, nothing changes. 
- If Fenix is closed and reopened, it is working as expected again. 

**Device information:**
* Android devices: HTC 10 (Android 8), Samsung Galaxy S9 (Android 8), and Motorola G6 (Android 8),
* Fenix version: Nightly build from 4/8
* Not reproducible on Google Pixel (Android 10), OnePlus 5T (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), OnePlus A3 (Android 6.0.1), LG g7 fit (Android 8.1)


Please see the attached GIF for better understanding:
![language](https://user-images.githubusercontent.com/40694158/78769783-739dd400-7996-11ea-8252-c2355e2cd200.gif)

**Comment by liuche** [comment]
That's definitely kind of weird behavior. @boek what do you think, since it's on a few devices (and I assume for RTL switching back and forth) do you want to file this as a follow-up, or try to fix it here?

**Comment by boek** [comment]
@liuche I think we should try to fix. It looks like it's an entire Android version

**Comment by ebalazs-sv** [comment]
This is reproducible on Fenix Beta 4.3.0-beta.1 from 4/14 with Motorola Moto G6 (Android 8).

**Comment by boek** [comment]
This needs QA in 4.3. Once https://github.com/mozilla-mobile/android-components/pull/6690 lands we can test on Nightly

**Comment by softvision-miralobontiu** [comment]
Hi all!

The issue regarding [RTL languages](https://github.com/mozilla-mobile/fenix/issues/9413#issuecomment-610863611) is still reproducible on Nightly build from 4/21 on HTC 10 (Android8), LG G7 Fit (Android 8.1), and Samsung Galaxy S9 (Android 8) - please see the GIF below taken with HTC device:

![nightly](https://user-images.githubusercontent.com/40694158/79863266-1f581280-83e0-11ea-98ad-837ca626e633.gif)


**On HTC 10, and Samsung Galaxy S9, the issue is fixed on Beta 4.3.0-beta.2** - please see the GIF below:

![beta](https://user-images.githubusercontent.com/40694158/79863950-4a8f3180-83e1-11ea-87cc-278855a5f648.gif)


**However, on LG G7 Fit (Android 8.1) is not fixed yet, on Beta 4.3.0-beta.2** - please see the GIF below:

![20200421_145649](https://user-images.githubusercontent.com/40694158/79863925-3fd49c80-83e1-11ea-80c8-88548849d832.gif)

I'll remove the qa:needed flag for now.

**Comment by sv-sdeiac** [comment]
Hi, this issue is still reproducible using the latest version of Firefox Preview Nightly 4/30 #21210606.

Device:
- LG G7 fit (Android 8.1).

I'll remove the qa:needed flag till new updates are coming.

**Comment by boek** [comment]
🤦 will be fixed with https://github.com/mozilla-mobile/android-components/pull/6834

**Comment by liuche** [comment]
This should have landed in Nightly by now since that AC issue is fixed and merged, so adding the QA-needed label again.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 5/18 with HTC 10 (Android 8), and LG G7 Fit (Android 8.1).
