### ISSUE TITLE
[Bug] vertical alignment of add-on rating

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9710]
### Steps to reproduce

1. open the add-ons manager
2. look at the rating
3. go into the details view of an add-on
4. look at the rating

### Expected behavior

The stars and the number of users should be aligned in the middle (steps 2 and 4).

### Actual behavior

It's not correctly aligned.

![Screenshot_20200404-091140](https://user-images.githubusercontent.com/1100614/78421041-1384f600-7655-11ea-9710-e55bece001c2.jpg)
![Screenshot_20200404-091135](https://user-images.githubusercontent.com/1100614/78421045-18e24080-7655-11ea-9f7d-b783ab51dd3d.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition, OxygenOS 10.0.7 (Android 10)
* Fenix version: master branch revision b35704beed2ba48331d93485c499d7cf05fd9d82

**Comment by ValentinTimisica** [comment]
The alignment from:
- step 2 should be fixed in https://github.com/mozilla-mobile/android-components/pull/6655.
- step 4 should be fixed in https://github.com/mozilla-mobile/fenix/pull/9950.

**Comment by cadeyrn** [comment]
@ValentinTimisica Thank you for working on this!

It looks much better now but please note that it's still not perfectly aligned.

List view:

<img width="998" alt="Bildschirmfoto 2020-04-16 um 21 11 55" src="https://user-images.githubusercontent.com/1100614/79496804-f540d200-8026-11ea-9b84-98a5bb67660e.png">

Details view:

<img width="763" alt="Bildschirmfoto 2020-04-16 um 21 11 49" src="https://user-images.githubusercontent.com/1100614/79496815-fa9e1c80-8026-11ea-86da-fd7898cb3f62.png">

**Comment by ekager** [comment]
Reopening for QA

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 4/21 #21121811.
The add-on rating stars are now correctly aligned on add-ons manager and the details view.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG g7 fit (Android 8.1).
