### ISSUE TITLE
[Bug]Collections can't be expanded

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9913]
## Prerequisites
Have a Collection created

## Steps to reproduce
1. Tap on the previously create collections area (next to the collections name)

### Expected behavior
Collection should be expanded

### Actual behavior
Seems to be freeze

### Device information

* Android device:  OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Fenix beta 4.3.0-beta.1 (Build #21050021)
• Debug build from Master 4/14

### Notes
► Video
![20200414-151141-1](https://user-images.githubusercontent.com/51314259/79225453-62a50500-7e65-11ea-812a-9934f0a1d1fb.gif)

► Video
![20200414-150148](https://user-images.githubusercontent.com/51314259/79225336-3ab5a180-7e65-11ea-9c43-b57a398c7bd3.gif)

❗ Seems to be happening when performing actions on the hidden collections buttons.

**Comment by mcarare** [comment]
Should be fixed when https://github.com/mozilla-mobile/fenix/pull/10144/commits/cf847c46f8b1a1c2db7fb4bd9d3a17fa05f30b4b lands.

**Comment by Diana-Rus** [comment]
Hi, verified the issue as fixed on Firefox Preview Nightly 4/27 with Sony Xperia Z5 (Android 7) and Google Pixel 3 XL (Android 9), but with Samsung Galaxy S9 (Android 8) the issue is still reproducible - please check GIF.

Sony Xperia Z5 - GIF - ✔️
![20200427-111308](https://user-images.githubusercontent.com/49859863/80352381-7a748400-887c-11ea-83d2-704a005ab547.gif)

Pixel 3 XL - GIF - ✔️
![20200427-112625](https://user-images.githubusercontent.com/49859863/80352625-d212ef80-887c-11ea-87fc-8d9a89bd9b41.gif)

Samsung Galaxy S9 - GIF - ❌
![20200427-115602](https://user-images.githubusercontent.com/49859863/80353890-ae50a900-887e-11ea-882b-e0b538044d02.gif)

**Issue related to the one described in  #9914 as it is derived**

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 4/28** with **Google Pixel 4 XL (10), Samsung Galaxy S9 (9).**
